//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pwiz.PanoramaClient.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("pwiz.PanoramaClient.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ChromLib {
            get {
                object obj = ResourceManager.GetObject("ChromLib", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Copy {
            get {
                object obj = ResourceManager.GetObject("Copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Edit_Undo {
            get {
                object obj = ResourceManager.GetObject("Edit_Undo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Folder {
            get {
                object obj = ResourceManager.GetObject("Folder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: {0}.
        /// </summary>
        public static string GenericState_AppendErrorAndUri_Error___0_ {
            get {
                return ResourceManager.GetString("GenericState_AppendErrorAndUri_Error___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL: {0}.
        /// </summary>
        public static string GenericState_AppendErrorAndUri_URL___0_ {
            get {
                return ResourceManager.GetString("GenericState_AppendErrorAndUri_URL___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Icojam_Blueberry_Basic_Arrow_up {
            get {
                object obj = ResourceManager.GetObject("Icojam-Blueberry-Basic-Arrow-up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select a file first!.
        /// </summary>
        public static string PanoramaFilePicker_Open_Click_You_must_select_a_file_first_ {
            get {
                return ResourceManager.GetString("PanoramaFilePicker_Open_Click_You_must_select_a_file_first_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not authenticate user. Response received from server: {0} {1}.
        /// </summary>
        public static string PanoramaUtil_EnsureLogin_Could_not_authenticate_user__Response_received_from_server___0___1_ {
            get {
                return ResourceManager.GetString("PanoramaUtil_EnsureLogin_Could_not_authenticate_user__Response_received_from_serv" +
                        "er___0___1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server did not return a valid JSON response. {0} is not a Panorama server..
        /// </summary>
        public static string PanoramaUtil_EnsureLogin_Server_did_not_return_a_valid_JSON_response___0__is_not_a_Panorama_server_ {
            get {
                return ResourceManager.GetString("PanoramaUtil_EnsureLogin_Server_did_not_return_a_valid_JSON_response___0__is_not_" +
                        "a_Panorama_server_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected JSON response from the server: {0}.
        /// </summary>
        public static string PanoramaUtil_EnsureLogin_Unexpected_JSON_response_from_the_server___0_ {
            get {
                return ResourceManager.GetString("PanoramaUtil_EnsureLogin_Unexpected_JSON_response_from_the_server___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a Panorama folder.
        /// </summary>
        public static string PanoramaUtil_VerifyFolder__0__is_not_a_Panorama_folder {
            get {
                return ResourceManager.GetString("PanoramaUtil_VerifyFolder__0__is_not_a_Panorama_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder {0} does not exist on the Panorama server {1}.
        /// </summary>
        public static string PanoramaUtil_VerifyFolder_Folder__0__does_not_exist_on_the_Panorama_server__1_ {
            get {
                return ResourceManager.GetString("PanoramaUtil_VerifyFolder_Folder__0__does_not_exist_on_the_Panorama_server__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User {0} does not have permissions to upload to the Panorama folder {1}.
        /// </summary>
        public static string PanoramaUtil_VerifyFolder_User__0__does_not_have_permissions_to_upload_to_the_Panorama_folder__1_ {
            get {
                return ResourceManager.GetString("PanoramaUtil_VerifyFolder_User__0__does_not_have_permissions_to_upload_to_the_Pan" +
                        "orama_folder__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server {0} does not exist..
        /// </summary>
        public static string ServerState_GetErrorMessage_The_server__0__does_not_exist_ {
            get {
                return ResourceManager.GetString("ServerState_GetErrorMessage_The_server__0__does_not_exist_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to connect to the server {0}..
        /// </summary>
        public static string ServerState_GetErrorMessage_Unable_to_connect_to_the_server__0__ {
            get {
                return ResourceManager.GetString("ServerState_GetErrorMessage_Unable_to_connect_to_the_server__0__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap up_pro32 {
            get {
                object obj = ResourceManager.GetObject("up_pro32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The username and password could not be authenticated with the panorama server..
        /// </summary>
        public static string UserState_GetErrorMessage_The_username_and_password_could_not_be_authenticated_with_the_panorama_server_ {
            get {
                return ResourceManager.GetString("UserState_GetErrorMessage_The_username_and_password_could_not_be_authenticated_wi" +
                        "th_the_panorama_server_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error authenticating user credentials on the server {0}..
        /// </summary>
        public static string UserState_GetErrorMessage_There_was_an_error_authenticating_user_credentials_on_the_server__0__ {
            get {
                return ResourceManager.GetString("UserState_GetErrorMessage_There_was_an_error_authenticating_user_credentials_on_t" +
                        "he_server__0__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading {0}.
        /// </summary>
        public static string WebPanoramaClient_DownloadFile_Downloading__0_ {
            get {
                return ResourceManager.GetString("WebPanoramaClient_DownloadFile_Downloading__0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the folder where the file will be downloaded.
        /// </summary>
        public static string WebPanoramaClient_SaveFile_Select_the_folder_where_the_file_will_be_downloaded {
            get {
                return ResourceManager.GetString("WebPanoramaClient_SaveFile_Select_the_folder_where_the_file_will_be_downloaded", resourceCulture);
            }
        }
    }
}
