/*
 * Original author: Alana Killeen <killea .at. u.washington.edu>,
 *                  MacCoss Lab, Department of Genome Sciences, UW
 *
 * Copyright 2010 University of Washington - Seattle, WA
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
namespace pwiz.Skyline.Model.DocSettings
{
    public static class UniMod
    {
        public static StaticMod[] StructuralMods { get; private set; }
        public static StaticMod[] IsotopeMods { get; private set; }
        public static StaticMod[] HiddenStructuralMods { get; private set; }
        public static StaticMod[] HiddenIsotopeMods { get; private set; }

        public static void Init()
        {
// ReSharper disable RedundantExplicitArrayCreation
            StructuralMods = new[] {   
                new StaticMod("Acetyl (K)", "K", null, "H2C2O"),
                new StaticMod("Acetyl (N-term)", null, ModTerminus.N, "H2C2O"),
                new StaticMod("Amidated (C-term)", null, ModTerminus.C, "HN - O"),
                new StaticMod("Biotin (K)", "K", null, "H14C10N2O2S"),
                new StaticMod("Biotin (N-term)", null, ModTerminus.N, "H14C10N2O2S"),
                new StaticMod("Carbamidomethyl (C)", "C", null, "H3C2NO"),
                new StaticMod("Carbamyl (K)", "K", null, "HCNO"),
                new StaticMod("Carbamyl (N-term)", null, ModTerminus.N, "HCNO"),
                new StaticMod("Carboxymethyl (C)", "C", null, "H2C2O2"),
                new StaticMod("Cation:Na (C-term)", null, ModTerminus.C, "Na - H"),
                new StaticMod("Cation:Na (DE)", "D, E", null, "Na - H"),
                new StaticMod("cysTMT6plex (C)", "C", null, "H25C10C'4N2N'O2S"),
                new StaticMod("Deamidated (NQ)", "N, Q", null, "O - HN"),
                new StaticMod("Dehydro (C)", "C", null, "-H"),
                new StaticMod("Dioxidation (M)", "M", null, "O2"),
                new StaticMod("Ethanolyl (C)", "C", null, "H4C2O"),
                new StaticMod("ExacTagAmine (K)", "K", null, "H52C25C'12N8N'6O19S"),
                new StaticMod("ExacTagThiol (C)", "C", null, "H50C23C'12N8N'6O18"),
                new StaticMod("Formyl (N-term)", null, ModTerminus.N, "CO"),
                new StaticMod("Guanidinyl (K)", "K", null, "H2CN2"),
                new StaticMod("ICAT-C (C)", "C", null, "H17C10N3O3"),
                new StaticMod("ICAT-C:13C(9) (C)", "C", null, "H17CC'9N3O3"),
                new StaticMod("ICPL (K)", "K", null, "H3C6NO"),
                new StaticMod("ICPL:13C(6) (K)", "K", null, "H3C'6NO"),
                new StaticMod("ICPL:13C(6)2H(4) (K)", "K", null, "H'4C'6NO - H"),
                new StaticMod("ICPL:13C(6)2H(4) (N-term)", null, ModTerminus.N, "H'4C'6NO - H"),
                new StaticMod("ICPL:2H(4) (K)", "K", null, "H'4C6NO - H"),
                new StaticMod("iTRAQ4plex (K)", "K", null, "H12C4C'3NN'O"),
                new StaticMod("iTRAQ4plex (N-term)", null, ModTerminus.N, "H12C4C'3NN'O"),
                new StaticMod("iTRAQ4plex (Y)", "Y", null, "H12C4C'3NN'O"),
                new StaticMod("iTRAQ8plex (K)", "K", null, "H24C7C'7N3N'O3"),
                new StaticMod("iTRAQ8plex (N-term)", null, ModTerminus.N, "H24C7C'7N3N'O3"),
                new StaticMod("iTRAQ8plex (Y)", "Y", null, "H24C7C'7N3N'O3"),
                new StaticMod("Methyl (C-term)", null, ModTerminus.C, "H2C"),
                new StaticMod("Methyl (DE)", "D, E", null, "H2C"),
                new StaticMod("Methylthio (C)", "C", null, "H2CS"),
                new StaticMod("mTRAQ (K)", "K", null, "H12C7N2O"),
                new StaticMod("mTRAQ (N-term)", null, ModTerminus.N, "H12C7N2O"),
                new StaticMod("mTRAQ (Y)", "Y", null, "H12C7N2O"),
                new StaticMod("mTRAQ:13C(3)15N(1) (K)", "K", null, "H12C4C'3NN'O"),
                new StaticMod("mTRAQ:13C(3)15N(1) (N-term)", null, ModTerminus.N, "H12C4C'3NN'O"),
                new StaticMod("mTRAQ:13C(3)15N(1) (Y)", "Y", null, "H12C4C'3NN'O"),
                new StaticMod("NIPCAM (C)", "C", null, "H9C5NO"),
                new StaticMod("Oxidation (HW)", "H, W", null, "O"),
                new StaticMod("Oxidation (M)", "M", null, "O"),
                new StaticMod("Phospho (ST)", "S, T", null, "HO3P"),
                new StaticMod("Phospho (Y)", "Y", null, "HO3P"),
                new StaticMod("Propionamide (C)", "C", null, "H5C3NO"),
                new StaticMod("Pyridylethyl (C)", "C", null, "H7C7N"),
                new StaticMod("Sulfo (S)", "S", null, "O3S"),
                new StaticMod("Sulfo (T)", "T", null, "O3S"),
                new StaticMod("Sulfo (Y)", "Y", null, "O3S"),
                new StaticMod("TMT (K)", "K", null, "H20C12N2O2"),
                new StaticMod("TMT (N-term)", null, ModTerminus.N, "H20C12N2O2"),
                new StaticMod("TMT2plex (K)", "K", null, "H20C11C'N2O2"),
                new StaticMod("TMT2plex (N-term)", null, ModTerminus.N, "H20C11C'N2O2"),
                new StaticMod("TMT6plex (K)", "K", null, "H20C8C'4NN'O2"),
                new StaticMod("TMT6plex (N-term)", null, ModTerminus.N, "H20C8C'4NN'O2"),
            };

            IsotopeMods = new StaticMod[] {
                new StaticMod("Label:18O(1) (C-term)", null, ModTerminus.C, "O' - O"),
                new StaticMod("Label:18O(2) (C-term)", null, ModTerminus.C, "O'2 - O2"),
                new StaticMod("Label:15N(1) (F)", "F", null, LabelAtoms.N15),
            };

            HiddenStructuralMods = new StaticMod[] {
                new StaticMod("15dB-biotin (C)", "C", null, "H54C35N4O4S"),
                new StaticMod("2-succinyl (C)", "C", null, "H4C4O4"),
                new StaticMod("2HPG (R)", "R", null, "H10C16O5"),
                new StaticMod("3-deoxyglucosone (R)", "R", null, "H8C6O4"),
                new StaticMod("3sulfo (N-term)", null, ModTerminus.N, "H4C7O4S"),
                new StaticMod("4-ONE (C)", "C", null, "H14C9O2"),
                new StaticMod("4-ONE (H)", "H", null, "H14C9O2"),
                new StaticMod("4-ONE (K)", "K", null, "H14C9O2"),
                new StaticMod("4-ONE+Delta:H(-2)O(-1) (C)", "C", null, "H12C9O"),
                new StaticMod("4-ONE+Delta:H(-2)O(-1) (H)", "H", null, "H12C9O"),
                new StaticMod("4-ONE+Delta:H(-2)O(-1) (K)", "K", null, "H12C9O"),
                new StaticMod("4AcAllylGal (C)", "C", null, "H24C17O9"),
                new StaticMod("a-type-ion (C-term)", null, ModTerminus.C, "-H2CO2"),
                new StaticMod("AccQTag (K)", "K", null, "H6C10N2O"),
                new StaticMod("AccQTag (N-term)", null, ModTerminus.N, "H6C10N2O"),
                new StaticMod("Acetyl (C)", "C", null, "H2C2O"),
                new StaticMod("Acetyl (H)", "H", null, "H2C2O"),
                new StaticMod("Acetyl (S)", "S", null, "H2C2O"),
                new StaticMod("Acetyl (T)", "T", null, "H2C2O"),
                new StaticMod("Acetyl (Y)", "Y", null, "H2C2O"),
                new StaticMod("Acetyl:2H(3) (K)", "K", null, "H'3C2O - H"),
                new StaticMod("Acetyl:2H(3) (N-term)", null, ModTerminus.N, "H'3C2O - H"),
                new StaticMod("ADP-Ribosyl (C)", "C", null, "H21C15N5O13P2"),
                new StaticMod("ADP-Ribosyl (E)", "E", null, "H21C15N5O13P2"),
                new StaticMod("ADP-Ribosyl (N)", "N", null, "H21C15N5O13P2"),
                new StaticMod("ADP-Ribosyl (R)", "R", null, "H21C15N5O13P2"),
                new StaticMod("ADP-Ribosyl (S)", "S", null, "H21C15N5O13P2"),
                new StaticMod("AEBS (H)", "H", null, "H9C8NO2S"),
                new StaticMod("AEBS (K)", "K", null, "H9C8NO2S"),
                new StaticMod("AEBS (S)", "S", null, "H9C8NO2S"),
                new StaticMod("AEBS (Y)", "Y", null, "H9C8NO2S"),
                new StaticMod("AEC-MAEC (S)", "S", null, "H5C2NS - O"),
                new StaticMod("AEC-MAEC (T)", "T", null, "H5C2NS - O"),
                new StaticMod("AEC-MAEC:2H(4) (S)", "S", null, "HH'4C2NS - O"),
                new StaticMod("AEC-MAEC:2H(4) (T)", "T", null, "HH'4C2NS - O"),
                new StaticMod("AHA-Alkyne (M)", "M", null, "H5C4N5O - S"),
                new StaticMod("AHA-Alkyne-KDDDD (M)", "M", null, "H37C26N11O14 - S"),
                new StaticMod("Amidine (K)", "K", null, "H3C2N"),
                new StaticMod("Amidine (N-term)", null, ModTerminus.N, "H3C2N"),
                new StaticMod("Amidino (C)", "C", null, "H2CN2"),
                new StaticMod("Amino (Y)", "Y", null, "HN"),
                new StaticMod("Ammonia-loss (N)", "N", null, "-H3N"),
                new StaticMod("Ammonium (C-term)", null, ModTerminus.C, "H3N"),
                new StaticMod("Ammonium (DE)", "D, E", null, "H3N"),
                new StaticMod("AMTzHexNAc2 (N)", "N", null, "H30C19N6O10"),
                new StaticMod("AMTzHexNAc2 (S)", "S", null, "H30C19N6O10"),
                new StaticMod("AMTzHexNAc2 (T)", "T", null, "H30C19N6O10"),
                new StaticMod("Archaeol (C)", "C", null, "H86C43O2"),
                new StaticMod("Arg->GluSA (R)", "R", null, "O - H5CN3"),
                new StaticMod("Arg->Npo (R)", "R", null, "C3NO2 - H"),
                new StaticMod("Arg->Orn (R)", "R", null, "-H2CN2"),
                new StaticMod("Arg2PG (R)", "R", null, "H10C16O4"),
                new StaticMod("Argbiotinhydrazide (R)", "R", null, "H13C9NO2S"),
                new StaticMod("AROD (C)", "C", null, "H52C35N10O9S2"),
                new StaticMod("Atto495Maleimide (C)", "C", null, "H32C27N5O3"),
                new StaticMod("Bacillosamine (N)", "N", null, "H16C10N2O4"),
                new StaticMod("BADGE (C)", "C", null, "H24C21O4"),
                new StaticMod("BDMAPP (H)", "H", null, "H12C11NOBr"),
                new StaticMod("BDMAPP (K)", "K", null, "H12C11NOBr"),
                new StaticMod("BDMAPP (W)", "W", null, "H12C11NOBr"),
                new StaticMod("BDMAPP (Y)", "Y", null, "H12C11NOBr"),
                new StaticMod("Benzoyl (K)", "K", null, "H4C7O"),
                new StaticMod("Benzoyl (N-term)", null, ModTerminus.N, "H4C7O"),
                new StaticMod("BHAc (K)", "K", null, "H25C16N3O3S"),
                new StaticMod("BHT (C)", "C", null, "H22C15O"),
                new StaticMod("BHT (H)", "H", null, "H22C15O"),
                new StaticMod("BHT (K)", "K", null, "H22C15O"),
                new StaticMod("BHTOH (C)", "C", null, "H22C15O2"),
                new StaticMod("BHTOH (H)", "H", null, "H22C15O2"),
                new StaticMod("BHTOH (K)", "K", null, "H22C15O2"),
                new StaticMod("Biotin-HPDP (C)", "C", null, "H32C19N4O3S2"),
                new StaticMod("Biotin-maleimide (C)", "C", null, "H27C20N5O5S"),
                new StaticMod("Biotin-PEG-PRA (M)", "M", null, "H42C26N8O7"),
                new StaticMod("Biotin-PEO-Amine (D)", "D", null, "H28C16N4O3S"),
                new StaticMod("Biotin-PEO-Amine (E)", "E", null, "H28C16N4O3S"),
                new StaticMod("Biotin-PEO4-hydrazide (C-term)", null, ModTerminus.C, "H37C21N5O6S"),
                new StaticMod("Biotin-phenacyl (C)", "C", null, "H38C29N8O6S"),
                new StaticMod("Biotin-phenacyl (H)", "H", null, "H38C29N8O6S"),
                new StaticMod("Biotin-phenacyl (S)", "S", null, "H38C29N8O6S"),
                new StaticMod("BisANS (K)", "K", null, "H20C32N2O6S2"),
                new StaticMod("BITC (C)", "C", null, "H7C8NS"),
                new StaticMod("BITC (K)", "K", null, "H7C8NS"),
                new StaticMod("BITC (N-term)", null, ModTerminus.N, "H7C8NS"),
                new StaticMod("BMOE (C)", "C", null, "H8C10N2O4"),
                new StaticMod("Bodipy (C)", "C", null, "H21C20N4O3F2B"),
                new StaticMod("Bromo (F)", "F", null, "Br - H"),
                new StaticMod("Bromo (H)", "H", null, "Br - H"),
                new StaticMod("Bromo (W)", "W", null, "Br - H"),
                new StaticMod("Bromobimane (C)", "C", null, "H10C10N2O2"),
                new StaticMod("C8-QAT (K)", "K", null, "H29C14NO"),
                new StaticMod("C8-QAT (N-term)", null, ModTerminus.N, "H29C14NO"),
                new StaticMod("CAF (N-term)", null, ModTerminus.N, "H4C3O4S"),
                new StaticMod("CAMthiopropanoyl (K)", "K", null, "H7C5NO2S"),
                new StaticMod("Can-FP-biotin (S)", "S", null, "H34C19N3O5PS"),
                new StaticMod("Can-FP-biotin (T)", "T", null, "H34C19N3O5PS"),
                new StaticMod("Can-FP-biotin (Y)", "Y", null, "H34C19N3O5PS"),
                new StaticMod("Carbamidomethyl (D)", "D", null, "H3C2NO"),
                new StaticMod("Carbamidomethyl (E)", "E", null, "H3C2NO"),
                new StaticMod("Carbamidomethyl (H)", "H", null, "H3C2NO"),
                new StaticMod("Carbamidomethyl (K)", "K", null, "H3C2NO"),
                new StaticMod("Carbamidomethyl (N-term)", null, ModTerminus.N, "H3C2NO"),
                new StaticMod("CarbamidomethylDTT (C)", "C", null, "H11C6NO3S2"),
                new StaticMod("Carbamyl (C)", "C", null, "HCNO"),
                new StaticMod("Carbamyl (M)", "M", null, "HCNO"),
                new StaticMod("Carbamyl (R)", "R", null, "HCNO"),
                new StaticMod("Carbamyl (S)", "S", null, "HCNO"),
                new StaticMod("Carbamyl (T)", "T", null, "HCNO"),
                new StaticMod("Carbamyl (Y)", "Y", null, "HCNO"),
                new StaticMod("Carbofuran (S)", "S", null, "H4C2NO"),
                new StaticMod("Carboxy (D)", "D", null, "CO2"),
                new StaticMod("Carboxy (E)", "E", null, "CO2"),
                new StaticMod("Carboxy (K)", "K", null, "CO2"),
                new StaticMod("Carboxy (W)", "W", null, "CO2"),
                new StaticMod("Carboxyethyl (K)", "K", null, "H4C3O2"),
                new StaticMod("Carboxymethyl (K)", "K", null, "H2C2O2"),
                new StaticMod("Carboxymethyl (N-term)", null, ModTerminus.N, "H2C2O2"),
                new StaticMod("Carboxymethyl (W)", "W", null, "H2C2O2"),
                new StaticMod("Carboxymethyl:13C(2) (C)", "C", null, "H2C'2O2"),
                new StaticMod("CarboxymethylDTT (C)", "C", null, "H10C6O4S2"),
                new StaticMod("Cation:Ag (C-term)", null, ModTerminus.C, "Ag - H"),
                new StaticMod("Cation:Ag (DE)", "D, E", null, "Ag - H"),
            };

            HiddenIsotopeMods = new StaticMod[] {
            };
// ReSharper restore RedundantExplicitArrayCreation
        }
    }
}
