//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkylineBatch.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SkylineBatch.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap add {
            get {
                object obj = ResourceManager.GetObject("add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abort.
        /// </summary>
        internal static string AlertDlg_GetDefaultButtonText_Abort {
            get {
                return ResourceManager.GetString("AlertDlg_GetDefaultButtonText_Abort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string AlertDlg_GetDefaultButtonText_Cancel {
            get {
                return ResourceManager.GetString("AlertDlg_GetDefaultButtonText_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore.
        /// </summary>
        internal static string AlertDlg_GetDefaultButtonText_Ignore {
            get {
                return ResourceManager.GetString("AlertDlg_GetDefaultButtonText_Ignore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string AlertDlg_GetDefaultButtonText_No {
            get {
                return ResourceManager.GetString("AlertDlg_GetDefaultButtonText_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string AlertDlg_GetDefaultButtonText_OK {
            get {
                return ResourceManager.GetString("AlertDlg_GetDefaultButtonText_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry.
        /// </summary>
        internal static string AlertDlg_GetDefaultButtonText_Retry {
            get {
                return ResourceManager.GetString("AlertDlg_GetDefaultButtonText_Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string AlertDlg_GetDefaultButtonText_Yes {
            get {
                return ResourceManager.GetString("AlertDlg_GetDefaultButtonText_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message truncated. Press Ctrl+C to copy entire message to the clipboard..
        /// </summary>
        internal static string AlertDlg_TruncateMessage_Message_truncated__Press_Ctrl_C_to_copy_entire_message_to_the_clipboard_ {
            get {
                return ResourceManager.GetString("AlertDlg_TruncateMessage_Message_truncated__Press_Ctrl_C_to_copy_entire_message_t" +
                        "o_the_clipboard_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysis folder directory {0} does not exist..
        /// </summary>
        internal static string Analysis_folder_does_not_exist {
            get {
                return ResourceManager.GetString("Analysis_folder_does_not_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot Delete.
        /// </summary>
        internal static string Cannot_Delete {
            get {
                return ResourceManager.GetString("Cannot_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot run configurations while they are still running..
        /// </summary>
        internal static string Cannot_run_busy_configurations {
            get {
                return ResourceManager.GetString("Cannot_run_busy_configurations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Comment {
            get {
                object obj = ResourceManager.GetObject("Comment", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \&quot;{0}\&quot; Error: {1}.
        /// </summary>
        internal static string Configuration_error_message {
            get {
                return ResourceManager.GetString("Configuration_error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Delete.
        /// </summary>
        internal static string Confirm_Delete {
            get {
                return ResourceManager.GetString("Confirm_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cound not save the following configurations:.
        /// </summary>
        internal static string Could_not_save_configurations {
            get {
                return ResourceManager.GetString("Could_not_save_configurations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data folder {0} does not exist..
        /// </summary>
        internal static string Data_folder_does_not_exist {
            get {
                return ResourceManager.GetString("Data_folder_does_not_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Delete {
            get {
                object obj = ResourceManager.GetObject("Delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap downarrow {
            get {
                object obj = ResourceManager.GetObject("downarrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Configurations Error.
        /// </summary>
        internal static string Import_configs_error_title {
            get {
                return ResourceManager.GetString("Import_configs_error_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Configurations.
        /// </summary>
        internal static string Import_configurations {
            get {
                return ResourceManager.GetString("Import_configurations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not import configurations from file {0}.
        /// </summary>
        internal static string No_configs_imported {
            get {
                return ResourceManager.GetString("No_configs_imported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following configurations already exist and were not imported:.
        /// </summary>
        internal static string Number_configs_duplicates {
            get {
                return ResourceManager.GetString("Number_configs_duplicates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of configurations imported: .
        /// </summary>
        internal static string Number_configs_imported {
            get {
                return ResourceManager.GetString("Number_configs_imported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following configurations could not be validated and were not imported:.
        /// </summary>
        internal static string Number_configs_not_valid {
            get {
                return ResourceManager.GetString("Number_configs_not_valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open R Script.
        /// </summary>
        internal static string Open_R_Script {
            get {
                return ResourceManager.GetString("Open_R_Script", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Report.
        /// </summary>
        internal static string Open_Report {
            get {
                return ResourceManager.GetString("Open_Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Skyline File.
        /// </summary>
        internal static string Open_skyline_file {
            get {
                return ResourceManager.GetString("Open_skyline_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed operation &quot;{0}&quot;: Configuration &quot;{1}&quot; already exists..
        /// </summary>
        internal static string Operation_fail_config_exists {
            get {
                return ResourceManager.GetString("Operation_fail_config_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed operation &quot;{0}&quot;: Configuration &quot;{1}&quot; does not exist..
        /// </summary>
        internal static string Operation_fail_config_nonexistant {
            get {
                return ResourceManager.GetString("Operation_fail_config_nonexistant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;{0}.
        /// </summary>
        internal static string Pneumonic_on_first_letter {
            get {
                return ResourceManager.GetString("Pneumonic_on_first_letter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process terminated: exiting..
        /// </summary>
        internal static string Process_terminated {
            get {
                return ResourceManager.GetString("Process_terminated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R|*.r.
        /// </summary>
        internal static string R_file_extension {
            get {
                return ResourceManager.GetString("R_file_extension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run Error.
        /// </summary>
        internal static string Run_error_title {
            get {
                return ResourceManager.GetString("Run_error_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Configuration Error.
        /// </summary>
        internal static string Save_configuration_error {
            get {
                return ResourceManager.GetString("Save_configuration_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save configurations....
        /// </summary>
        internal static string Save_configurations {
            get {
                return ResourceManager.GetString("Save_configurations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the skyline installation directory..
        /// </summary>
        internal static string Select_the_skyline_installation_directory {
            get {
                return ResourceManager.GetString("Select_the_skyline_installation_directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SKY|*.sky.
        /// </summary>
        internal static string Sky_file_extension {
            get {
                return ResourceManager.GetString("Sky_file_extension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SkylineBatch encountered an unexpected error. .
        /// </summary>
        internal static string SkylineBatch_encountered_an_unexpected_error {
            get {
                return ResourceManager.GetString("SkylineBatch_encountered_an_unexpected_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SKYR|*.skyr.
        /// </summary>
        internal static string Skyr_file_extension {
            get {
                return ResourceManager.GetString("Skyr_file_extension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify path to: {0}..
        /// </summary>
        internal static string Specify_path_to {
            get {
                return ResourceManager.GetString("Specify_path_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ------------------------------ Starting Configuration: {0} -------------------------------.
        /// </summary>
        internal static string Start_running_config_log_message {
            get {
                return ResourceManager.GetString("Start_running_config_log_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skyline file {0} does not exist..
        /// </summary>
        internal static string Template_file_does_not_exist {
            get {
                return ResourceManager.GetString("Template_file_does_not_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ------------------------------ {0}: {1} -------------------------------.
        /// </summary>
        internal static string Terminated_running_config_log_message {
            get {
                return ResourceManager.GetString("Terminated_running_config_log_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable To Find Skyline.
        /// </summary>
        internal static string Unable_To_Find_Skyline {
            get {
                return ResourceManager.GetString("Unable_To_Find_Skyline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap uparrow {
            get {
                object obj = ResourceManager.GetObject("uparrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML Files(*.xml)|*.xml.
        /// </summary>
        internal static string XML_file_extension {
            get {
                return ResourceManager.GetString("XML_file_extension", resourceCulture);
            }
        }
    }
}
