version: '{build}.{branch}'
skip_branch_with_pr: true
image:
- Visual Studio 2017
clone_depth: 5
init:
- git config --global core.autocrlf false
build_script:
- cmd: quickbuild.bat address-model=64 --i-agree-to-the-vendor-licenses -j2 --abbreviate-paths pwiz executables
test: off

skip_commits:
  files:
    - README.md
    - .travis.yml
    - .gitignore
    - pwiz_tools/Bumbershoot/**
    - pwiz_tools/BiblioSpec/**
    - pwiz_tools/Skyline/**
    - pwiz_tools/Topograph/**

notifications:
- provider: Webhook
  url: https://webhooks.gitter.im/e/23b73cbedd68b1381ac3
  method: POST
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: true