#!/bin/bash

pushd $(dirname $0) > /dev/null

# parse version string from pwiz/Version.cpp Version::str() implementation
version_string=$(cat pwiz/Version.cpp | grep 'Version::str()' | awk -F\" '{print $2}')
if [ $? -ne 0 ]
then
    echo "Error getting version string."
    return 1
fi

echo $version_string

