set(pwiz_INCLUDE_DIRS
    ${CMAKE_CURRENT_LIST_DIR}
    ${CMAKE_CURRENT_LIST_DIR}/libraries/boost_1_76_0
    ${CMAKE_CURRENT_LIST_DIR}/libraries/boost_aux
    )

set(pwiz_LIB_PREFIX ${CMAKE_CURRENT_LIST_DIR}/build-nt-x86)
set(pwiz_LIBS_DEBUG
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/libboost_chrono-vc143-mt-gd.lib
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/libboost_filesystem-vc143-mt-gd.lib
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/libboost_iostreams-vc143-mt-gd.lib
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/libboost_nowide-vc143-mt-gd.lib
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/libboost_program_options-vc143-mt-gd.lib
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/libboost_serialization-vc143-mt-gd.lib
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/libboost_system-vc143-mt-gd.lib
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/libboost_thread-vc143-mt-gd.lib
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/libfreetype-vc143-mt-gd-2_4.lib
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/libgd-vc143-mt-gd-2_1.lib
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/libhdf5.lib
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/libhdf5pp.lib
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/libpng.lib
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/libpwiz_analysis_chromatogram_processing.lib
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/libpwiz_analysis_common.lib
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/libpwiz_analysis_demux.lib
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/libpwiz_analysis_demuxtestdata.lib
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/libpwiz_analysis_diaumpire.lib
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/libpwiz_analysis_frequency.lib
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/libpwiz_analysis_passive.lib
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/libpwiz_analysis_passive_core.lib
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/libpwiz_analysis_peakdetect.lib
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/libpwiz_analysis_peptideid.lib
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/libpwiz_analysis_proteome_processing.lib
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/libpwiz_analysis_spectrum_processing.lib
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/libpwiz_analysis_spectrum_processing_basic.lib
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/libpwiz_analysis_version.lib
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/libpwiz_data_common.lib
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/libpwiz_data_identdata.lib
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/libpwiz_data_identdata_examples.lib
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/libpwiz_data_identdata_version.lib
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/libpwiz_data_misc.lib
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/libpwiz_data_msdata.lib
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/libpwiz_data_msdata_core.lib
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/libpwiz_data_msdata_examples.lib
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/libpwiz_data_msdata_mz5.lib
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/libpwiz_data_msdata_mzmlb.lib
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/libpwiz_data_msdata_version.lib
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/libpwiz_data_obo.lib
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/libpwiz_data_proteome.lib
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/libpwiz_data_proteome_examples.lib
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/libpwiz_data_proteome_version.lib
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/libpwiz_data_tradata.lib
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/libpwiz_data_tradata_examples.lib
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/libpwiz_data_tradata_version.lib
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/libpwiz_data_vendor_readers.lib
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/libpwiz_reader_abi.lib
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/libpwiz_reader_abi_t2d.lib
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/libpwiz_reader_agilent.lib
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/libpwiz_reader_bruker.lib
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/libpwiz_reader_shimadzu.lib
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/libpwiz_reader_thermo.lib
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/libpwiz_reader_uimf.lib
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/libpwiz_reader_unifi.lib
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/libpwiz_reader_waters.lib
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/libpwiz_tools_common.lib
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/libpwiz_utility_chemistry.lib
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/libpwiz_utility_image.lib
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/libpwiz_utility_math.lib
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/libpwiz_utility_minimxml.lib
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/libpwiz_utility_misc.lib
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/libpwiz_utility_vendor_reader_test_harness.lib
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/libpwiz_vendor_api_abi.lib
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/libpwiz_vendor_api_agilent.lib
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/libpwiz_vendor_api_thermo.lib
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/libpwiz_vendor_api_uimf.lib
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/libpwiz_vendor_api_unifi.lib
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/libpwiz_version.lib
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/libSHA1.lib
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/libsqlite3.lib
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/libsqlite3pp.lib
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/libsvm.lib
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/libzlib.lib
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/msconvert.lib
    )

set(pwiz_LIBS_RELEASE
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/libboost_chrono-vc143-mt.lib
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/libboost_filesystem-vc143-mt.lib
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/libboost_iostreams-vc143-mt.lib
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/libboost_nowide-vc143-mt.lib
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/libboost_program_options-vc143-mt.lib
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/libboost_serialization-vc143-mt.lib
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/libboost_system-vc143-mt.lib
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/libboost_thread-vc143-mt.lib
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/libfreetype-vc143-mt-2_4.lib
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/libgd-vc143-mt-2_1.lib
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/libhdf5.lib
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/libhdf5pp.lib
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/libpng.lib
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/libpwiz_analysis_chromatogram_processing.lib
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/libpwiz_analysis_common.lib
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/libpwiz_analysis_demux.lib
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/libpwiz_analysis_demuxtestdata.lib
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/libpwiz_analysis_diaumpire.lib
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/libpwiz_analysis_frequency.lib
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/libpwiz_analysis_passive.lib
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/libpwiz_analysis_passive_core.lib
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/libpwiz_analysis_peakdetect.lib
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/libpwiz_analysis_peptideid.lib
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/libpwiz_analysis_proteome_processing.lib
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/libpwiz_analysis_spectrum_processing.lib
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/libpwiz_analysis_spectrum_processing_basic.lib
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/libpwiz_analysis_version.lib
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/libpwiz_data_common.lib
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/libpwiz_data_identdata.lib
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/libpwiz_data_identdata_examples.lib
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/libpwiz_data_identdata_version.lib
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/libpwiz_data_misc.lib
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/libpwiz_data_msdata.lib
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/libpwiz_data_msdata_core.lib
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/libpwiz_data_msdata_examples.lib
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/libpwiz_data_msdata_mz5.lib
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/libpwiz_data_msdata_mzmlb.lib
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/libpwiz_data_msdata_version.lib
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/libpwiz_data_obo.lib
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/libpwiz_data_proteome.lib
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/libpwiz_data_proteome_examples.lib
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/libpwiz_data_proteome_version.lib
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/libpwiz_data_tradata.lib
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/libpwiz_data_tradata_examples.lib
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/libpwiz_data_tradata_version.lib
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/libpwiz_data_vendor_readers.lib
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/libpwiz_reader_abi.lib
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/libpwiz_reader_abi_t2d.lib
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/libpwiz_reader_agilent.lib
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/libpwiz_reader_bruker.lib
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/libpwiz_reader_shimadzu.lib
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/libpwiz_reader_thermo.lib
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/libpwiz_reader_uimf.lib
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/libpwiz_reader_unifi.lib
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/libpwiz_reader_waters.lib
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/libpwiz_tools_common.lib
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/libpwiz_utility_chemistry.lib
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/libpwiz_utility_image.lib
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/libpwiz_utility_math.lib
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/libpwiz_utility_minimxml.lib
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/libpwiz_utility_misc.lib
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/libpwiz_utility_vendor_reader_test_harness.lib
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/libpwiz_vendor_api_abi.lib
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/libpwiz_vendor_api_agilent.lib
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/libpwiz_vendor_api_thermo.lib
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/libpwiz_vendor_api_uimf.lib
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/libpwiz_vendor_api_unifi.lib
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/libpwiz_version.lib
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/libSHA1.lib
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/libsqlite3.lib
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/libsqlite3pp.lib
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/libsvm.lib
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/libzlib.lib
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/msconvert.lib
    )

set(pwiz_REDISTR_DEBUG
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/agtsampleinforw.dll
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/api-ms-win-core-console-l1-1-0.dll
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/api-ms-win-core-datetime-l1-1-0.dll
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/api-ms-win-core-debug-l1-1-0.dll
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/api-ms-win-core-errorhandling-l1-1-0.dll
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/api-ms-win-core-file-l1-1-0.dll
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/api-ms-win-core-file-l1-2-0.dll
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/api-ms-win-core-file-l2-1-0.dll
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/api-ms-win-core-handle-l1-1-0.dll
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/api-ms-win-core-heap-l1-1-0.dll
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/api-ms-win-core-interlocked-l1-1-0.dll
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/api-ms-win-core-libraryloader-l1-1-0.dll
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/api-ms-win-core-localization-l1-2-0.dll
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/api-ms-win-core-memory-l1-1-0.dll
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/api-ms-win-core-namedpipe-l1-1-0.dll
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/api-ms-win-core-processenvironment-l1-1-0.dll
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/api-ms-win-core-processthreads-l1-1-0.dll
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/api-ms-win-core-processthreads-l1-1-1.dll
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/api-ms-win-core-profile-l1-1-0.dll
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/api-ms-win-core-rtlsupport-l1-1-0.dll
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/api-ms-win-core-string-l1-1-0.dll
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/api-ms-win-core-synch-l1-1-0.dll
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/api-ms-win-core-synch-l1-2-0.dll
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/api-ms-win-core-sysinfo-l1-1-0.dll
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/api-ms-win-core-timezone-l1-1-0.dll
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/api-ms-win-core-util-l1-1-0.dll
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/api-ms-win-crt-conio-l1-1-0.dll
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/api-ms-win-crt-convert-l1-1-0.dll
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/api-ms-win-crt-environment-l1-1-0.dll
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/api-ms-win-crt-filesystem-l1-1-0.dll
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/api-ms-win-crt-heap-l1-1-0.dll
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/api-ms-win-crt-locale-l1-1-0.dll
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/api-ms-win-crt-math-l1-1-0.dll
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/api-ms-win-crt-multibyte-l1-1-0.dll
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/api-ms-win-crt-private-l1-1-0.dll
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/api-ms-win-crt-process-l1-1-0.dll
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/api-ms-win-crt-runtime-l1-1-0.dll
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/api-ms-win-crt-stdio-l1-1-0.dll
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/api-ms-win-crt-string-l1-1-0.dll
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/api-ms-win-crt-time-l1-1-0.dll
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/api-ms-win-crt-utility-l1-1-0.dll
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/BaseCommon.dll
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/BaseDataAccess.dll
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/BaseError.dll
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/BaseTof.dll
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/Clearcore2.Compression.dll
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/Clearcore2.Data.AnalystDataProvider.dll
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/Clearcore2.Data.Client.dll
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/Clearcore2.Data.CommonInterfaces.dll
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/Clearcore2.Data.dll
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/Clearcore2.Data.Wiff2.dll
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/Clearcore2.Data.WiffReader.dll
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/Clearcore2.Devices.Types.dll
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/Clearcore2.Domain.Acquisition.dll
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/Clearcore2.Infrastructure.dll
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/Clearcore2.InternalRawXYProcessing.dll
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/Clearcore2.Muni.dll
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/Clearcore2.RawXYProcessing.dll
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/Clearcore2.StructuredStorage.dll
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/Clearcore2.Utility.dll
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/Clearcore2.XmlHelpers.dll
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/IdentityModel.dll
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/Interop.DataExplorer.dll
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/MassSpecDataReader.dll
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/mfc90.dll
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/MIDAC.dll
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/msvcm90.dll
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/msvcp110.dll
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/msvcp120.dll
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/msvcp140.dll
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/msvcp90.dll
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/msvcr110.dll
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/msvcr120.dll
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/msvcr90.dll
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/Newtonsoft.Json.dll
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/OFX.Core.Contracts.dll
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/ParallelExtensionsExtras.dll
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/protobuf-net.dll
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/SCIEX.Apis.Data.v1.dll
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/Sciex.Clearcore.FMan.dll
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/Sciex.Data.SimpleTypes.dll
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/Sciex.Data.XYData.dll
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/Sciex.FMan.dll
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/Sciex.Wiff.dll
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/SQLite.Interop.dll
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/System.Data.SQLite.dll
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/System.Runtime.Caching.Generic.dll
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/ThermoFisher.CommonCore.Data.dll
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/ThermoFisher.CommonCore.RawFileReader.dll
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/ucrtbase.dll
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/UIMFLibrary.dll
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/unifi-protobuf-net.dll
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/vcomp110.dll
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/vcomp140.dll
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/vcomp90.dll
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/vcruntime140.dll
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/vcruntime140_1.dll
    )

set(pwiz_REDISTR_RELEASE
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/agtsampleinforw.dll
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/api-ms-win-core-console-l1-1-0.dll
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/api-ms-win-core-datetime-l1-1-0.dll
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/api-ms-win-core-debug-l1-1-0.dll
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/api-ms-win-core-errorhandling-l1-1-0.dll
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/api-ms-win-core-file-l1-1-0.dll
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/api-ms-win-core-file-l1-2-0.dll
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/api-ms-win-core-file-l2-1-0.dll
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/api-ms-win-core-handle-l1-1-0.dll
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/api-ms-win-core-heap-l1-1-0.dll
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/api-ms-win-core-interlocked-l1-1-0.dll
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/api-ms-win-core-libraryloader-l1-1-0.dll
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/api-ms-win-core-localization-l1-2-0.dll
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/api-ms-win-core-memory-l1-1-0.dll
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/api-ms-win-core-namedpipe-l1-1-0.dll
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/api-ms-win-core-processenvironment-l1-1-0.dll
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/api-ms-win-core-processthreads-l1-1-0.dll
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/api-ms-win-core-processthreads-l1-1-1.dll
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/api-ms-win-core-profile-l1-1-0.dll
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/api-ms-win-core-rtlsupport-l1-1-0.dll
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/api-ms-win-core-string-l1-1-0.dll
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/api-ms-win-core-synch-l1-1-0.dll
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/api-ms-win-core-synch-l1-2-0.dll
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/api-ms-win-core-sysinfo-l1-1-0.dll
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/api-ms-win-core-timezone-l1-1-0.dll
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/api-ms-win-core-util-l1-1-0.dll
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/api-ms-win-crt-conio-l1-1-0.dll
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/api-ms-win-crt-convert-l1-1-0.dll
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/api-ms-win-crt-environment-l1-1-0.dll
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/api-ms-win-crt-filesystem-l1-1-0.dll
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/api-ms-win-crt-heap-l1-1-0.dll
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/api-ms-win-crt-locale-l1-1-0.dll
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/api-ms-win-crt-math-l1-1-0.dll
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/api-ms-win-crt-multibyte-l1-1-0.dll
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/api-ms-win-crt-private-l1-1-0.dll
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/api-ms-win-crt-process-l1-1-0.dll
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/api-ms-win-crt-runtime-l1-1-0.dll
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/api-ms-win-crt-stdio-l1-1-0.dll
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/api-ms-win-crt-string-l1-1-0.dll
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/api-ms-win-crt-time-l1-1-0.dll
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/api-ms-win-crt-utility-l1-1-0.dll
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/BaseCommon.dll
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/BaseDataAccess.dll
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/BaseError.dll
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/BaseTof.dll
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/Clearcore2.Compression.dll
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/Clearcore2.Data.AnalystDataProvider.dll
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/Clearcore2.Data.Client.dll
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/Clearcore2.Data.CommonInterfaces.dll
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/Clearcore2.Data.dll
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/Clearcore2.Data.Wiff2.dll
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/Clearcore2.Data.WiffReader.dll
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/Clearcore2.Devices.Types.dll
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/Clearcore2.Domain.Acquisition.dll
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/Clearcore2.Infrastructure.dll
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/Clearcore2.InternalRawXYProcessing.dll
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/Clearcore2.Muni.dll
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/Clearcore2.RawXYProcessing.dll
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/Clearcore2.StructuredStorage.dll
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/Clearcore2.Utility.dll
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/Clearcore2.XmlHelpers.dll
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/IdentityModel.dll
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/Interop.DataExplorer.dll
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/MassSpecDataReader.dll
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/mfc90.dll
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/MIDAC.dll
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/msvcm90.dll
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/msvcp110.dll
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/msvcp120.dll
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/msvcp140.dll
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/msvcp90.dll
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/msvcr110.dll
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/msvcr120.dll
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/msvcr90.dll
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/Newtonsoft.Json.dll
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/OFX.Core.Contracts.dll
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/ParallelExtensionsExtras.dll
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/protobuf-net.dll
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/SCIEX.Apis.Data.v1.dll
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/Sciex.Clearcore.FMan.dll
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/Sciex.Data.SimpleTypes.dll
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/Sciex.Data.XYData.dll
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/Sciex.FMan.dll
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/Sciex.Wiff.dll
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/SQLite.Interop.dll
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/System.Data.SQLite.dll
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/System.Runtime.Caching.Generic.dll
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/ThermoFisher.CommonCore.Data.dll
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/ThermoFisher.CommonCore.RawFileReader.dll
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/ucrtbase.dll
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/UIMFLibrary.dll
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/unifi-protobuf-net.dll
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/vcomp110.dll
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/vcomp140.dll
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/vcomp90.dll
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/vcruntime140.dll
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/vcruntime140_1.dll
    )

if (CMAKE_BUILD_TYPE STREQUAL "Debug")
    set(pwiz_LIBS ${pwiz_LIBS_DEBUG})
    set(pwiz_REDISTR ${pwiz_REDISTR_DEBUG})
else()
    set(pwiz_LIBS ${pwiz_LIBS_RELEASE})
    set(pwiz_REDISTR ${pwiz_REDISTR_RELEASE})
endif()
