#!/bin/bash

pushd $(dirname $0) > /dev/null

packagedir=build/packages/$(get_version)

ls -lt $packagedir

echo "Ready to upload to SourceForge"
read -p "user: " user 

rsync -avP -e ssh $packagedir/* $user@frs.sourceforge.net:uploads/

