// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Build", "CA1416:This call site is reachable on all platforms. 'SystemBrushes.ControlText' is only supported on: 'windows'.", Justification = "<Pending>", Scope = "member", Target = "~M:DataGridViewAutoFilter.DataGridViewAutoFilterColumnHeaderCell.Paint(System.Drawing.Graphics,System.Drawing.Rectangle,System.Drawing.Rectangle,System.Int32,System.Windows.Forms.DataGridViewElementStates,System.Object,System.Object,System.String,System.Windows.Forms.DataGridViewCellStyle,System.Windows.Forms.DataGridViewAdvancedBorderStyle,System.Windows.Forms.DataGridViewPaintParts)")]
[assembly: SuppressMessage("Build", "CA1416:This call site is reachable on all platforms. 'Font.Height' is only supported on: 'windows'.", Justification = "<Pending>", Scope = "member", Target = "~M:DataGridViewAutoFilter.DataGridViewAutoFilterColumnHeaderCell.SetDropDownButtonBounds")]
[assembly: SuppressMessage("Build", "CA1416:This call site is reachable on all platforms. 'Graphics.MeasureString(string?, Font)' is only supported on: 'windows'.", Justification = "<Pending>", Scope = "member", Target = "~M:DataGridViewAutoFilter.DataGridViewAutoFilterColumnHeaderCell.SetDropDownListBoxBounds")]
[assembly: SuppressMessage("Build", "CA1416:This call site is reachable on all platforms. 'RegistryKey.OpenSubKey(string)' is only supported on: 'windows'.", Justification = "<Pending>", Scope = "member", Target = "~M:JWC.MruStripMenu.LoadFromRegistry")]
[assembly: SuppressMessage("Build", "CA1416:This call site is reachable on all platforms. 'Registry.CurrentUser' is only supported on: 'windows'.", Justification = "<Pending>", Scope = "member", Target = "~M:JWC.MruStripMenu.SaveToRegistry")]
[assembly: SuppressMessage("Build", "CA1416:This call site is reachable on all platforms. 'SolidBrush' is only supported on: 'windows'.", Justification = "<Pending>", Scope = "member", Target = "~M:seems.HeatmapForm.ChromatogramControl.CustomizeCurve(ZedGraph.CurveItem)")]
[assembly: SuppressMessage("Build", "CA1416:This call site is reachable on all platforms. 'Font' is only supported on: 'windows'.", Justification = "<Pending>", Scope = "member", Target = "~M:seems.Manager.chromatogramListForm_CellClick(System.Object,seems.ChromatogramListCellClickEventArgs)")]
[assembly: SuppressMessage("Build", "CA1416:This call site is reachable on all platforms. 'Font' is only supported on: 'windows'.", Justification = "<Pending>", Scope = "member", Target = "~M:seems.Manager.spectrumListForm_CellClick(System.Object,seems.SpectrumListCellClickEventArgs)")]
[assembly: SuppressMessage("Build", "CA1416:This call site is reachable on all platforms. 'DashStyle.Dot' is only supported on: 'windows'.", Justification = "<Pending>", Scope = "member", Target = "~M:seems.MassSpectrum.AddAnnotations(pwiz.MSGraph.MSGraphPane,System.Drawing.Graphics,pwiz.MSGraph.MSPointList,ZedGraph.GraphObjList)")]
[assembly: SuppressMessage("Build", "CA1416:This call site is reachable on all platforms. 'Graphics.DrawString(string?, Font, Brush, float, float)' is only supported on: 'windows'.", Justification = "<Pending>", Scope = "member", Target = "~M:seems.OpenDataSourceDialog.lookInComboBox_DrawItem(System.Object,System.Windows.Forms.DrawItemEventArgs)")]
[assembly: SuppressMessage("Build", "CA1416:This call site is reachable on all platforms. 'Graphics.MeasureString(string?, Font)' is only supported on: 'windows'.", Justification = "<Pending>", Scope = "member", Target = "~M:seems.OpenDataSourceDialog.lookInComboBox_MeasureItem(System.Object,System.Windows.Forms.MeasureItemEventArgs)")]
[assembly: SuppressMessage("Build", "CA1416:This call site is reachable on all platforms. 'DashStyle.Dot' is only supported on: 'windows'.", Justification = "<Pending>", Scope = "member", Target = "~M:seems.PeptideFragmentationAnnotation.addFragment(ZedGraph.GraphObjList,pwiz.MSGraph.MSPointList,System.String,System.Int32,System.Int32,System.Double)")]
[assembly: SuppressMessage("Build", "CA1416:This call site is reachable on all platforms. 'DashStyle.Dash' is only supported on: 'windows'.", Justification = "<Pending>", Scope = "member", Target = "~M:seems.PeptideFragmentationAnnotation.addIonSeries(ZedGraph.GraphObjList,pwiz.MSGraph.MSPointList,pwiz.CLI.proteome.Peptide,pwiz.CLI.proteome.Fragmentation,System.String,System.String)")]
[assembly: SuppressMessage("Build", "CA1416:This call site is reachable on all platforms. 'FontStyle.Bold' is only supported on: 'windows'.", Justification = "<Pending>", Scope = "member", Target = "~M:seems.PeptideFragmentationAnnotation.Update(seems.GraphItem,pwiz.MSGraph.MSPointList,ZedGraph.GraphObjList)")]
[assembly: SuppressMessage("Build", "CA1416:This call site is reachable on all platforms. 'RegistryKey.Close()' is only supported on: 'windows'.", Justification = "<Pending>", Scope = "member", Target = "~M:seems.seemsForm.#ctor")]
