package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.BuildType
import jetbrains.buildServer.configs.kotlin.buildSteps.DotnetMsBuildStep
import jetbrains.buildServer.configs.kotlin.buildSteps.DotnetVsTestStep
import jetbrains.buildServer.configs.kotlin.buildSteps.dotnetCustom
import jetbrains.buildServer.configs.kotlin.buildSteps.dotnetMsBuild
import jetbrains.buildServer.configs.kotlin.buildSteps.dotnetRestore
import jetbrains.buildServer.configs.kotlin.buildSteps.dotnetVsTest
import jetbrains.buildServer.configs.kotlin.buildSteps.exec
import jetbrains.buildServer.configs.kotlin.buildSteps.script
import jetbrains.buildServer.configs.kotlin.failureConditions.BuildFailureOnMetric
import jetbrains.buildServer.configs.kotlin.failureConditions.failOnMetricChange
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a buildType with absolute id = 'ProteoWizard_SkylineWindowsNet'
in the root project, and delete the patch script.
*/
create(DslContext.projectId, BuildType({
    templates(AbsoluteId("ProteoWizard_WindowsBase"), AbsoluteId("ProteoWizard_WindowsCoreRelease"), AbsoluteId("ProteoWizard_GitHubReportingConfig"), AbsoluteId("ProteoWizard_RemoteAccountTestParameters"))
    id = AbsoluteId("ProteoWizard_SkylineWindowsNet")
    name = "Skyline Windows .NET"

    artifactRules = """
        pwiz_tools/Skyline/TestResults/*.trx
        pwiz_tools/Skyline/bin/staging/Release/SkylineNightly.zip
        pwiz_tools/Skyline/bin/staging/Release/SkylineTester.zip
        pwiz_tools/Skyline/bin/staging/Release/BiblioSpec.zip
    """.trimIndent()

    params {
        // Environment for the inspection step below. These are declared at configuration
        // level because env.* IS a build-configuration parameter: the generic runners have
        // no per-step environment variables. param("env.X", ...) inside an exec {} block
        // compiles and is stored as a runner property, and nothing ever reads it - build
        // #285 ran the step with all three declared there and tcinspect.ps1 saw none of
        // them. The steps in this file that look like counterexamples are meta-runners
        // (RUNNER_73, RUNNER_85), where those names are the runner's declared inputs.
        //
        // BUILD_VCS_NUMBER needs no entry: TeamCity predefines it. That is how #285 posted
        // nothing for the token while still resolving the commit SHA.
        param("env.GITHUB_STATUS_TOKEN", "%GitHubAuthToken%")
        // guest=1 so the link from GitHub opens without a TeamCity login, matching what the
        // standalone inspection config has always linked to.
        param("env.INSPECTION_TARGET_URL", "https://teamcity.labkey.org/buildConfiguration/%system.teamcity.buildType.id%/%teamcity.build.id%?guest=1")
    }

    steps {
        exec {
            name = "Skyline code inspection"
            id = "Skyline_Code_Inspection"
            path = "pwsh"
            arguments = "-NoProfile -File pwiz_tools/Skyline/tcinspect.ps1"
            // tcinspect.ps1 posts its own GitHub commit status rather than handing a verdict
            // to a following step, so the check updates when the inspection finishes instead
            // of when the enclosing step ends - and it stays correct if the inspection ever
            // moves inside tcbuild.bat. It always exits 0, so it cannot fail this build.
            //
            // It publishes the context the standalone "Skyline Code Inspection" config
            // publishes, character for character, replacing that check on a PR rather than
            // adding a second one. Note there is no "teamcity - " prefix on that one, unlike
            // every other config here - verified against the GitHub status API, not inferred.
            //
            // GITHUB_STATUS_TOKEN and INSPECTION_TARGET_URL reach it from params above.
        }
        dotnetCustom {
            name = "Install dotCover"
            id = "Install_dotCover"
            enabled = false
            args = "tool install -g JetBrains.dotCover.CommandLineTools"
        }
        exec {
            id = "RUNNER_simpleRunner_139"
            path = "pwiz_tools/Skyline/tcbuild.bat"
            arguments = "--i-agree-to-the-vendor-licenses --automated --require-vendor-support"
        }
        dotnetRestore {
            name = "Restore"
            id = "dotnet_1"
            enabled = false
            projects = "pwiz-sharp/Pwiz.sln"
            args = "/p:IAgreeToVendorLicenses=true"
            sdk = "8.0"
        }
        dotnetMsBuild {
            id = "dotnet"
            enabled = false
            projects = "pwiz-sharp/Pwiz.sln"
            version = DotnetMsBuildStep.MSBuildVersion.CrossPlatform
            configuration = "Release"
            args = "/p:IAgreeToVendorLicenses=true -p:TestTfmsInParallel=false"
            sdk = "8.0"
        }
        dotnetVsTest {
            name = "Test"
            id = "Test"
            enabled = false
            assemblies = "**/bin/**Tests.dll"
            version = DotnetVsTestStep.VSTestVersion.CrossPlatform
            platform = DotnetVsTestStep.Platform.Auto
            sdk = "8.0"
            coverage = dotcover {
            }
        }
        script {
            name = "Set PWIZ_VERSION variable"
            id = "Set_PWIZ_VERSION_variable"
            enabled = false
            scriptContent = """
                REM Read version from build directory into PWIZ_VERSION
                set /p PWIZ_VERSION=<build-nt-x86\VERSION
                
                REM Replace spaces with periods
                set PWIZ_VERSION=%%PWIZ_VERSION: =.%%
                
                REM Pass the value to TeamCity
                echo ##teamcity[setParameter name='env.PWIZ_VERSION' value='%%PWIZ_VERSION%%']
            """.trimIndent()
            param("org.jfrog.artifactory.selectedDeployableServer.downloadSpecSource", "Job configuration")
            param("org.jfrog.artifactory.selectedDeployableServer.useSpecs", "false")
            param("org.jfrog.artifactory.selectedDeployableServer.uploadSpecSource", "Job configuration")
        }
        step {
            id = "RUNNER_73"
            type = "ProteoWizard_UploadArtifactMetadataToSourceForge"
            enabled = false
            executionMode = BuildStep.ExecutionMode.DEFAULT
            param("env.NUMBER_OF_CORES", "%teamcity.agent.hardware.cpuCount%")
            param("teamcity.activeBuildBranch.age.hours", "0")
            param("WINDOWS_CHECKOUT_DIR", """Z:\pwiz""")
            param("system.artifact.paths", "build-nt-x86/*.msi,build-nt-x86/*.tar.bz2,build-nt-x86/VERSION")
            param("env.PYTHON_HOME", """C:\Python38""")
            param("teamcity.activeVcsBranch.age.days", "3")
            param("WINDOWS_SKYLINE_RELEASE_CHECKOUT_DIR", """C:\skyline_release""")
        }
        step {
            name = "Send build status update for pwiz artifacts"
            id = "RUNNER_85"
            type = "ProteoWizard_SendBuildStatusToGitHub"
            executionMode = BuildStep.ExecutionMode.RUN_ON_FAILURE
            param("buildStatusUpdateTargetUrl", "https://mc-tca-01.s3.us-west-2.amazonaws.com/ProteoWizard/%system.teamcity.buildType.id%/%teamcity.build.id%/pwiz-setup-%env.PWIZ_VERSION%-x86_64.msi")
            param("buildStatusUpdateContext", "artifacts - ProteoWizard")
            param("buildStatusUpdateDescription", "Includes msconvert/SeeMS")
            param("teamcity.step.phase", "")
            param("GitHubAuthToken", "credentialsJSON:ff89fd87-e72b-4868-b752-4f2beaabe7b2")
            param("buildStatusUpdateState", "success")
        }
        stepsOrder = arrayListOf("Set_PYTHON_HOME_if_unset_by_agent", "Skyline_Code_Inspection", "Install_dotCover", "RUNNER_simpleRunner_139", "dotnet_1", "dotnet", "Test", "Set_PWIZ_VERSION_variable", "RUNNER_73", "RUNNER_85")
    }

    failureConditions {
        executionTimeoutMin = 120
        failOnMetricChange {
            id = "BUILD_EXT_539"
            metric = BuildFailureOnMetric.MetricType.TEST_COUNT
            threshold = 50
            units = BuildFailureOnMetric.MetricUnit.DEFAULT_UNIT
            comparison = BuildFailureOnMetric.MetricComparison.LESS
            compareTo = build {
                buildRule = lastSuccessful()
            }
        }
    }

    requirements {
        contains("teamcity.agent.name", "MacCoss", "RQ_59")
    }
    
    disableSettings("RQ_59")
}))

