package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.BuildType
import jetbrains.buildServer.configs.kotlin.buildSteps.dotnetCustom
import jetbrains.buildServer.configs.kotlin.buildSteps.exec
import jetbrains.buildServer.configs.kotlin.failureConditions.BuildFailureOnMetric
import jetbrains.buildServer.configs.kotlin.failureConditions.failOnMetricChange
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a buildType with absolute id = 'ProteoWizard_SkylineWindowsNetPerfTutorialTests'
in the root project, and delete the patch script.
*/
create(DslContext.projectId, BuildType({
    templates(AbsoluteId("ProteoWizard_WindowsBase"), AbsoluteId("ProteoWizard_WindowsCoreRelease"), AbsoluteId("ProteoWizard_GitHubReportingConfig"), AbsoluteId("ProteoWizard_RemoteAccountTestParameters"))
    id = AbsoluteId("ProteoWizard_SkylineWindowsNetPerfTutorialTests")
    name = "Skyline Windows .NET Perf/Tutorial Tests"

    artifactRules = "# Configure artifacts in tcbuild.bat"

    steps {
        dotnetCustom {
            name = "Install dotCover"
            id = "Install_dotCover"
            enabled = false
            args = "tool install -g JetBrains.dotCover.CommandLineTools"
        }
        exec {
            id = "RUNNER_simpleRunner_139"
            path = "pwiz_tools/Skyline/tc-perftests.bat"
            arguments = "--i-agree-to-the-vendor-licenses --automated --require-vendor-support"
        }
        step {
            id = "RUNNER_73"
            type = "ProteoWizard_UploadArtifactMetadataToSourceForge"
            enabled = false
            executionMode = BuildStep.ExecutionMode.DEFAULT
            param("env.NUMBER_OF_CORES", "%teamcity.agent.hardware.cpuCount%")
            param("teamcity.activeBuildBranch.age.hours", "0")
            param("WINDOWS_CHECKOUT_DIR", """Z:\pwiz""")
            param("system.artifact.paths", "build-nt-x86/*.msi,build-nt-x86/*.tar.bz2,build-nt-x86/VERSION")
            param("env.PYTHON_HOME", """C:\Python38""")
            param("teamcity.activeVcsBranch.age.days", "3")
            param("WINDOWS_SKYLINE_RELEASE_CHECKOUT_DIR", """C:\skyline_release""")
        }
        step {
            name = "Send build status update for pwiz artifacts"
            id = "RUNNER_85"
            type = "ProteoWizard_SendBuildStatusToGitHub"
            enabled = false
            executionMode = BuildStep.ExecutionMode.RUN_ON_FAILURE
            param("buildStatusUpdateTargetUrl", "https://mc-tca-01.s3.us-west-2.amazonaws.com/ProteoWizard/%system.teamcity.buildType.id%/%teamcity.build.id%/pwiz-setup-%env.PWIZ_VERSION%-x86_64.msi")
            param("buildStatusUpdateContext", "artifacts - ProteoWizard")
            param("buildStatusUpdateDescription", "Includes msconvert/SeeMS")
            param("teamcity.step.phase", "")
            param("GitHubAuthToken", "credentialsJSON:ff89fd87-e72b-4868-b752-4f2beaabe7b2")
            param("buildStatusUpdateState", "success")
        }
        stepsOrder = arrayListOf("Set_PYTHON_HOME_if_unset_by_agent", "Install_dotCover", "RUNNER_simpleRunner_139", "RUNNER_73", "RUNNER_85")
    }

    failureConditions {
        executionTimeoutMin = 180
        failOnMetricChange {
            id = "BUILD_EXT_539"
            metric = BuildFailureOnMetric.MetricType.TEST_COUNT
            threshold = 50
            units = BuildFailureOnMetric.MetricUnit.DEFAULT_UNIT
            comparison = BuildFailureOnMetric.MetricComparison.LESS
            compareTo = build {
                buildRule = lastSuccessful()
            }
        }
    }

    requirements {
        contains("teamcity.agent.name", "MacCoss", "RQ_59")
    }
}))

