package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.BuildType
import jetbrains.buildServer.configs.kotlin.buildSteps.ExecBuildStep
import jetbrains.buildServer.configs.kotlin.buildSteps.ScriptBuildStep
import jetbrains.buildServer.configs.kotlin.buildSteps.exec
import jetbrains.buildServer.configs.kotlin.buildSteps.script
import jetbrains.buildServer.configs.kotlin.triggers.schedule
import jetbrains.buildServer.configs.kotlin.triggers.vcs
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a buildType with absolute id = 'ProteoWizard_ProteoWizardAndSkylineDockerContainerNetWineX8664'
in the root project, and delete the patch script.
*/
create(DslContext.projectId, BuildType({
    templates(AbsoluteId("ProteoWizard_GitHubReportingConfig"))
    id = AbsoluteId("ProteoWizard_ProteoWizardAndSkylineDockerContainerNetWineX8664")
    name = "ProteoWizard and Skyline Docker container .NET (Wine x86_64)"
    description = "Builds the container from the latest binary snapshots"

    artifactRules = """
        **/*.log => logs.tar.gz
        **/*.diff => diffs.tar.gz
        pwiz-skyline-i-agree-to-the-vendor-licenses.*
        /tmp/pwiz-skyline-i-agree-to-the-vendor-licenses.*
        %system.teamcity.build.tempDir%/*pwiz-skyline-i-agree-to-the-vendor-licenses_x64*.simg
        -:**/duration.log
        -:**/AcqData
        -:**/method.log
        -:TestRunner*.log
        -:pwiz_tools/Skyline/**/*.log
    """.trimIndent()
    buildNumberPattern = "%build.counter% (%system.build.vcs.number.ProteoWizard_PwizGithubMasterWithPRs%)"

    params {
        param("env.address_model_property", "")
        param("env.architecture_property", "")
        param("env.MSPARSER_HOME", "")
        param("env.variant_property", "release")
        param("env.link_property", "")
        param("system.build.vcs.number", "%system.build.vcs.number.ProteoWizard_GithubContainer%")
    }

    vcs {
        root(AbsoluteId("ProteoWizard_GithubContainer"), "+:. => container")
        root(AbsoluteId("ProteoWizard_PwizGithubMasterWithPRs"))

        checkoutMode = CheckoutMode.ON_AGENT
        checkoutDir = "pwiz-container"
        showDependenciesChanges = true
    }

    steps {
        script {
            name = "Build container"
            id = "RUNNER_2155"
            workingDir = "container"
            scriptContent = """
                rm -f *.tar.bz2 *.zip *.exe
                mv artifacts/* .
                if ls ProteoWizard-*Setup-*.exe >/dev/null 2>&1; then
                  PB=proteowizard/wine:stable11.0-x64;  RB=proteowizard/wine:stable11.0-x64
                else
                  PB=ubuntu:20.04;  RB=proteowizard/wine-dotnet:winestaging10.6-net4.8-x64
                fi
                /usr/bin/docker system prune --all --force --volumes
                df -h
                /usr/bin/docker build --build-arg PAYLOAD_BASE=${'$'}PB --build-arg RUNTIME_BASE=${'$'}RB -t chambm/pwiz-skyline-i-agree-to-the-vendor-licenses:x64 .
            """.trimIndent()
        }
        exec {
            name = "Run ProteoWizard tests"
            id = "RUNNER_337"
            path = "scripts/container/tctest.sh"
            dockerImage = "chambm/pwiz-skyline-i-agree-to-the-vendor-licenses:x64"
            dockerImagePlatform = ExecBuildStep.ImagePlatform.Linux
            dockerRunParameters = "--rm -e WINEDEBUG=-all"
            param("script.content", """
                #!/bin/bash
                
                #set -x
                #set -v
                
                export DEBIAN_FRONTEND="noninteractive"
                apt-get -qq update
                apt-get -qq install bzip2 time
                
                declare -a arr=("ABI" "Agilent" "Bruker" "Mobilion" "Shimadzu" "Thermo" "UIMF" "Waters")
                declare -a ext=(".d" ".lcd" ".mbi" ".raw" ".wiff" ".wiff2" ".uimf")
                
                TC=##teamcity
                
                echo " ${'$'}{TC}[testSuiteStarted name='ProteoWizard msconvert']"
                
                for i in "${'$'}{arr[@]}"; do
                  pushd pwiz/data/vendor_readers/"${'$'}i"
                  if [ -e Reader_"${'$'}i"_Test.data.tar.bz2 ]; then
                    tar xkjf Reader_"${'$'}i"_Test.data.tar.bz2
                  fi
                  cd Reader_"${'$'}i"_Test.data
                  for j in "${'$'}{ext[@]}"; do
                    if ls *"${'$'}j" > /dev/null 2>&1; then
                      for k in *"${'$'}j"; do
                        TESTNAME="Convert ${'$'}k"
                        echo " ${'$'}{TC}[testStarted name='${'$'}TESTNAME' captureStandardOutput='true']"
                        fn=${'$'}(basename "${'$'}k" "${'$'}j")
                        if ! [ -e "${'$'}k/Analysis.yep" ] && [ "${'$'}k" != "diaPASEF.d" ]; then
                          if [ "${'$'}fn" == "swath.api" ]; then
                            /usr/bin/time -f '%E' -o duration.log mywine msconvert -z "${'$'}k" --noindex -o "output/${'$'}fn" --outfile "swath.api-sample-centroid.mzML" --filter "peakPicking true 1-"
                          else
                            /usr/bin/time -f '%E' -o duration.log mywine msconvert -z "${'$'}k" --noindex -o "output/${'$'}fn"
                          fi
                        fi
                        if [ -e "output/${'$'}fn/${'$'}fn.mzML" ]; then
                          mywine msdiff -p 1e-5 "${'$'}fn.mzML" "output/${'$'}fn/${'$'}fn.mzML" > "output/${'$'}fn/${'$'}fn.diff"
                        elif [ "${'$'}fn" == "swath.api.wiff2" ]; then
                          mywine msdiff "${'$'}fn-sample-centroid.mzML" "output/${'$'}fn/${'$'}fn.mzML" > "output/${'$'}fn/${'$'}fn.diff"
                        elif ( [ "${'$'}j" == ".wiff" ] || [ "${'$'}j" == ".wiff2" ] ); then
                          for mzml in output/${'$'}fn/*.mzML; do
                            refMzML=${'$'}(basename "${'$'}mzml")
                            if [ -e "${'$'}refMzML" ]; then
                              mywine msdiff "${'$'}refMzML" "${'$'}mzml" >> "output/${'$'}fn/${'$'}fn.diff"
                            elif [ -e ${'$'}(basename "${'$'}mzml" .mzML)-centroid.mzML ]; then
                              mywine msdiff ${'$'}(basename "${'$'}mzml" .mzML)-centroid.mzML "${'$'}mzml" >> "output/${'$'}fn/${'$'}fn.diff"
                            fi
                          done
                        elif ( [ "${'$'}k" == "diaPASEF.d" ] ); then
                          echo " Skipping diaPASEF test because it is not tested in non-filtered mode (diaPASEF.mzML)."
                        else
                          #cat "output/${'$'}fn/${'$'}k.log"
                          echo " ${'$'}{TC}[testFailed name='${'$'}TESTNAME' message='Expected output file |'output/${'$'}fn/${'$'}fn.mzML|' does not exist.']"
                        fi
                
                        diffFile="output/${'$'}fn/${'$'}fn.diff"
                        if [ -e "${'$'}diffFile" ]; then
                          if grep -q "0 spectra" "${'$'}diffFile" && \
                            grep -q "0 chromatograms" "${'$'}diffFile"; then
                            duration=${'$'}(<duration.log)
                            rm "output/${'$'}fn/${'$'}fn.diff"
                          else
                            #cat "output/${'$'}fn/${'$'}k.log"
                            echo " ${'$'}{TC}[testFailed name='${'$'}TESTNAME']"
                          fi
                        fi
                
                        echo " ${'$'}{TC}[testFinished name='${'$'}TESTNAME' duration='${'$'}duration']"
                      done
                    fi
                  done
                  popd
                done
                echo " ${'$'}{TC}[testSuiteFinished name='ProteoWizard msconvert']"
            """.trimIndent())
        }
        script {
            name = "Run Skyline tests"
            id = "RUNNER_334"
            scriptContent = """
                TC=##teamcity
                
                echo " ${'$'}{TC}[testSuiteStarted name='Skyline Test.dll']"
                wine TestRunner test=Test.dll skip=CodeInspection language=en loop=1 runsmallmoleculeversions=1 teamcitytestdecoration=1
                echo " ${'$'}{TC}[testSuiteFinished name='Skyline Test.dll']"
                
                echo " ${'$'}{TC}[testSuiteStarted name='Skyline TestData.dll']"
                wine TestRunner test=TestData.dll skip=TestInstallFromZip language=en loop=1 runsmallmoleculeversions=1 teamcitytestdecoration=1
                echo " ${'$'}{TC}[testSuiteFinished name='Skyline TestData.dll']"
                
                # args previously passed to docker run
                # -v %teamcity.build.checkoutDir%/pwiz_tools/Skyline:/wineprefix64/drive_c/pwiz/skyline/TestZipFiles
            """.trimIndent()
            dockerImage = "chambm/pwiz-skyline-i-agree-to-the-vendor-licenses:x64"
            param("org.jfrog.artifactory.selectedDeployableServer.downloadSpecSource", "Job configuration")
            param("org.jfrog.artifactory.selectedDeployableServer.useSpecs", "false")
            param("org.jfrog.artifactory.selectedDeployableServer.uploadSpecSource", "Job configuration")
        }
        script {
            name = "Save Docker tarball"
            id = "RUNNER_343"
            scriptContent = "/usr/bin/docker save chambm/pwiz-skyline-i-agree-to-the-vendor-licenses:x64 | pigz -c > /tmp/pwiz-skyline-i-agree-to-the-vendor-licenses.tbz2"
            param("org.jfrog.artifactory.selectedDeployableServer.useSpecs", "false")
            param("org.jfrog.artifactory.selectedDeployableServer.uploadSpecSource", "Job configuration")
            param("org.jfrog.artifactory.selectedDeployableServer.downloadSpecSource", "Job configuration")
        }
        script {
            name = "Convert Docker image to Singularity"
            id = "RUNNER_385"
            enabled = false
            scriptContent = """
                rm -f /%system.teamcity.build.tempDir%/*.simg
                docker-entrypoint.sh /docker2singularity.sh chambm/pwiz-skyline-i-agree-to-the-vendor-licenses:x64
            """.trimIndent()
            dockerImage = "singularityware/docker2singularity:v2.5"
            dockerImagePlatform = ScriptBuildStep.ImagePlatform.Linux
            dockerRunParameters = "-v /var/run/docker.sock:/var/run/docker.sock -v %system.teamcity.build.tempDir%:/output --privileged -t"
            param("org.jfrog.artifactory.selectedDeployableServer.downloadSpecSource", "Job configuration")
            param("org.jfrog.artifactory.selectedDeployableServer.useSpecs", "false")
            param("org.jfrog.artifactory.selectedDeployableServer.uploadSpecSource", "Job configuration")
        }
        step {
            id = "RUNNER_75"
            type = "ProteoWizard_UploadArtifactMetadataToSourceForge"
            executionMode = BuildStep.ExecutionMode.DEFAULT
            param("env.NUMBER_OF_CORES", "%teamcity.agent.hardware.cpuCount%")
            param("teamcity.activeBuildBranch.age.hours", "0")
            param("WINDOWS_CHECKOUT_DIR", """Z:\pwiz""")
            param("system.artifact.paths", "pwiz-skyline-i-agree-to-the-vendor-licenses.*,/tmp/pwiz-skyline-i-agree-to-the-vendor-licenses.*,%system.teamcity.build.tempDir%/*pwiz-skyline-i-agree-to-the-vendor-licenses_x64*.simg")
            param("env.PYTHON_HOME", """C:\Python38""")
            param("teamcity.activeVcsBranch.age.days", "3")
            param("WINDOWS_SKYLINE_RELEASE_CHECKOUT_DIR", """C:\skyline_release""")
        }
    }

    triggers {
        schedule {
            id = "TRIGGER_1024"
            enabled = false
            schedulingPolicy = daily {
                hour = 0
            }
            branchFilter = "-:Skyline/skyline_*"
            triggerRules = """
                +:.
                -:pwiz_tools/SeeMS/**
                -:pwiz_tools/MSConvertGUI/**
            """.trimIndent()
            triggerBuild = always()
        }
        vcs {
            id = "vcsTrigger"
            triggerRules = "+:container/Dockerfile"
            branchFilter = """
                +:*
                -:Skyline/skyline_*
            """.trimIndent()
        }
    }

    failureConditions {
        executionTimeoutMin = 60
    }

    features {
        feature {
            id = "BUILD_EXT_21"
            type = "teamcity.github.status"
            param("guthub_context", "teamcity - %system.teamcity.buildConfName%")
            param("guthub_owner", "ProteoWizard")
            param("guthub_authentication_type", "token")
            param("guthub_repo", "container")
            param("github_report_on", "on start and finish")
            param("secure:github_access_token", "credentialsJSON:f8fb99a5-f2ce-42ef-9ef4-8809c17e6b32")
        }
    }

    dependencies {
        dependency(AbsoluteId("ProteoWizard_CoreWindowsNet")) {
            snapshot {
                reuseBuilds = ReuseBuilds.ANY
                onDependencyCancel = FailureAction.CANCEL
                synchronizeRevisions = false
            }

            artifacts {
                id = "ARTIFACT_DEPENDENCY_37"
                buildRule = sameChain()
                cleanDestination = true
                artifactRules = "ProteoWizard-WithVendorSdks-Setup*.exe => container/artifacts"
            }
        }
        dependency(AbsoluteId("ProteoWizard_SkylineWindowsNet")) {
            snapshot {
                reuseBuilds = ReuseBuilds.ANY
                onDependencyCancel = FailureAction.CANCEL
                synchronizeRevisions = false
            }

            artifacts {
                id = "ARTIFACT_DEPENDENCY_2278"
                artifactRules = "SkylineTester.zip => container/artifacts"
            }
        }
    }

    requirements {
        contains("teamcity.agent.jvm.os.name", "Linux", "RQ_471")
        doesNotEqual("teamcity.agent.jvm.os.arch", "i386", "RQ_473")
        exists("docker.version", "RQ_2033")
    }

    cleanup {
        baseRule {
            history(days = 30)
            artifacts(builds = 1, days = 7, artifactPatterns = """
                *.tbz2
                *.simg
            """.trimIndent())
        }
    }
}))

