package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.BuildType
import jetbrains.buildServer.configs.kotlin.buildSteps.exec
import jetbrains.buildServer.configs.kotlin.buildSteps.script
import jetbrains.buildServer.configs.kotlin.failureConditions.BuildFailureOnMetric
import jetbrains.buildServer.configs.kotlin.failureConditions.failOnMetricChange
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a buildType with absolute id = 'ProteoWizard_CoreWindowsNet'
in the root project, and delete the patch script.
*/
create(DslContext.projectId, BuildType({
    templates(AbsoluteId("ProteoWizard_WindowsBase"), AbsoluteId("ProteoWizard_WindowsCoreRelease"), AbsoluteId("ProteoWizard_GitHubReportingConfig"), AbsoluteId("ProteoWizard_RemoteAccountTestParameters"))
    id = AbsoluteId("ProteoWizard_CoreWindowsNet")
    name = "Core Windows .NET"

    artifactRules = """
        scripts/installer/build/ProteoWizard-*.exe
        **/*.blib.observed
    """.trimIndent()

    steps {
        exec {
            id = "RUNNER_simpleRunner_139"
            path = "tcbuild.bat"
            arguments = "--i-agree-to-the-vendor-licenses --automated --require-vendor-support"
        }
        script {
            name = "Set PWIZ_VERSION variable"
            id = "Set_PWIZ_VERSION_variable"
            enabled = false
            scriptContent = """
                REM Read version from build directory into PWIZ_VERSION
                set /p PWIZ_VERSION=<build-nt-x86\VERSION
                
                REM Replace spaces with periods
                set PWIZ_VERSION=%%PWIZ_VERSION: =.%%
                
                REM Pass the value to TeamCity
                echo ##teamcity[setParameter name='env.PWIZ_VERSION' value='%%PWIZ_VERSION%%']
            """.trimIndent()
            param("org.jfrog.artifactory.selectedDeployableServer.downloadSpecSource", "Job configuration")
            param("org.jfrog.artifactory.selectedDeployableServer.useSpecs", "false")
            param("org.jfrog.artifactory.selectedDeployableServer.uploadSpecSource", "Job configuration")
        }
        step {
            id = "RUNNER_73"
            type = "ProteoWizard_UploadArtifactMetadataToSourceForge"
            enabled = false
            executionMode = BuildStep.ExecutionMode.DEFAULT
            param("env.NUMBER_OF_CORES", "%teamcity.agent.hardware.cpuCount%")
            param("teamcity.activeBuildBranch.age.hours", "0")
            param("WINDOWS_CHECKOUT_DIR", """Z:\pwiz""")
            param("system.artifact.paths", "build-nt-x86/*.msi,build-nt-x86/*.tar.bz2,build-nt-x86/VERSION")
            param("env.PYTHON_HOME", """C:\Python38""")
            param("teamcity.activeVcsBranch.age.days", "3")
            param("WINDOWS_SKYLINE_RELEASE_CHECKOUT_DIR", """C:\skyline_release""")
        }
        step {
            name = "Send build status update for pwiz artifacts"
            id = "RUNNER_85"
            type = "ProteoWizard_SendBuildStatusToGitHub"
            executionMode = BuildStep.ExecutionMode.RUN_ON_FAILURE
            param("buildStatusUpdateTargetUrl", "https://mc-tca-01.s3.us-west-2.amazonaws.com/ProteoWizard/%system.teamcity.buildType.id%/%teamcity.build.id%/pwiz-setup-%env.PWIZ_VERSION%-x86_64.msi")
            param("buildStatusUpdateContext", "artifacts - ProteoWizard")
            param("buildStatusUpdateDescription", "Includes msconvert/SeeMS")
            param("teamcity.step.phase", "")
            param("GitHubAuthToken", "credentialsJSON:ff89fd87-e72b-4868-b752-4f2beaabe7b2")
            param("buildStatusUpdateState", "success")
        }
        stepsOrder = arrayListOf("Set_PYTHON_HOME_if_unset_by_agent", "Install_dotCover", "RUNNER_simpleRunner_139", "dotnet_1", "dotnet", "Test", "Set_PWIZ_VERSION_variable", "RUNNER_73", "RUNNER_85")
    }

    failureConditions {
        failOnMetricChange {
            id = "BUILD_EXT_539"
            metric = BuildFailureOnMetric.MetricType.TEST_COUNT
            threshold = 50
            units = BuildFailureOnMetric.MetricUnit.DEFAULT_UNIT
            comparison = BuildFailureOnMetric.MetricComparison.LESS
            compareTo = build {
                buildRule = lastSuccessful()
            }
        }
    }

    requirements {
        contains("teamcity.agent.name", "MacCoss", "RQ_59")
    }
    
    disableSettings("RQ_59")
}))

