#!/bin/bash

pwiz_root=$(dirname $0)/../..
pushd $pwiz_root > /dev/null

tag=$(scripts/release/get_version)
bindir=build
packagedir=build/packages/$tag

echo "tag: $tag"
echo "bindir: $bindir"
echo "packagedir: $packagedir"

read -p "<enter> to continue..."

rm -rf $packagedir
mkdir -p $packagedir

package_windows=pwiz-$tag-tools-windows-i386.zip
package_linux=pwiz-$tag-tools-linux-i386.zip
package_osx=pwiz-$tag-tools-osx-i386.zip
package_src=pwiz-$tag-src.tgz

echo "Creating $package_windows."
zip -j $packagedir/$package_windows $bindir/msvc-release/*
echo "Creating $package_linux."
zip -j $packagedir/$package_linux $bindir/gcc-release/*
echo "Creating $package_osx."
zip -j $packagedir/$package_osx $bindir/darwin-release/*

echo "Creating $package_src."
tempdir=pwiz_$tag
echo "staging source..."
svn export . $packagedir/$tempdir
pushd $packagedir
tar czvf $package_src $tempdir
rm -rf $tempdir
popd

echo
echo $packagedir
ls -lt $packagedir

