#!/bin/bash

pwiz_root=$(dirname $0)/../..
pushd $pwiz_root > /dev/null

# parse version string from pwiz/Version.cpp Version::str() implementation
#version_string=$(cat pwiz/Version.cpp | grep 'Version::str()' | awk -F\" '{print $2}')
#if [ $? -ne 0 ]
#then
#    echo "Error getting version string."
#    return 1
#fi

# hack -- do this right!
version_string=1.5.0

echo $version_string

