//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pwiz.Skyline.Model.DocSettings.AbsoluteQuantification {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class QuantificationStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal QuantificationStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("pwiz.Skyline.Model.DocSettings.AbsoluteQuantification.QuantificationStrings", typeof(QuantificationStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyte Concentration.
        /// </summary>
        public static string Analyte_Concentration {
            get {
                return ResourceManager.GetString("Analyte Concentration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area.
        /// </summary>
        public static string Area {
            get {
                return ResourceManager.GetString("Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculated Concentration.
        /// </summary>
        public static string Calculated_Concentration {
            get {
                return ResourceManager.GetString("Calculated_Concentration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calibration Curve.
        /// </summary>
        public static string Calibration_Curve {
            get {
                return ResourceManager.GetString("Calibration_Curve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error:.
        /// </summary>
        public static string CalibrationCurve_ToString_Error__ {
            get {
                return ResourceManager.GetString("CalibrationCurve_ToString_Error__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intercept: {0}.
        /// </summary>
        public static string CalibrationCurve_ToString_Intercept___0_ {
            get {
                return ResourceManager.GetString("CalibrationCurve_ToString_Intercept___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slope: {0}.
        /// </summary>
        public static string CalibrationCurve_ToString_Slope___0_ {
            get {
                return ResourceManager.GetString("CalibrationCurve_ToString_Slope___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slope: {0} Intercept: {1}.
        /// </summary>
        public static string CalibrationCurve_ToString_Slope___0__Intercept___1_ {
            get {
                return ResourceManager.GetString("CalibrationCurve_ToString_Slope___0__Intercept___1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turning Point: {0}.
        /// </summary>
        public static string CalibrationCurve_ToString_Turning_Point___0_ {
            get {
                return ResourceManager.GetString("CalibrationCurve_ToString_Turning_Point___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to y = {0} x^2 + {1} x + {2}.
        /// </summary>
        public static string CalibrationCurve_ToString_y_x_2_x_c {
            get {
                return ResourceManager.GetString("CalibrationCurve_ToString_y_x_2_x_c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}:{1} Concentration Ratio.
        /// </summary>
        public static string CalibrationCurveFitter_ConcentrationRatioText__0___1__Concentration_Ratio {
            get {
                return ResourceManager.GetString("CalibrationCurveFitter_ConcentrationRatioText__0___1__Concentration_Ratio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concentration Ratio to {0}.
        /// </summary>
        public static string CalibrationCurveFitter_ConcentrationRatioText_Concentration_Ratio_to__0_ {
            get {
                return ResourceManager.GetString("CalibrationCurveFitter_ConcentrationRatioText_Concentration_Ratio_to__0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All of the external standards are missing one or more peaks..
        /// </summary>
        public static string CalibrationCurveFitter_GetCalibrationCurve_All_of_the_external_standards_are_missing_one_or_more_peaks_ {
            get {
                return ResourceManager.GetString("CalibrationCurveFitter_GetCalibrationCurve_All_of_the_external_standards_are_miss" +
                        "ing_one_or_more_peaks_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The external standards and the target replicate have no peaks in common..
        /// </summary>
        public static string CalibrationCurveFitter_GetCalibrationCurve_The_external_standards_and_the_target_replicate_have_no_peaks_in_common_ {
            get {
                return ResourceManager.GetString("CalibrationCurveFitter_GetCalibrationCurve_The_external_standards_and_the_target_" +
                        "replicate_have_no_peaks_in_common_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more transitions are missing or truncated..
        /// </summary>
        public static string CalibrationCurveFitter_GetQuantificationResult_One_or_more_transitions_are_missing_or_truncated_ {
            get {
                return ResourceManager.GetString("CalibrationCurveFitter_GetQuantificationResult_One_or_more_transitions_are_missin" +
                        "g_or_truncated_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concentration from ratio to {0}.
        /// </summary>
        public static string CalibrationCurveFitter_GetXAxisTitle_Concentration_from_ratio_to_0_ {
            get {
                return ResourceManager.GetString("CalibrationCurveFitter_GetXAxisTitle_Concentration_from_ratio_to_0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ratio to {0}.
        /// </summary>
        public static string CalibrationCurveFitter_GetXAxisTitle_Ratio_to__0_ {
            get {
                return ResourceManager.GetString("CalibrationCurveFitter_GetXAxisTitle_Ratio_to__0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normalized Peak Area.
        /// </summary>
        public static string CalibrationCurveFitter_GetYAxisTitle_Normalized_Peak_Area {
            get {
                return ResourceManager.GetString("CalibrationCurveFitter_GetYAxisTitle_Normalized_Peak_Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peak Area.
        /// </summary>
        public static string CalibrationCurveFitter_GetYAxisTitle_Peak_Area {
            get {
                return ResourceManager.GetString("CalibrationCurveFitter_GetYAxisTitle_Peak_Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peak Area Ratio.
        /// </summary>
        public static string CalibrationCurveFitter_GetYAxisTitle_Peak_Area_Ratio {
            get {
                return ResourceManager.GetString("CalibrationCurveFitter_GetYAxisTitle_Peak_Area_Ratio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}:{1} Peak Area Ratio.
        /// </summary>
        public static string CalibrationCurveFitter_PeakAreaRatioText__0___1__Peak_Area_Ratio {
            get {
                return ResourceManager.GetString("CalibrationCurveFitter_PeakAreaRatioText__0___1__Peak_Area_Ratio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peak Area Ratio to {0}.
        /// </summary>
        public static string CalibrationCurveFitter_PeakAreaRatioText_Peak_Area_Ratio_to__0_ {
            get {
                return ResourceManager.GetString("CalibrationCurveFitter_PeakAreaRatioText_Peak_Area_Ratio_to__0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R-Squared = .
        /// </summary>
        public static string CalibrationForm_DisplayCalibrationCurve_ {
            get {
                return ResourceManager.GetString("CalibrationForm_DisplayCalibrationCurve_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results available.
        /// </summary>
        public static string CalibrationForm_DisplayCalibrationCurve_No_results_available {
            get {
                return ResourceManager.GetString("CalibrationForm_DisplayCalibrationCurve_No_results_available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ({1}).
        /// </summary>
        public static string CalibrationForm_DisplayCalibrationCurve_QualifiedSampleType {
            get {
                return ResourceManager.GetString("CalibrationForm_DisplayCalibrationCurve_QualifiedSampleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a peptide to see its calibration curve.
        /// </summary>
        public static string CalibrationForm_DisplayCalibrationCurve_Select_a_peptide_to_see_its_calibration_curve {
            get {
                return ResourceManager.GetString("CalibrationForm_DisplayCalibrationCurve_Select_a_peptide_to_see_its_calibration_c" +
                        "urve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected peptide is no longer part of the Skyline document..
        /// </summary>
        public static string CalibrationForm_DisplayCalibrationCurve_The_selected_peptide_is_no_longer_part_of_the_Skyline_document_ {
            get {
                return ResourceManager.GetString("CalibrationForm_DisplayCalibrationCurve_The_selected_peptide_is_no_longer_part_of" +
                        "_the_Skyline_document_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected replicate has missing or truncated transitions.
        /// </summary>
        public static string CalibrationForm_DisplayCalibrationCurve_The_selected_replicate_has_missing_or_truncated_transitions {
            get {
                return ResourceManager.GetString("CalibrationForm_DisplayCalibrationCurve_The_selected_replicate_has_missing_or_tru" +
                        "ncated_transitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected replicate has no transitions that can be quantified..
        /// </summary>
        public static string CalibrationForm_DisplayCalibrationCurve_The_selected_replicate_has_no_transitions_that_can_be_quantified_ {
            get {
                return ResourceManager.GetString("CalibrationForm_DisplayCalibrationCurve_The_selected_replicate_has_no_transitions" +
                        "_that_can_be_quantified_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To convert peak area ratios to concentrations, specify the internal standard concentration for {0}..
        /// </summary>
        public static string CalibrationForm_DisplayCalibrationCurve_To_convert_peak_area_ratios_to_concentrations__specify_the_internal_standard_concentration_for__0__ {
            get {
                return ResourceManager.GetString("CalibrationForm_DisplayCalibrationCurve_To_convert_peak_area_ratios_to_concentrat" +
                        "ions__specify_the_internal_standard_concentration_for__0__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To fit a calibration curve, set the Sample Type of some replicates to Standard, and specify their concentration..
        /// </summary>
        public static string CalibrationForm_DisplayCalibrationCurve_To_fit_a_calibration_curve__set_the_Sample_Type_of_some_replicates_to_Standard__and_specify_their_concentration_ {
            get {
                return ResourceManager.GetString("CalibrationForm_DisplayCalibrationCurve_To_fit_a_calibration_curve__set_the_Sampl" +
                        "e_Type_of_some_replicates_to_Standard__and_specify_their_concentration_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the Quantification tab on the Peptide Settings dialog to control the conversion of peak areas to concentrations..
        /// </summary>
        public static string CalibrationForm_DisplayCalibrationCurve_Use_the_Quantification_tab_on_the_Peptide_Settings_dialog_to_control_the_conversion_of_peak_areas_to_concentrations_ {
            get {
                return ResourceManager.GetString("CalibrationForm_DisplayCalibrationCurve_Use_the_Quantification_tab_on_the_Peptide" +
                        "_Settings_dialog_to_control_the_conversion_of_peak_areas_to_concentrations_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (All Replicates).
        /// </summary>
        public static string CalibrationForm_GetFormTitle__All_Replicates_ {
            get {
                return ResourceManager.GetString("CalibrationForm_GetFormTitle__All_Replicates_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Batch: {0}).
        /// </summary>
        public static string CalibrationForm_GetFormTitle__Batch___0__ {
            get {
                return ResourceManager.GetString("CalibrationForm_GetFormTitle__Batch___0__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Replicate: {0}).
        /// </summary>
        public static string CalibrationForm_GetFormTitle__Replicate___0__ {
            get {
                return ResourceManager.GetString("CalibrationForm_GetFormTitle__Replicate___0__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclude Standard.
        /// </summary>
        public static string CalibrationForm_MakeExcludeStandardMenuItem_Exclude_Standard {
            get {
                return ResourceManager.GetString("CalibrationForm_MakeExcludeStandardMenuItem_Exclude_Standard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include Standard.
        /// </summary>
        public static string CalibrationForm_MakeExcludeStandardMenuItem_Include_Standard {
            get {
                return ResourceManager.GetString("CalibrationForm_MakeExcludeStandardMenuItem_Include_Standard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bootstrap Curve.
        /// </summary>
        public static string CalibrationGraphControl_DoUpdate_Bootstrap_Curve {
            get {
                return ResourceManager.GetString("CalibrationGraphControl_DoUpdate_Bootstrap_Curve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit of Detection.
        /// </summary>
        public static string CalibrationGraphControl_DoUpdate_Limit_of_Detection {
            get {
                return ResourceManager.GetString("CalibrationGraphControl_DoUpdate_Limit_of_Detection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lower Limit of Quantification.
        /// </summary>
        public static string CalibrationGraphControl_DoUpdate_Lower_Limit_of_Quantification {
            get {
                return ResourceManager.GetString("CalibrationGraphControl_DoUpdate_Lower_Limit_of_Quantification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concentration Ratio.
        /// </summary>
        public static string Concentration_Ratio {
            get {
                return ResourceManager.GetString("Concentration_Ratio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOD: .
        /// </summary>
        public static string FiguresOfMerit_ToString_LOD__ {
            get {
                return ResourceManager.GetString("FiguresOfMerit_ToString_LOD__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOQ: .
        /// </summary>
        public static string FiguresOfMerit_ToString_LOQ__ {
            get {
                return ResourceManager.GetString("FiguresOfMerit_ToString_LOQ__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blank plus 2 * SD.
        /// </summary>
        public static string LodCalculation_BLANK_PLUS_2SD_Blank_plus_2___SD {
            get {
                return ResourceManager.GetString("LodCalculation_BLANK_PLUS_2SD_Blank_plus_2___SD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blank plus 3 * SD.
        /// </summary>
        public static string LodCalculation_BLANK_PLUS_3SD_Blank_plus_3___SD {
            get {
                return ResourceManager.GetString("LodCalculation_BLANK_PLUS_3SD_Blank_plus_3___SD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string LodCalculation_NONE_None {
            get {
                return ResourceManager.GetString("LodCalculation_NONE_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilinear turning point (legacy).
        /// </summary>
        public static string LodCalculation_TURNING_POINT_Bilinear_turning_point_legacy {
            get {
                return ResourceManager.GetString("LodCalculation_TURNING_POINT_Bilinear_turning_point_legacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilinear turning point.
        /// </summary>
        public static string LodCalculation_TURNING_POINT_STDERR_Bilinear_turning_point {
            get {
                return ResourceManager.GetString("LodCalculation_TURNING_POINT_STDERR_Bilinear_turning_point", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string MsLevelOption_ALL_All {
            get {
                return ResourceManager.GetString("MsLevelOption_ALL_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string MsLevelOption_DEFAULT_Default {
            get {
                return ResourceManager.GetString("MsLevelOption_DEFAULT_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normalized Intensity.
        /// </summary>
        public static string Normalized_Intensity {
            get {
                return ResourceManager.GetString("Normalized_Intensity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calibration Curve.
        /// </summary>
        public static string NormalizeOption_CALIBRATED_Calibration_Curve {
            get {
                return ResourceManager.GetString("NormalizeOption_CALIBRATED_Calibration_Curve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Normalization Method.
        /// </summary>
        public static string NormalizeOption_DEFAULT_Default_Normalization_Method {
            get {
                return ResourceManager.GetString("NormalizeOption_DEFAULT_Default_Normalization_Method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum.
        /// </summary>
        public static string NormalizeOption_MAXIMUM_Maximum {
            get {
                return ResourceManager.GetString("NormalizeOption_MAXIMUM_Maximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string NormalizeOption_TOTAL_Total {
            get {
                return ResourceManager.GetString("NormalizeOption_TOTAL_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optimize transitions.
        /// </summary>
        public static string OptimizeDocumentTransitionsForm_Apply_Optimize_transitions {
            get {
                return ResourceManager.GetString("OptimizeDocumentTransitionsForm_Apply_Optimize_transitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normalized Area: {0}.
        /// </summary>
        public static string QuantificationResult_ToString_Normalized_Area___0_ {
            get {
                return ResourceManager.GetString("QuantificationResult_ToString_Normalized_Area___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOD: {0} LLOQ: {1}.
        /// </summary>
        public static string QuantLimit_ToString_LOD___0__LLOQ___1_ {
            get {
                return ResourceManager.GetString("QuantLimit_ToString_LOD___0__LLOQ___1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Ratio To {1}.
        /// </summary>
        public static string RatioToLabel_GetAxisTitle__0__Ratio_To__1_ {
            get {
                return ResourceManager.GetString("RatioToLabel_GetAxisTitle__0__Ratio_To__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surrogate {0}.
        /// </summary>
        public static string RatioToSurrogate_NormalizeToCaption_Surrogate__0_ {
            get {
                return ResourceManager.GetString("RatioToSurrogate_NormalizeToCaption_Surrogate__0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surrogate {0} ({1}).
        /// </summary>
        public static string RatioToSurrogate_NormalizeToCaption_Surrogate__0____1__ {
            get {
                return ResourceManager.GetString("RatioToSurrogate_NormalizeToCaption_Surrogate__0____1__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilinear.
        /// </summary>
        public static string RegressionFit_BILINEAR_Bilinear {
            get {
                return ResourceManager.GetString("RegressionFit_BILINEAR_Bilinear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linear.
        /// </summary>
        public static string RegressionFit_LINEAR_Linear {
            get {
                return ResourceManager.GetString("RegressionFit_LINEAR_Linear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linear through zero.
        /// </summary>
        public static string RegressionFit_LINEAR_THROUGH_ZERO_Linear_through_zero {
            get {
                return ResourceManager.GetString("RegressionFit_LINEAR_THROUGH_ZERO_Linear_through_zero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string RegressionFit_NONE_None {
            get {
                return ResourceManager.GetString("RegressionFit_NONE_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quadratic.
        /// </summary>
        public static string RegressionFit_QUADRATIC_Quadratic {
            get {
                return ResourceManager.GetString("RegressionFit_QUADRATIC_Quadratic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string RegressionWeighting_NONE {
            get {
                return ResourceManager.GetString("RegressionWeighting_NONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 / x.
        /// </summary>
        public static string RegressionWeighting_ONE_OVER_X {
            get {
                return ResourceManager.GetString("RegressionWeighting_ONE_OVER_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 / (x * x).
        /// </summary>
        public static string RegressionWeighting_ONE_OVER_X_SQUARED {
            get {
                return ResourceManager.GetString("RegressionWeighting_ONE_OVER_X_SQUARED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blank.
        /// </summary>
        public static string SampleType_BLANK_Blank {
            get {
                return ResourceManager.GetString("SampleType_BLANK_Blank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double Blank.
        /// </summary>
        public static string SampleType_DOUBLE_BLANK_Double_Blank {
            get {
                return ResourceManager.GetString("SampleType_DOUBLE_BLANK_Double_Blank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality Control.
        /// </summary>
        public static string SampleType_QC_Quality_Control {
            get {
                return ResourceManager.GetString("SampleType_QC_Quality_Control", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solvent.
        /// </summary>
        public static string SampleType_SOLVENT_Solvent {
            get {
                return ResourceManager.GetString("SampleType_SOLVENT_Solvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard.
        /// </summary>
        public static string SampleType_STANDARD_Standard {
            get {
                return ResourceManager.GetString("SampleType_STANDARD_Standard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string SampleType_UNKNOWN_Unknown {
            get {
                return ResourceManager.GetString("SampleType_UNKNOWN_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default ({0}).
        /// </summary>
        public static string SkylineWindow_MakeNormalizeToMenuItem_Default___0__ {
            get {
                return ResourceManager.GetString("SkylineWindow_MakeNormalizeToMenuItem_Default___0__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equal.
        /// </summary>
        public static string ValueStatus_EQUAL_Equal {
            get {
                return ResourceManager.GetString("ValueStatus_EQUAL_Equal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail.
        /// </summary>
        public static string ValueStatus_FAIL_Fail {
            get {
                return ResourceManager.GetString("ValueStatus_FAIL_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        public static string ValueStatus_HIGH_High {
            get {
                return ResourceManager.GetString("ValueStatus_HIGH_High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        public static string ValueStatus_LOW_Low {
            get {
                return ResourceManager.GetString("ValueStatus_LOW_Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pass.
        /// </summary>
        public static string ValueStatus_PASS_Pass {
            get {
                return ResourceManager.GetString("ValueStatus_PASS_Pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Present.
        /// </summary>
        public static string ValueStatus_PRESENT_Present {
            get {
                return ResourceManager.GetString("ValueStatus_PRESENT_Present", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undefined.
        /// </summary>
        public static string ValueStatus_UNDEFINED_Undefined {
            get {
                return ResourceManager.GetString("ValueStatus_UNDEFINED_Undefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weighting.
        /// </summary>
        public static string Weighting {
            get {
                return ResourceManager.GetString("Weighting", resourceCulture);
            }
        }
    }
}
