#!/bin/bash

if [ $# -ne 3 ]
then
    echo Usage: run_msconvert bindir datadir outdir
    exit 1
fi

bindir=$1
datadir=$2
outdir=$3

echo bindir: $bindir
echo datadir: $datadir
echo outdir: $outdir
read -p "<Enter> to continue..." dummy

msconvert_exe=$bindir/msconvert

if uname | grep -iq cygwin
then
    msconvert_exe+=.exe
fi

if [ ! -f $msconvert_exe ]
then
    echo $msconvert_exe not found.
    exit 1
fi

mkdir -p $outdir
log=$outdir/log

outdir_base=$outdir/$(basename $datadir)

#
# run msconvert on all files in datadir, in a separate output dir for each command line variant
#

$msconvert_exe $datadir/* -o $outdir_base.default | tee -a $log
$msconvert_exe $datadir/* -o $outdir_base.precursor --precursorRecalculation | tee -a $log
$msconvert_exe $datadir/* -o $outdir_base.zlib --zlib | tee -a $log
$msconvert_exe $datadir/* -o $outdir_base.mzxml --mzXML| tee -a $log

