//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pwiz.Skyline.Model.Koina.Models {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ModelsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ModelsResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("pwiz.Skyline.Model.Koina.Models.ModelsResources", typeof(ModelsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting Koina spectra to BiblioSpec library.
        /// </summary>
        public static string KoinaHelpers_ExportKoinaSpectraToBlib_Exporting_Koina_spectra_to_BiblioSpec_library {
            get {
                return ResourceManager.GetString("KoinaHelpers_ExportKoinaSpectraToBlib_Exporting_Koina_spectra_to_BiblioSpec_li" +
                        "brary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to failed to write Koina output to blib.
        /// </summary>
        public static string KoinaHelpers_ExportKoinaSpectraToBlib_failed_to_write_Koina_output_to_blib {
            get {
                return ResourceManager.GetString("KoinaHelpers_ExportKoinaSpectraToBlib_failed_to_write_Koina_output_to_blib", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading Koina CSV input.
        /// </summary>
        public static string KoinaHelpers_PredictBatchesFromKoinaCsv_Reading_Koina_CSV_input {
            get {
                return ResourceManager.GetString("KoinaHelpers_PredictBatchesFromKoinaCsv_Reading_Koina_CSV_input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The charge {0} is not supported by Koina. The maximum supported charge is {1}..
        /// </summary>
        public static string KoinaIntensityModel_CreateKoinaInputRow_UnsupportedCharge {
            get {
                return ResourceManager.GetString("KoinaIntensityModel_CreateKoinaInputRow_UnsupportedCharge", resourceCulture);
            }
        }
    }
}
