//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pwiz.Skyline.EditUI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EditUIResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EditUIResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("pwiz.Skyline.EditUI.EditUIResources", typeof(EditUIResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comparing Imported Files.
        /// </summary>
        public static string AddPeakCompareDlg_OkDialog_Comparing_Imported_Files {
            get {
                return ResourceManager.GetString("AddPeakCompareDlg_OkDialog_Comparing_Imported_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comparing Models.
        /// </summary>
        public static string AddPeakCompareDlg_OkDialog_Comparing_Models {
            get {
                return ResourceManager.GetString("AddPeakCompareDlg_OkDialog_Comparing_Models", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document has no eligible chromatograms for analysis.  Valid chromatograms must not be decoys or iRT standards..
        /// </summary>
        public static string AddPeakCompareDlg_OkDialog_Document_has_no_eligible_chromatograms_for_analysis___Valid_chromatograms_must_not_be_decoys_or_iRT_standards_ {
            get {
                return ResourceManager.GetString("AddPeakCompareDlg_OkDialog_Document_has_no_eligible_chromatograms_for_analysis___" +
                        "Valid_chromatograms_must_not_be_decoys_or_iRT_standards_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error comparing model peak boundaries: {0}.
        /// </summary>
        public static string AddPeakCompareDlg_OkDialog_Error_comparing_model_peak_boundaries___0_ {
            get {
                return ResourceManager.GetString("AddPeakCompareDlg_OkDialog_Error_comparing_model_peak_boundaries___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string AlignItem_ToString_None {
            get {
                return ResourceManager.GetString("AlignItem_ToString_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retention time calculator....
        /// </summary>
        public static string AlignItem_ToString_Retention_time_calculator___ {
            get {
                return ResourceManager.GetString("AlignItem_ToString_Retention_time_calculator___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retention time calculator ({0}).
        /// </summary>
        public static string AlignItem_ToString_Retention_time_calculator___0__ {
            get {
                return ResourceManager.GetString("AlignItem_ToString_Retention_time_calculator___0__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared Peptides.
        /// </summary>
        public static string AssociateProteinsDlg_CellValueNeeded_Shared_Peptides {
            get {
                return ResourceManager.GetString("AssociateProteinsDlg_CellValueNeeded_Shared_Peptides", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find &amp;minimal gene group list that explains all peptides.
        /// </summary>
        public static string AssociateProteinsDlg_Find_minimal_gene_group_list_that_explains_all_peptides {
            get {
                return ResourceManager.GetString("AssociateProteinsDlg_Find_minimal_gene_group_list_that_explains_all_peptides", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find &amp;minimal protein group list that explains all peptides.
        /// </summary>
        public static string AssociateProteinsDlg_Find_minimal_protein_group_list_that_explains_all_peptides {
            get {
                return ResourceManager.GetString("AssociateProteinsDlg_Find_minimal_protein_group_list_that_explains_all_peptides", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No matches were found using the imported fasta file..
        /// </summary>
        public static string AssociateProteinsDlg_FindProteinMatchesWithFasta_No_matches_were_found_using_the_imported_fasta_file_ {
            get {
                return ResourceManager.GetString("AssociateProteinsDlg_FindProteinMatchesWithFasta_No_matches_were_found_using_the_" +
                        "imported_fasta_file_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mi&amp;n peptides per gene.
        /// </summary>
        public static string AssociateProteinsDlg_Min_peptides_per_gene {
            get {
                return ResourceManager.GetString("AssociateProteinsDlg_Min_peptides_per_gene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mi&amp;n peptides per protein group.
        /// </summary>
        public static string AssociateProteinsDlg_Min_peptides_per_protein_group {
            get {
                return ResourceManager.GetString("AssociateProteinsDlg_Min_peptides_per_protein_group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existing protein associations will be discarded..
        /// </summary>
        public static string AssociateProteinsDlg_OnShown_Existing_protein_associations_will_be_discarded_ {
            get {
                return ResourceManager.GetString("AssociateProteinsDlg_OnShown_Existing_protein_associations_will_be_discarded_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organize all document peptides into associated proteins or protein groups..
        /// </summary>
        public static string AssociateProteinsDlg_OnShown_Organize_all_document_peptides_into_associated_proteins_or_protein_groups {
            get {
                return ResourceManager.GetString("AssociateProteinsDlg_OnShown_Organize_all_document_peptides_into_associated_prote" +
                        "ins_or_protein_groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Remove subset genes.
        /// </summary>
        public static string AssociateProteinsDlg_Remove_subset_genes {
            get {
                return ResourceManager.GetString("AssociateProteinsDlg_Remove_subset_genes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Remove subset protein groups.
        /// </summary>
        public static string AssociateProteinsDlg_Remove_subset_protein_groups {
            get {
                return ResourceManager.GetString("AssociateProteinsDlg_Remove_subset_protein_groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No matches were found using the background proteome..
        /// </summary>
        public static string AssociateProteinsDlg_UseBackgroundProteome_No_matches_were_found_using_the_background_proteome_ {
            get {
                return ResourceManager.GetString("AssociateProteinsDlg_UseBackgroundProteome_No_matches_were_found_using_the_backgr" +
                        "ound_proteome_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes.
        /// </summary>
        public static string ChromChartPropertyDlg_cbRelative_CheckedChanged_minutes {
            get {
                return ResourceManager.GetString("ChromChartPropertyDlg_cbRelative_CheckedChanged_minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to widths.
        /// </summary>
        public static string ChromChartPropertyDlg_cbRelative_CheckedChanged_widths {
            get {
                return ResourceManager.GetString("ChromChartPropertyDlg_cbRelative_CheckedChanged_widths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Model or File:.
        /// </summary>
        public static string ComparePeakBoundariesList_Label__Model_or_File_ {
            get {
                return ResourceManager.GetString("ComparePeakBoundariesList_Label__Model_or_File_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Peak Boundary Comparisons.
        /// </summary>
        public static string ComparePeakBoundariesList_Title_Edit_Peak_Boundary_Comparisons {
            get {
                return ResourceManager.GetString("ComparePeakBoundariesList_Title_Edit_Peak_Boundary_Comparisons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observed FPR:.
        /// </summary>
        public static string ComparePeakPickingDlg_checkObserved_CheckedChanged_Observed_FPR_ {
            get {
                return ResourceManager.GetString("ComparePeakPickingDlg_checkObserved_CheckedChanged_Observed_FPR_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Q value cutoff:.
        /// </summary>
        public static string ComparePeakPickingDlg_checkObserved_CheckedChanged_Q_value_cutoff_ {
            get {
                return ResourceManager.GetString("ComparePeakPickingDlg_checkObserved_CheckedChanged_Q_value_cutoff_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find the peptide {0} with charge state {1}.
        /// </summary>
        public static string ComparePeakPickingDlg_ClickGridViewItem_Unable_to_find_the_peptide__0__with_charge_state__1_ {
            get {
                return ResourceManager.GetString("ComparePeakPickingDlg_ClickGridViewItem_Unable_to_find_the_peptide__0__with_charg" +
                        "e_state__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fraction of Peak Groups.
        /// </summary>
        public static string ComparePeakPickingDlg_ComparePeakPickingDlg_Fraction_of_Peak_Groups {
            get {
                return ResourceManager.GetString("ComparePeakPickingDlg_ComparePeakPickingDlg_Fraction_of_Peak_Groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Correct Peaks.
        /// </summary>
        public static string ComparePeakPickingDlg_ComparePeakPickingDlg_Total_Correct_Peaks {
            get {
                return ResourceManager.GetString("ComparePeakPickingDlg_ComparePeakPickingDlg_Total_Correct_Peaks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add models/files for comparison to see a q-Q plot.
        /// </summary>
        public static string ComparePeakPickingDlg_InitializeGraphPanes_Add_models_files_for_comparison_to_see_a_q_Q_plot {
            get {
                return ResourceManager.GetString("ComparePeakPickingDlg_InitializeGraphPanes_Add_models_files_for_comparison_to_see" +
                        "_a_q_Q_plot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add models/files for comparison to see a ROC plot..
        /// </summary>
        public static string ComparePeakPickingDlg_InitializeGraphPanes_Add_models_files_for_comparison_to_see_a_ROC_plot_ {
            get {
                return ResourceManager.GetString("ComparePeakPickingDlg_InitializeGraphPanes_Add_models_files_for_comparison_to_see" +
                        "_a_ROC_plot_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add models/files for comparison to see an analysis of runs.
        /// </summary>
        public static string ComparePeakPickingDlg_InitializeGraphPanes_Add_models_files_for_comparison_to_see_an_analysis_of_runs {
            get {
                return ResourceManager.GetString("ComparePeakPickingDlg_InitializeGraphPanes_Add_models_files_for_comparison_to_see" +
                        "_an_analysis_of_runs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected False Positive Rate.
        /// </summary>
        public static string ComparePeakPickingDlg_InitializeGraphPanes_Expected_False_Positive_Rate {
            get {
                return ResourceManager.GetString("ComparePeakPickingDlg_InitializeGraphPanes_Expected_False_Positive_Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observed False Positive Rate.
        /// </summary>
        public static string ComparePeakPickingDlg_InitializeGraphPanes_Observed_False_Positive_Rate {
            get {
                return ResourceManager.GetString("ComparePeakPickingDlg_InitializeGraphPanes_Observed_False_Positive_Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replicate Name.
        /// </summary>
        public static string ComparePeakPickingDlg_InitializeGraphPanes_Replicate_Name {
            get {
                return ResourceManager.GetString("ComparePeakPickingDlg_InitializeGraphPanes_Replicate_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh {0}.
        /// </summary>
        public static string ComparePeakPickingDlg_RefreshDocument_Refresh__0_ {
            get {
                return ResourceManager.GetString("ComparePeakPickingDlg_RefreshDocument_Refresh__0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} observed false positive rate.
        /// </summary>
        public static string ComparePeakPickingDlg_UpdateGraph__0__observed_false_positive_rate {
            get {
                return ResourceManager.GetString("ComparePeakPickingDlg_UpdateGraph__0__observed_false_positive_rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} significance threshold.
        /// </summary>
        public static string ComparePeakPickingDlg_UpdateGraph__0__significance_threshold {
            get {
                return ResourceManager.GetString("ComparePeakPickingDlg_UpdateGraph__0__significance_threshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equality.
        /// </summary>
        public static string ComparePeakPickingDlg_UpdateGraph_Equality {
            get {
                return ResourceManager.GetString("ComparePeakPickingDlg_UpdateGraph_Equality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Q-Q Comparison.
        /// </summary>
        public static string ComparePeakPickingDlg_UpdateGraph_Q_Q_Comparison {
            get {
                return ResourceManager.GetString("ComparePeakPickingDlg_UpdateGraph_Q_Q_Comparison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replicate Comparison (Observed FPR &lt; {0}).
        /// </summary>
        public static string ComparePeakPickingDlg_UpdateGraph_Replicate_Comparison__Observed_FPR____0__ {
            get {
                return ResourceManager.GetString("ComparePeakPickingDlg_UpdateGraph_Replicate_Comparison__Observed_FPR____0__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replicate Comparison (q value &lt; {0}).
        /// </summary>
        public static string ComparePeakPickingDlg_UpdateGraph_Replicate_Comparison__q_value____0__ {
            get {
                return ResourceManager.GetString("ComparePeakPickingDlg_UpdateGraph_Replicate_Comparison__q_value____0__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ROC Plot Comparison.
        /// </summary>
        public static string ComparePeakPickingDlg_UpdateGraph_ROC_Plot_Comparison {
            get {
                return ResourceManager.GetString("ComparePeakPickingDlg_UpdateGraph_ROC_Plot_Comparison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metafile image copied to clipboard.
        /// </summary>
        public static string CopyEmfToolStripMenuItem_CopyEmf_Metafile_image_copied_to_clipboard {
            get {
                return ResourceManager.GetString("CopyEmfToolStripMenuItem_CopyEmf_Metafile_image_copied_to_clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column.
        /// </summary>
        public static string DisplayGraphsTypeExtension_LOCALIZED_VALUES_Column {
            get {
                return ResourceManager.GetString("DisplayGraphsTypeExtension_LOCALIZED_VALUES_Column", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row.
        /// </summary>
        public static string DisplayGraphsTypeExtension_LOCALIZED_VALUES_Row {
            get {
                return ResourceManager.GetString("DisplayGraphsTypeExtension_LOCALIZED_VALUES_Row", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiled.
        /// </summary>
        public static string DisplayGraphsTypeExtension_LOCALIZED_VALUES_Tiled {
            get {
                return ResourceManager.GetString("DisplayGraphsTypeExtension_LOCALIZED_VALUES_Tiled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Modifications.
        /// </summary>
        public static string EditLinkedPeptidesDlg_dataGridViewLinkedPeptides_CellToolTipTextNeeded_Edit_Modifications {
            get {
                return ResourceManager.GetString("EditLinkedPeptidesDlg_dataGridViewLinkedPeptides_CellToolTipTextNeeded_Edit_Modif" +
                        "ications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both ends of this crosslink cannot be the same..
        /// </summary>
        public static string EditLinkedPeptidesDlg_MakeCrosslink_Both_ends_of_this_crosslink_cannot_be_the_same_ {
            get {
                return ResourceManager.GetString("EditLinkedPeptidesDlg_MakeCrosslink_Both_ends_of_this_crosslink_cannot_be_the_sam" +
                        "e_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid crosslinker.
        /// </summary>
        public static string EditLinkedPeptidesDlg_MakeCrosslink_Invalid_crosslinker {
            get {
                return ResourceManager.GetString("EditLinkedPeptidesDlg_MakeCrosslink_Invalid_crosslinker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The crosslinker &apos;{0}&apos; cannot attach to this amino acid position..
        /// </summary>
        public static string EditLinkedPeptidesDlg_MakeCrosslink_The_crosslinker___0___cannot_attach_to_this_amino_acid_position_ {
            get {
                return ResourceManager.GetString("EditLinkedPeptidesDlg_MakeCrosslink_The_crosslinker___0___cannot_attach_to_this_a" +
                        "mino_acid_position_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This amino acid position cannot be blank..
        /// </summary>
        public static string EditLinkedPeptidesDlg_MakeCrosslink_This_amino_acid_position_cannot_be_blank_ {
            get {
                return ResourceManager.GetString("EditLinkedPeptidesDlg_MakeCrosslink_This_amino_acid_position_cannot_be_blank_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This amino acid position in this peptide is already being used by another crosslink..
        /// </summary>
        public static string EditLinkedPeptidesDlg_MakeCrosslink_This_amino_acid_position_in_this_peptide_is_already_being_used_by_another_crosslink_ {
            get {
                return ResourceManager.GetString("EditLinkedPeptidesDlg_MakeCrosslink_This_amino_acid_position_in_this_peptide_is_a" +
                        "lready_being_used_by_another_crosslink_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is not a valid amino acid position in this peptide..
        /// </summary>
        public static string EditLinkedPeptidesDlg_MakeCrosslink_This_is_not_a_valid_amino_acid_position_in_this_peptide_ {
            get {
                return ResourceManager.GetString("EditLinkedPeptidesDlg_MakeCrosslink_This_is_not_a_valid_amino_acid_position_in_th" +
                        "is_peptide_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This peptide is not valid..
        /// </summary>
        public static string EditLinkedPeptidesDlg_MakeCrosslink_This_peptide_is_not_valid_ {
            get {
                return ResourceManager.GetString("EditLinkedPeptidesDlg_MakeCrosslink_This_peptide_is_not_valid_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discard.
        /// </summary>
        public static string EditPepModsDlg_EnsureLinkedPeptide_ButtonText_Discard {
            get {
                return ResourceManager.GetString("EditPepModsDlg_EnsureLinkedPeptide_ButtonText_Discard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Crosslinks.
        /// </summary>
        public static string EditPepModsDlg_EnsureLinkedPeptide_ButtonText_Edit_Crosslinks {
            get {
                return ResourceManager.GetString("EditPepModsDlg_EnsureLinkedPeptide_ButtonText_Edit_Crosslinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing the crosslink on this amino acid will result in a crosslinked peptide no longer being connected. Would you like to edit the crosslinks now or discard the disconnected peptides?.
        /// </summary>
        public static string EditPepModsDlg_EnsureLinkedPeptide_Discard_or_edit_disconnected_crosslinks {
            get {
                return ResourceManager.GetString("EditPepModsDlg_EnsureLinkedPeptide_Discard_or_edit_disconnected_crosslinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Isotope {0}:.
        /// </summary>
        public static string EditPepModsDlg_GetIsotopeLabelText_Isotope__0__ {
            get {
                return ResourceManager.GetString("EditPepModsDlg_GetIsotopeLabelText_Isotope__0__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crosslink to {0}: {1} [{2}].
        /// </summary>
        public static string EditPepModsDlg_GetTooltip_Crosslink_to__0____1____2__ {
            get {
                return ResourceManager.GetString("EditPepModsDlg_GetTooltip_Crosslink_to__0____1____2__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid crosslink: {0}.
        /// </summary>
        public static string EditPepModsDlg_GetTooltip_Invalid_crosslink___0_ {
            get {
                return ResourceManager.GetString("EditPepModsDlg_GetTooltip_Invalid_crosslink___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looplink: {0} [{1}].
        /// </summary>
        public static string EditPepModsDlg_GetTooltip_Looplink___0____1__ {
            get {
                return ResourceManager.GetString("EditPepModsDlg_GetTooltip_Looplink___0____1__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more of the crosslinked peptides are no longer attached to this peptide. .
        /// </summary>
        public static string EditPepModsDlg_OkDialog_One_or_more_of_the_crosslinked_peptides_are_no_longer_attached_to_this_peptide__ {
            get {
                return ResourceManager.GetString("EditPepModsDlg_OkDialog_One_or_more_of_the_crosslinked_peptides_are_no_longer_att" +
                        "ached_to_this_peptide__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case {0}.
        /// </summary>
        public static string EditSpectrumFilterDlg_MakePageButton_Case__0_ {
            get {
                return ResourceManager.GetString("EditSpectrumFilterDlg_MakePageButton_Case__0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;&lt; Hide Ad&amp;vanced.
        /// </summary>
        public static string FindNodeDlg_AdvancedVisible_Hide_Advanced {
            get {
                return ResourceManager.GetString("FindNodeDlg_AdvancedVisible_Hide_Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Ad&amp;vanced &gt;&gt;.
        /// </summary>
        public static string FindNodeDlg_AdvancedVisible_Show_Advanced {
            get {
                return ResourceManager.GetString("FindNodeDlg_AdvancedVisible_Show_Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of peptides {0} must be less than the number of peptide precursor models for decoys {1}, or use the &apos;{2}&apos; decoy generation method..
        /// </summary>
        public static string GenerateDecoysDlg_OkDialog_The_number_of_peptides__0__must_be_less_than_the_number_of_peptide_precursor_models_for_decoys__1___or_use_the___2___decoy_generation_method_ {
            get {
                return ResourceManager.GetString("GenerateDecoysDlg_OkDialog_The_number_of_peptides__0__must_be_less_than_the_numbe" +
                        "r_of_peptide_precursor_models_for_decoys__1___or_use_the___2___decoy_generation_" +
                        "method_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On line {0}, row has more than 2 columns.
        /// </summary>
        public static string GridViewDriver_ValidateRow_On_line__0__row_has_more_than_2_columns {
            get {
                return ResourceManager.GetString("GridViewDriver_ValidateRow_On_line__0__row_has_more_than_2_columns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acquired Time.
        /// </summary>
        public static string GroupGraphsOrderExtension_LOCALIZED_VALUES_Acquired_Time {
            get {
                return ResourceManager.GetString("GroupGraphsOrderExtension_LOCALIZED_VALUES_Acquired_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document.
        /// </summary>
        public static string GroupGraphsOrderExtension_LOCALIZED_VALUES_Document {
            get {
                return ResourceManager.GetString("GroupGraphsOrderExtension_LOCALIZED_VALUES_Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string GroupGraphsOrderExtension_LOCALIZED_VALUES_Position {
            get {
                return ResourceManager.GetString("GroupGraphsOrderExtension_LOCALIZED_VALUES_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a capital letter that corresponds to an amino acid..
        /// </summary>
        public static string ImportFastaHelper_AddFasta___0___is_not_a_capital_letter_that_corresponds_to_an_amino_acid_ {
            get {
                return ResourceManager.GetString("ImportFastaHelper_AddFasta___0___is_not_a_capital_letter_that_corresponds_to_an_a" +
                        "mino_acid_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred: .
        /// </summary>
        public static string ImportFastaHelper_AddFasta_An_unexpected_error_occurred__ {
            get {
                return ResourceManager.GetString("ImportFastaHelper_AddFasta_An_unexpected_error_occurred__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no name for this protein.
        /// </summary>
        public static string ImportFastaHelper_AddFasta_There_is_no_name_for_this_protein {
            get {
                return ResourceManager.GetString("ImportFastaHelper_AddFasta_There_is_no_name_for_this_protein", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This must start with &apos;&gt;&apos;.
        /// </summary>
        public static string ImportFastaHelper_AddFasta_This_must_start_with____ {
            get {
                return ResourceManager.GetString("ImportFastaHelper_AddFasta_This_must_start_with____", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no sequence for this protein.
        /// </summary>
        public static string ImportFastaHelper_CheckSequence_There_is_no_sequence_for_this_protein {
            get {
                return ResourceManager.GetString("ImportFastaHelper_CheckSequence_There_is_no_sequence_for_this_protein", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FASTA files.
        /// </summary>
        public static string OpenFileDialog_FASTA_files {
            get {
                return ResourceManager.GetString("OpenFileDialog_FASTA_files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string PasteDlg_AddPeptides_OK {
            get {
                return ResourceManager.GetString("PasteDlg_AddPeptides_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This peptide sequence was not found in the protein sequence.
        /// </summary>
        public static string PasteDlg_AddPeptides_This_peptide_sequence_was_not_found_in_the_protein_sequence {
            get {
                return ResourceManager.GetString("PasteDlg_AddPeptides_This_peptide_sequence_was_not_found_in_the_protein_sequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to interpret peptide modifications.
        /// </summary>
        public static string PasteDlg_AddPeptides_Unable_to_interpret_peptide_modifications {
            get {
                return ResourceManager.GetString("PasteDlg_AddPeptides_Unable_to_interpret_peptide_modifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to use the Unimod definitions for the following modifications?.
        /// </summary>
        public static string PasteDlg_AddPeptides_Would_you_like_to_use_the_Unimod_definitions_for_the_following_modifications {
            get {
                return ResourceManager.GetString("PasteDlg_AddPeptides_Would_you_like_to_use_the_Unimod_definitions_for_the_followi" +
                        "ng_modifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid protein sequence: {0}.
        /// </summary>
        public static string PasteDlg_AddProteins_Invalid_protein_sequence__0__ {
            get {
                return ResourceManager.GetString("PasteDlg_AddProteins_Invalid_protein_sequence__0__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing protein sequence.
        /// </summary>
        public static string PasteDlg_AddProteins_Missing_protein_sequence {
            get {
                return ResourceManager.GetString("PasteDlg_AddProteins_Missing_protein_sequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This protein was not found in the background proteome database..
        /// </summary>
        public static string PasteDlg_AddProteins_This_protein_was_not_found_in_the_background_proteome_database {
            get {
                return ResourceManager.GetString("PasteDlg_AddProteins_This_protein_was_not_found_in_the_background_proteome_databa" +
                        "se", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert.
        /// </summary>
        public static string PasteDlg_Description_Insert {
            get {
                return ResourceManager.GetString("PasteDlg_Description_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert FASTA.
        /// </summary>
        public static string PasteDlg_Description_Insert_FASTA {
            get {
                return ResourceManager.GetString("PasteDlg_Description_Insert_FASTA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert peptide list.
        /// </summary>
        public static string PasteDlg_Description_Insert_peptide_list {
            get {
                return ResourceManager.GetString("PasteDlg_Description_Insert_peptide_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert protein list.
        /// </summary>
        public static string PasteDlg_Description_Insert_protein_list {
            get {
                return ResourceManager.GetString("PasteDlg_Description_Insert_protein_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The peptide sequence cannot be blank..
        /// </summary>
        public static string PasteDlg_ListPeptideSequences_The_peptide_sequence_cannot_be_blank {
            get {
                return ResourceManager.GetString("PasteDlg_ListPeptideSequences_The_peptide_sequence_cannot_be_blank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The structure of this crosslinked peptide is not supported by Skyline.
        /// </summary>
        public static string PasteDlg_ListPeptideSequences_The_structure_of_this_crosslinked_peptide_is_not_supported_by_Skyline {
            get {
                return ResourceManager.GetString("PasteDlg_ListPeptideSequences_The_structure_of_this_crosslinked_peptide_is_not_su" +
                        "pported_by_Skyline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This peptide sequence contains invalid characters..
        /// </summary>
        public static string PasteDlg_ListPeptideSequences_This_peptide_sequence_contains_invalid_characters {
            get {
                return ResourceManager.GetString("PasteDlg_ListPeptideSequences_This_peptide_sequence_contains_invalid_characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must select a model for comparison..
        /// </summary>
        public static string PeakBoundaryCompareTest_DoTest_Must_select_a_model_for_comparison_ {
            get {
                return ResourceManager.GetString("PeakBoundaryCompareTest_DoTest_Must_select_a_model_for_comparison_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permute isotope modifications.
        /// </summary>
        public static string PermuteIsotopeModificationsDlg_OkDialog_Permute_isotope_modifications {
            get {
                return ResourceManager.GetString("PermuteIsotopeModificationsDlg_OkDialog_Permute_isotope_modifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permuting Isotope Modifications.
        /// </summary>
        public static string PermuteIsotopeModificationsDlg_OkDialog_Permuting_Isotope_Modifications {
            get {
                return ResourceManager.GetString("PermuteIsotopeModificationsDlg_OkDialog_Permuting_Isotope_Modifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating settings.
        /// </summary>
        public static string PermuteIsotopeModificationsDlg_OkDialog_Updating_settings {
            get {
                return ResourceManager.GetString("PermuteIsotopeModificationsDlg_OkDialog_Updating_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add la&amp;bel type:.
        /// </summary>
        public static string RefineDlg_cbAdd_CheckedChanged_Add_label_type {
            get {
                return ResourceManager.GetString("RefineDlg_cbAdd_CheckedChanged_Add_label_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precursors of the chosen isotope label type will be added if they are missing.
        /// </summary>
        public static string RefineDlg_cbAdd_CheckedChanged_Precursors_of_the_chosen_isotope_label_type_will_be_added_if_they_are_missing {
            get {
                return ResourceManager.GetString("RefineDlg_cbAdd_CheckedChanged_Precursors_of_the_chosen_isotope_label_type_will_b" +
                        "e_added_if_they_are_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        public static string RefineDlg_MSLevel_1 {
            get {
                return ResourceManager.GetString("RefineDlg_MSLevel_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        public static string RefineDlg_MSLevel_2 {
            get {
                return ResourceManager.GetString("RefineDlg_MSLevel_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be less than min peak found ratio..
        /// </summary>
        public static string RefineDlg_OkDialog__0__must_be_less_than_min_peak_found_ratio {
            get {
                return ResourceManager.GetString("RefineDlg_OkDialog__0__must_be_less_than_min_peak_found_ratio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The label type &apos;{0}&apos; cannot be added. There are no modifications for this type..
        /// </summary>
        public static string RefineDlg_OkDialog_The_label_type__0__cannot_be_added_There_are_no_modifications_for_this_type {
            get {
                return ResourceManager.GetString("RefineDlg_OkDialog_The_label_type__0__cannot_be_added_There_are_no_modifications_" +
                        "for_this_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all.
        /// </summary>
        public static string RefineDlg_RefineDlg_all {
            get {
                return ResourceManager.GetString("RefineDlg_RefineDlg_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to best.
        /// </summary>
        public static string RefineDlg_RefineDlg_best {
            get {
                return ResourceManager.GetString("RefineDlg_RefineDlg_best", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must train and select a model in order to reintegrate peaks..
        /// </summary>
        public static string ReintegrateDlg_OkDialog_You_must_train_and_select_a_model_in_order_to_reintegrate_peaks_ {
            get {
                return ResourceManager.GetString("ReintegrateDlg_OkDialog_You_must_train_and_select_a_model_in_order_to_reintegrate" +
                        "_peaks_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add FASTA File.
        /// </summary>
        public static string RenameProteinsDlg_btnFASTA_Click_Add_FASTA_File {
            get {
                return ResourceManager.GetString("RenameProteinsDlg_btnFASTA_Click_Add_FASTA_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No protein metadata available.
        /// </summary>
        public static string RenameProteinsDlg_UseAccessionOrPreferredNameorGene_No_protein_metadata_available {
            get {
                return ResourceManager.GetString("RenameProteinsDlg_UseAccessionOrPreferredNameorGene_No_protein_metadata_available" +
                        "", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed reading the file {0}. {1}.
        /// </summary>
        public static string RenameProteinsDlg_UseFastaFile_Failed_reading_the_file__0__1__ {
            get {
                return ResourceManager.GetString("RenameProteinsDlg_UseFastaFile_Failed_reading_the_file__0__1__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No protein sequence matches found between the current document and the FASTA file {0}.
        /// </summary>
        public static string RenameProteinsDlg_UseFastaFile_No_protein_sequence_matches_found_between_the_current_document_and_the_FASTA_file__0_ {
            get {
                return ResourceManager.GetString("RenameProteinsDlg_UseFastaFile_No_protein_sequence_matches_found_between_the_curr" +
                        "ent_document_and_the_FASTA_file__0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template file is not valid..
        /// </summary>
        public static string SchedulingGraphPropertyDlg_OkDialog_Template_file_is_not_valid_ {
            get {
                return ResourceManager.GetString("SchedulingGraphPropertyDlg_OkDialog_Template_file_is_not_valid_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation discarded {0} proteins with no peptides matching the current filter settings..
        /// </summary>
        public static string SkylineWindow_ImportFasta_This_operation_discarded__0__proteins_with_no_peptides_matching_the_current_filter_settings_ {
            get {
                return ResourceManager.GetString("SkylineWindow_ImportFasta_This_operation_discarded__0__proteins_with_no_peptides_" +
                        "matching_the_current_filter_settings_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To align to retention time prediction, you must first set up a retention time predictor in Peptide Settings / Prediction..
        /// </summary>
        public static string SynchronizedIntegrationDlg_comboAlign_SelectedIndexChanged_To_align_to_retention_time_prediction__you_must_first_set_up_a_retention_time_predictor_in_Peptide_Settings___Prediction_ {
            get {
                return ResourceManager.GetString("SynchronizedIntegrationDlg_comboAlign_SelectedIndexChanged_To_align_to_retention_" +
                        "time_prediction__you_must_first_set_up_a_retention_time_predictor_in_Peptide_Set" +
                        "tings___Prediction_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding rows to grid..
        /// </summary>
        public static string UniquePeptidesDlg_AddProteinRowsToGrid_Adding_rows_to_grid_ {
            get {
                return ResourceManager.GetString("UniquePeptidesDlg_AddProteinRowsToGrid_Adding_rows_to_grid_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed querying background proteome {0}..
        /// </summary>
        public static string UniquePeptidesDlg_LaunchPeptideProteinsQuery_Failed_querying_background_proteome__0__ {
            get {
                return ResourceManager.GetString("UniquePeptidesDlg_LaunchPeptideProteinsQuery_Failed_querying_background_proteome_" +
                        "_0__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looking for proteins with matching peptide sequences.
        /// </summary>
        public static string UniquePeptidesDlg_LaunchPeptideProteinsQuery_Looking_for_proteins_with_matching_peptide_sequences {
            get {
                return ResourceManager.GetString("UniquePeptidesDlg_LaunchPeptideProteinsQuery_Looking_for_proteins_with_matching_p" +
                        "eptide_sequences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Querying Background Proteome Database.
        /// </summary>
        public static string UniquePeptidesDlg_LaunchPeptideProteinsQuery_Querying_Background_Proteome_Database {
            get {
                return ResourceManager.GetString("UniquePeptidesDlg_LaunchPeptideProteinsQuery_Querying_Background_Proteome_Databas" +
                        "e", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclude peptides.
        /// </summary>
        public static string UniquePeptidesDlg_OkDialog_Exclude_peptides {
            get {
                return ResourceManager.GetString("UniquePeptidesDlg_OkDialog_Exclude_peptides", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These proteins include:.
        /// </summary>
        public static string UniquePeptidesDlg_SelectPeptidesWithNumberOfMatchesAtOrBelowThreshold_These_proteins_include_ {
            get {
                return ResourceManager.GetString("UniquePeptidesDlg_SelectPeptidesWithNumberOfMatchesAtOrBelowThreshold_These_prote" +
                        "ins_include_", resourceCulture);
            }
        }
    }
}
