#
# makefile (peaks_tools)
#

include project_paths.inc

TARGETS = \
    cfd \
    td \
    tlp \
    tlpinit \
    tlpiter \
    tlperror \
    proctran

include $(MSTOOLS_ROOT)/src/make/make_project.inc

