Title = Count Proteins using R
Command = $(ProgramPath(R,4.4.1))
Arguments = -f "$(ToolDir)\\CountProteins.R" --args "$(ToolDir)" $(SkylineConnection)
OutputToImmediateWindow = True
Identifier = URN:LSID:skyline.ms:Examples:CountProteins

