Title = Display Connection ID
Command = C:\\Windows\\System32\\cmd.exe
Arguments = /c echo $(SkylineConnection)
OutputToImmediateWindow = True
Identifier = URN:LSID:skyline.ms:Examples:DisplaySkylineConnectionId
