//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pwiz.Skyline.Controls.Databinding {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DatabindingResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DatabindingResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("pwiz.Skyline.Controls.Databinding.DatabindingResources", typeof(DatabindingResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Candidate Peaks.
        /// </summary>
        public static string CandidatePeakForm_CandidatePeakForm_Candidate_Peaks {
            get {
                return ResourceManager.GetString("CandidatePeakForm_CandidatePeakForm_Candidate_Peaks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Heat Map.
        /// </summary>
        public static string DataboundGridControl_DataboundGridControl_Show_Heat_Map {
            get {
                return ResourceManager.GetString("DataboundGridControl_DataboundGridControl_Show_Heat_Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show PCA Plot.
        /// </summary>
        public static string DataboundGridControl_DataboundGridControl_Show_PCA_Plot {
            get {
                return ResourceManager.GetString("DataboundGridControl_DataboundGridControl_Show_PCA_Plot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while displaying the data rows:.
        /// </summary>
        public static string DataboundGridControl_DisplayError_An_error_occured_while_displaying_the_data_rows_ {
            get {
                return ResourceManager.GetString("DataboundGridControl_DisplayError_An_error_occured_while_displaying_the_data_rows" +
                        "_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to continue to see these error messages?.
        /// </summary>
        public static string DataboundGridControl_DisplayError_Do_you_want_to_continue_to_see_these_error_messages_ {
            get {
                return ResourceManager.GetString("DataboundGridControl_DisplayError_Do_you_want_to_continue_to_see_these_error_mess" +
                        "ages_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error setting value:.
        /// </summary>
        public static string DataboundGridControl_DoFillDown_Error_setting_value_ {
            get {
                return ResourceManager.GetString("DataboundGridControl_DoFillDown_Error_setting_value_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filling {0}/{1} rows.
        /// </summary>
        public static string DataboundGridControl_DoFillDown_Filling__0___1__rows {
            get {
                return ResourceManager.GetString("DataboundGridControl_DoFillDown_Filling__0___1__rows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill Down.
        /// </summary>
        public static string DataboundGridControl_FillDown_Fill_Down {
            get {
                return ResourceManager.GetString("DataboundGridControl_FillDown_Fill_Down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating document settings to match edits..
        /// </summary>
        public static string DataGridViewPasteHandler_EndDeferSettingsChangesOnDocument_Updating_settings {
            get {
                return ResourceManager.GetString("DataGridViewPasteHandler_EndDeferSettingsChangesOnDocument_Updating_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Report.
        /// </summary>
        public static string DocumentGridViewContext_CreateViewEditor_Edit_Report {
            get {
                return ResourceManager.GetString("DocumentGridViewContext_CreateViewEditor_Edit_Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview: {0}.
        /// </summary>
        public static string DocumentGridViewContext_Preview_Preview___0_ {
            get {
                return ResourceManager.GetString("DocumentGridViewContext_Preview_Preview___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview New Report.
        /// </summary>
        public static string DocumentGridViewContext_Preview_Preview_New_Report {
            get {
                return ResourceManager.GetString("DocumentGridViewContext_Preview_Preview_New_Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invariant.
        /// </summary>
        public static string ExportLiveReportDlg_ExportLiveReportDlg_Invariant {
            get {
                return ResourceManager.GetString("ExportLiveReportDlg_ExportLiveReportDlg_Invariant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview: .
        /// </summary>
        public static string ExportLiveReportDlg_ShowPreview_Preview__ {
            get {
                return ResourceManager.GetString("ExportLiveReportDlg_ShowPreview_Preview__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building report....
        /// </summary>
        public static string ExportReportDlg_ExportReport_Building_report {
            get {
                return ResourceManager.GetString("ExportReportDlg_ExportReport_Building_report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed exporting to {0}.
        ///{1}.
        /// </summary>
        public static string ExportReportDlg_ExportReport_Failed_exporting_to {
            get {
                return ResourceManager.GetString("ExportReportDlg_ExportReport_Failed_exporting_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating Report.
        /// </summary>
        public static string ExportReportDlg_ExportReport_Generating_Report {
            get {
                return ResourceManager.GetString("ExportReportDlg_ExportReport_Generating_Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing report....
        /// </summary>
        public static string ExportReportDlg_ExportReport_Writing_report {
            get {
                return ResourceManager.GetString("ExportReportDlg_ExportReport_Writing_report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skyline Reports.
        /// </summary>
        public static string ExportReportDlg_ShowShare_Skyline_Reports {
            get {
                return ResourceManager.GetString("ExportReportDlg_ShowShare_Skyline_Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Document Reports.
        /// </summary>
        public static string SkylineViewContext_ChangeDocumentViewSpec_Change_Document_Reports {
            get {
                return ResourceManager.GetString("SkylineViewContext_ChangeDocumentViewSpec_Change_Document_Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Molecule Lists.
        /// </summary>
        public static string SkylineViewContext_GetDocumentGridRowSources_Molecule_Lists {
            get {
                return ResourceManager.GetString("SkylineViewContext_GetDocumentGridRowSources_Molecule_Lists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure loading {0}..
        /// </summary>
        public static string SkylineViewContext_ImportViews_Failure_loading__0__ {
            get {
                return ResourceManager.GetString("SkylineViewContext_ImportViews_Failure_loading__0__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No views were found in that file..
        /// </summary>
        public static string SkylineViewContext_ImportViews_No_views_were_found_in_that_file_ {
            get {
                return ResourceManager.GetString("SkylineViewContext_ImportViews_No_views_were_found_in_that_file_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Document Reports.
        /// </summary>
        public static string SkylineViewContext_SaveViewSpecList_Change_Document_Reports {
            get {
                return ResourceManager.GetString("SkylineViewContext_SaveViewSpecList_Change_Document_Reports", resourceCulture);
            }
        }
    }
}
