//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pwiz.Skyline.FileUI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FileUIResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FileUIResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("pwiz.Skyline.FileUI.FileUIResources", typeof(FileUIResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After minimizing, the cache file will be reduced to {0:0%} its current size.
        /// </summary>
        public static string BackgroundWorker_UpdateStatistics_After_minimizing_the_cache_file_will_be_reduced_to__0__its_current_size {
            get {
                return ResourceManager.GetString("BackgroundWorker_UpdateStatistics_After_minimizing_the_cache_file_will_be_reduced" +
                        "_to__0__its_current_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computing space savings ({0}% complete).
        /// </summary>
        public static string BackgroundWorker_UpdateStatistics_Computing_space_savings__0__complete {
            get {
                return ResourceManager.GetString("BackgroundWorker_UpdateStatistics_Computing_space_savings__0__complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current size of the cache file is {0:fs}.
        /// </summary>
        public static string BackgroundWorker_UpdateStatistics_The_current_size_of_the_cache_file_is__0__fs {
            get {
                return ResourceManager.GetString("BackgroundWorker_UpdateStatistics_The_current_size_of_the_cache_file_is__0__fs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Transition List (iRT standards).
        /// </summary>
        public static string ChooseIrtStandardPeptides_ImportTextFile_Import_Transition_List__iRT_standards_ {
            get {
                return ResourceManager.GetString("ChooseIrtStandardPeptides_ImportTextFile_Import_Transition_List__iRT_standards_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transition List.
        /// </summary>
        public static string ChooseIrtStandardPeptides_ImportTextFile_Transition_List {
            get {
                return ResourceManager.GetString("ChooseIrtStandardPeptides_ImportTextFile_Transition_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transition list field must contain a path to a valid file..
        /// </summary>
        public static string ChooseIrtStandardPeptides_OkDialog_Transition_list_field_must_contain_a_path_to_a_valid_file_ {
            get {
                return ResourceManager.GetString("ChooseIrtStandardPeptides_OkDialog_Transition_list_field_must_contain_a_path_to_a" +
                        "_valid_file_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unavailable: no matching iRT standards found.
        /// </summary>
        public static string ChooseIrtStandardPeptidesDlg_ChooseIrtStandardPeptidesDlg_Unavailable__no_matching_iRT_standards_found {
            get {
                return ResourceManager.GetString("ChooseIrtStandardPeptidesDlg_ChooseIrtStandardPeptidesDlg_Unavailable__no_matchin" +
                        "g_iRT_standards_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Known iRTs.
        /// </summary>
        public static string ChooseIrtStandardPeptidesDlg_OkDialog_Known_iRTs {
            get {
                return ResourceManager.GetString("ChooseIrtStandardPeptidesDlg_OkDialog_Known_iRTs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library iRTs.
        /// </summary>
        public static string ChooseIrtStandardPeptidesDlg_OkDialog_Library_iRTs {
            get {
                return ResourceManager.GetString("ChooseIrtStandardPeptidesDlg_OkDialog_Library_iRTs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linear regression.
        /// </summary>
        public static string ChooseIrtStandardPeptidesDlg_OkDialog_Linear_regression {
            get {
                return ResourceManager.GetString("ChooseIrtStandardPeptidesDlg_OkDialog_Linear_regression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a protein containing the list of standard peptides for the iRT calculator..
        /// </summary>
        public static string ChooseIrtStandardPeptidesDlg_OkDialog_Please_select_a_protein_containing_the_list_of_standard_peptides_for_the_iRT_calculator_ {
            get {
                return ResourceManager.GetString("ChooseIrtStandardPeptidesDlg_OkDialog_Please_select_a_protein_containing_the_list" +
                        "_of_standard_peptides_for_the_iRT_calculator_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The set of replicates in this document has changed. Please choose again which replicates to use for the retention time filter..
        /// </summary>
        public static string ChooseSchedulingReplicatesDlg_btnOk_Click_The_set_of_replicates_in_this_document_has_changed___Please_choose_again_which_replicates_to_use_for_the_retention_time_filter_ {
            get {
                return ResourceManager.GetString("ChooseSchedulingReplicatesDlg_btnOk_Click_The_set_of_replicates_in_this_document_" +
                        "has_changed___Please_choose_again_which_replicates_to_use_for_the_retention_time" +
                        "_filter_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must choose at least one replicate.
        /// </summary>
        public static string ChooseSchedulingReplicatesDlg_btnOk_Click_You_must_choose_at_least_one_replicate {
            get {
                return ResourceManager.GetString("ChooseSchedulingReplicatesDlg_btnOk_Click_You_must_choose_at_least_one_replicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot read the database file {0}..
        /// </summary>
        public static string CreateIrtCalculatorDlg_OkDialog_Cannot_read_the_database_file__0_ {
            get {
                return ResourceManager.GetString("CreateIrtCalculatorDlg_OkDialog_Cannot_read_the_database_file__0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a protein containing the list of standard peptides for the iRT calculator..
        /// </summary>
        public static string CreateIrtCalculatorDlg_OkDialog_Please_select_a_protein_containing_the_list_of_standard_peptides_for_the_iRT_calculator_ {
            get {
                return ResourceManager.GetString("CreateIrtCalculatorDlg_OkDialog_Please_select_a_protein_containing_the_list_of_st" +
                        "andard_peptides_for_the_iRT_calculator_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chromatogram Export Files.
        /// </summary>
        public static string ExportChromatogramDlg_OkDialog_Chromatogram_Export_Files {
            get {
                return ResourceManager.GetString("ExportChromatogramDlg_OkDialog_Chromatogram_Export_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Chromatograms.
        /// </summary>
        public static string ExportChromatogramDlg_OkDialog_Export_Chromatogram {
            get {
                return ResourceManager.GetString("ExportChromatogramDlg_OkDialog_Export_Chromatogram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting Chromatograms.
        /// </summary>
        public static string ExportChromatogramDlg_OkDialog_Exporting_Chromatograms {
            get {
                return ResourceManager.GetString("ExportChromatogramDlg_OkDialog_Exporting_Chromatograms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed attempting to save chromatograms to {0}..
        /// </summary>
        public static string ExportChromatogramDlg_OkDialog_Failed_attempting_to_save_chromatograms_to__0__ {
            get {
                return ResourceManager.GetString("ExportChromatogramDlg_OkDialog_Failed_attempting_to_save_chromatograms_to__0__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred attempting to export..
        /// </summary>
        public static string ExportDlgProperties_PerformLongExport_An_error_occurred_attempting_to_export {
            get {
                return ResourceManager.GetString("ExportDlgProperties_PerformLongExport_An_error_occurred_attempting_to_export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting Methods.
        /// </summary>
        public static string ExportDlgProperties_PerformLongExport_Exporting_Methods {
            get {
                return ResourceManager.GetString("ExportDlgProperties_PerformLongExport_Exporting_Methods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accumulation time (sec):.
        /// </summary>
        public static string ExportMethodDlg_ACCUMULATION_TIME_TXT {
            get {
                return ResourceManager.GetString("ExportMethodDlg_ACCUMULATION_TIME_TXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The chosen folder does not appear to contain a Bruker TOF method template. The folder is expected to have a .m extension, and contain the file submethods.xml..
        /// </summary>
        public static string ExportMethodDlg_btnBrowseTemplate_Click_The_chosen_folder_does_not_appear_to_contain_a_Bruker_TOF_method_template___The_folder_is_expected_to_have_a__m_extension__and_contain_the_file_submethods_xml_ {
            get {
                return ResourceManager.GetString("ExportMethodDlg_btnBrowseTemplate_Click_The_chosen_folder_does_not_appear_to_cont" +
                        "ain_a_Bruker_TOF_method_template___The_folder_is_expected_to_have_a__m_extension" +
                        "__and_contain_the_file_submethods_xml_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The chosen folder does not appear to contain an Agilent MassHunter 12 method template. The folder is expected to have a .m extension..
        /// </summary>
        public static string ExportMethodDlg_btnBrowseTemplate_Click_The_chosen_folder_does_not_appear_to_contain_an_Agilent_MassHunter_12_method_template__The_folder_is_expected_to_have_a__m_extension_ {
            get {
                return ResourceManager.GetString("ExportMethodDlg_btnBrowseTemplate_Click_The_chosen_folder_does_not_appear_to_cont" +
                        "ain_an_Agilent_MassHunter_12_method_template__The_folder_is_expected_to_have_a__" +
                        "m_extension_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agilent 6400 series instrument type methods are expected to have a .m extension, and contain the file qqqacqmethod.xsd. If this is an Agilent TQ method, please choose &quot;Agilent MassHunter 12 or higher&quot; as your instrument type..
        /// </summary>
        public static string ExportMethodDlg_btnBrowseTemplate_Click_The_chosen_folder_does_not_appear_to_contain_an_Agilent_QQQ_method_template_The_folder_is_expected_to_have_a_m_extension_and_contain_the_file_qqqacqmethod_xsd {
            get {
                return ResourceManager.GetString("ExportMethodDlg_btnBrowseTemplate_Click_The_chosen_folder_does_not_appear_to_cont" +
                        "ain_an_Agilent_QQQ_method_template_The_folder_is_expected_to_have_a_m_extension_" +
                        "and_contain_the_file_qqqacqmethod_xsd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred..
        /// </summary>
        public static string ExportMethodDlg_btnGraph_Click_An_error_occurred_ {
            get {
                return ResourceManager.GetString("ExportMethodDlg_btnGraph_Click_An_error_occurred_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grouping peptides by protein has not yet been implemented for scheduled methods..
        /// </summary>
        public static string ExportMethodDlg_cbIgnoreProteins_CheckedChanged_Grouping_peptides_by_protein_has_not_yet_been_implemented_for_scheduled_methods_ {
            get {
                return ResourceManager.GetString("ExportMethodDlg_cbIgnoreProteins_CheckedChanged_Grouping_peptides_by_protein_has_" +
                        "not_yet_been_implemented_for_scheduled_methods_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export of DIA isolation lists is not yet supported for {0}..
        /// </summary>
        public static string ExportMethodDlg_comboInstrument_SelectedIndexChanged_Export_of_DIA_isolation_lists_is_not_yet_supported_for__0__ {
            get {
                return ResourceManager.GetString("ExportMethodDlg_comboInstrument_SelectedIndexChanged_Export_of_DIA_isolation_list" +
                        "s_is_not_yet_supported_for__0__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export a method with extra transitions for finding an optimal value..
        /// </summary>
        public static string ExportMethodDlg_comboOptimizing_SelectedIndexChanged_Export_a_method_with_extra_transitions_for_finding_an_optimal_value_ {
            get {
                return ResourceManager.GetString("ExportMethodDlg_comboOptimizing_SelectedIndexChanged_Export_a_method_with_extra_t" +
                        "ransitions_for_finding_an_optimal_value_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optimizing for {0} will produce an additional {1} transitions per transition..
        /// </summary>
        public static string ExportMethodDlg_comboOptimizing_SelectedIndexChanged_Optimizing_for__0__will_produce_an_additional__1__transitions_per_transition_ {
            get {
                return ResourceManager.GetString("ExportMethodDlg_comboOptimizing_SelectedIndexChanged_Optimizing_for__0__will_prod" +
                        "uce_an_additional__1__transitions_per_transition_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check the calculator settings..
        /// </summary>
        public static string ExportMethodDlg_comboTargetType_SelectedIndexChanged_Check_the_calculator_settings {
            get {
                return ResourceManager.GetString("ExportMethodDlg_comboTargetType_SelectedIndexChanged_Check_the_calculator_setting" +
                        "s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check to make sure the document contains times for all of the required standard peptides..
        /// </summary>
        public static string ExportMethodDlg_comboTargetType_SelectedIndexChanged_Check_to_make_sure_the_document_contains_times_for_all_of_the_required_standard_peptides {
            get {
                return ResourceManager.GetString("ExportMethodDlg_comboTargetType_SelectedIndexChanged_Check_to_make_sure_the_docum" +
                        "ent_contains_times_for_all_of_the_required_standard_peptides", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retention time prediction calculator is unable to score..
        /// </summary>
        public static string ExportMethodDlg_comboTargetType_SelectedIndexChanged_Retention_time_prediction_calculator_is_unable_to_score {
            get {
                return ResourceManager.GetString("ExportMethodDlg_comboTargetType_SelectedIndexChanged_Retention_time_prediction_ca" +
                        "lculator_is_unable_to_score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retention time predictor is unable to auto-calculate a regression..
        /// </summary>
        public static string ExportMethodDlg_comboTargetType_SelectedIndexChanged_Retention_time_predictor_is_unable_to_auto_calculate_a_regression {
            get {
                return ResourceManager.GetString("ExportMethodDlg_comboTargetType_SelectedIndexChanged_Retention_time_predictor_is_" +
                        "unable_to_auto_calculate_a_regression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduled methods are not supported for the selected instrument..
        /// </summary>
        public static string ExportMethodDlg_comboTargetType_SelectedIndexChanged_Sched_Not_Supported_Err_Text {
            get {
                return ResourceManager.GetString("ExportMethodDlg_comboTargetType_SelectedIndexChanged_Sched_Not_Supported_Err_Text" +
                        "", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To export a scheduled method, you must first choose a retention time predictor in Peptide Settings / Prediction..
        /// </summary>
        public static string ExportMethodDlg_comboTargetType_SelectedIndexChanged_To_export_a_scheduled_list_you_must_first_choose_a_retention_time_predictor_in_Peptide_Settings_Prediction {
            get {
                return ResourceManager.GetString("ExportMethodDlg_comboTargetType_SelectedIndexChanged_To_export_a_scheduled_list_y" +
                        "ou_must_first_choose_a_retention_time_predictor_in_Peptide_Settings_Prediction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To export a scheduled method, you must first import results for all peptides in the document..
        /// </summary>
        public static string ExportMethodDlg_comboTargetType_SelectedIndexChanged_To_export_a_scheduled_list_you_must_first_import_results_for_all_peptides_in_the_document {
            get {
                return ResourceManager.GetString("ExportMethodDlg_comboTargetType_SelectedIndexChanged_To_export_a_scheduled_list_y" +
                        "ou_must_first_import_results_for_all_peptides_in_the_document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ma&amp;x concurrent precursors:.
        /// </summary>
        public static string ExportMethodDlg_CONCUR_PREC_TXT {
            get {
                return ResourceManager.GetString("ExportMethodDlg_CONCUR_PREC_TXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ma&amp;x concurrent transitions:.
        /// </summary>
        public static string ExportMethodDlg_CONCUR_TRANS_TXT {
            get {
                return ResourceManager.GetString("ExportMethodDlg_CONCUR_TRANS_TXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Dwell time (ms):.
        /// </summary>
        public static string ExportMethodDlg_DWELL_TIME_TXT {
            get {
                return ResourceManager.GetString("ExportMethodDlg_DWELL_TIME_TXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Isolation List.
        /// </summary>
        public static string ExportMethodDlg_ExportMethodDlg_Export_Isolation_List {
            get {
                return ResourceManager.GetString("ExportMethodDlg_ExportMethodDlg_Export_Isolation_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Transition List.
        /// </summary>
        public static string ExportMethodDlg_ExportMethodDlg_Export_Transition_List {
            get {
                return ResourceManager.GetString("ExportMethodDlg_ExportMethodDlg_Export_Transition_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A template file is required to export a method..
        /// </summary>
        public static string ExportMethodDlg_OkDialog_A_template_file_is_required_to_export_a_method {
            get {
                return ResourceManager.GetString("ExportMethodDlg_OkDialog_A_template_file_is_required_to_export_a_method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to continue?.
        /// </summary>
        public static string ExportMethodDlg_OkDialog_Are_you_sure_you_want_to_continue {
            get {
                return ResourceManager.GetString("ExportMethodDlg_OkDialog_Are_you_sure_you_want_to_continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to continue?.
        /// </summary>
        public static string ExportMethodDlg_OkDialog_Are_you_sure_you_want_to_continue_ {
            get {
                return ResourceManager.GetString("ExportMethodDlg_OkDialog_Are_you_sure_you_want_to_continue_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collision Energy:.
        /// </summary>
        public static string ExportMethodDlg_OkDialog_Collision_Energy {
            get {
                return ResourceManager.GetString("ExportMethodDlg_OkDialog_Collision_Energy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decluster Potential:.
        /// </summary>
        public static string ExportMethodDlg_OkDialog_Declustering_Potential {
            get {
                return ResourceManager.GetString("ExportMethodDlg_OkDialog_Declustering_Potential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export {0} Method.
        /// </summary>
        public static string ExportMethodDlg_OkDialog_Export__0__Method {
            get {
                return ResourceManager.GetString("ExportMethodDlg_OkDialog_Export__0__Method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Isolation List.
        /// </summary>
        public static string ExportMethodDlg_OkDialog_Isolation_List {
            get {
                return ResourceManager.GetString("ExportMethodDlg_OkDialog_Isolation_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method File.
        /// </summary>
        public static string ExportMethodDlg_OkDialog_Method_File {
            get {
                return ResourceManager.GetString("ExportMethodDlg_OkDialog_Method_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string ExportMethodDlg_OkDialog_None {
            get {
                return ResourceManager.GetString("ExportMethodDlg_OkDialog_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string ExportMethodDlg_OkDialog_OK {
            get {
                return ResourceManager.GetString("ExportMethodDlg_OkDialog_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orbitrap.
        /// </summary>
        public static string ExportMethodDlg_OkDialog_Orbitrap {
            get {
                return ResourceManager.GetString("ExportMethodDlg_OkDialog_Orbitrap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide transition ranking information through imported results, a spectral library, or choose only one target transition per precursor..
        /// </summary>
        public static string ExportMethodDlg_OkDialog_Provide_transition_ranking_information_through_imported_results__a_spectral_library__or_choose_only_one_target_transition_per_precursor_ {
            get {
                return ResourceManager.GetString("ExportMethodDlg_OkDialog_Provide_transition_ranking_information_through_imported_" +
                        "results__a_spectral_library__or_choose_only_one_target_transition_per_precursor_" +
                        "", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The document does not contain all of the retention time standard peptides..
        /// </summary>
        public static string ExportMethodDlg_OkDialog_The_document_does_not_contain_all_of_the_retention_time_standard_peptides {
            get {
                return ResourceManager.GetString("ExportMethodDlg_OkDialog_The_document_does_not_contain_all_of_the_retention_time_" +
                        "standard_peptides", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The folder {0} does not appear to contain a Bruker TOF method template. The folder is expected to have a .m extension, and contain the file submethods.xml..
        /// </summary>
        public static string ExportMethodDlg_OkDialog_The_folder__0__does_not_appear_to_contain_a_Bruker_TOF_method_template___The_folder_is_expected_to_have_a__m_extension__and_contain_the_file_submethods_xml_ {
            get {
                return ResourceManager.GetString("ExportMethodDlg_OkDialog_The_folder__0__does_not_appear_to_contain_a_Bruker_TOF_m" +
                        "ethod_template___The_folder_is_expected_to_have_a__m_extension__and_contain_the_" +
                        "file_submethods_xml_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The folder {0} does not appear to contain an Agilent MassHunter 12 method template. The folder is expected to have a .m extension..
        /// </summary>
        public static string ExportMethodDlg_OkDialog_The_folder__0__does_not_appear_to_contain_an_Agilent_MassHunter_12_method_template__The_folder_is_expected_to_have_a__m_extension_ {
            get {
                return ResourceManager.GetString("ExportMethodDlg_OkDialog_The_folder__0__does_not_appear_to_contain_an_Agilent_Mas" +
                        "sHunter_12_method_template__The_folder_is_expected_to_have_a__m_extension_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The folder {0} does not appear to contain an Agilent QQQ method template. The folder is expected to have a .m extension, and contain the file qqqacqmethod.xsd..
        /// </summary>
        public static string ExportMethodDlg_OkDialog_The_folder__0__does_not_appear_to_contain_an_Agilent_QQQ_method_template_The_folder_is_expected_to_have_a_m_extension_and_contain_the_file_qqqacqmethod_xsd {
            get {
                return ResourceManager.GetString("ExportMethodDlg_OkDialog_The_folder__0__does_not_appear_to_contain_an_Agilent_QQQ" +
                        "_method_template_The_folder_is_expected_to_have_a_m_extension_and_contain_the_fi" +
                        "le_qqqacqmethod_xsd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The product mass analyzer type is not set to {0} in Transition Settings (under the Full Scan tab)..
        /// </summary>
        public static string ExportMethodDlg_OkDialog_The_product_mass_analyzer_type_is_not_set_to__0__in_Transition_Settings_under_the_Full_Scan_tab {
            get {
                return ResourceManager.GetString("ExportMethodDlg_OkDialog_The_product_mass_analyzer_type_is_not_set_to__0__in_Tran" +
                        "sition_Settings_under_the_Full_Scan_tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The settings for this document do not match the instrument type {0}:.
        /// </summary>
        public static string ExportMethodDlg_OkDialog_The_settings_for_this_document_do_not_match_the_instrument_type__0__ {
            get {
                return ResourceManager.GetString("ExportMethodDlg_OkDialog_The_settings_for_this_document_do_not_match_the_instrume" +
                        "nt_type__0__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The template file {0} does not exist..
        /// </summary>
        public static string ExportMethodDlg_OkDialog_The_template_file__0__does_not_exist {
            get {
                return ResourceManager.GetString("ExportMethodDlg_OkDialog_The_template_file__0__does_not_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The transition prediction settings for this document are set to use optimized values by transition..
        /// </summary>
        public static string ExportMethodDlg_OkDialog_The_transition_prediction_settings_for_this_document_are_set_to_use_optimized_values_by_transition_ {
            get {
                return ResourceManager.GetString("ExportMethodDlg_OkDialog_The_transition_prediction_settings_for_this_document_are" +
                        "_set_to_use_optimized_values_by_transition_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOF.
        /// </summary>
        public static string ExportMethodDlg_OkDialog_TOF {
            get {
                return ResourceManager.GetString("ExportMethodDlg_OkDialog_TOF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transition List.
        /// </summary>
        public static string ExportMethodDlg_OkDialog_Transition_List {
            get {
                return ResourceManager.GetString("ExportMethodDlg_OkDialog_Transition_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using optimized values by transition is invalid for this instrument type. Would you like to use optimized values by precursor instead?.
        /// </summary>
        public static string ExportMethodDlg_OkDialog_Using_optimized_values_by_transition_is_invalid_for_this_instrument_type__Would_you_like_to_use_optimized_values_by_precursor_instead_ {
            get {
                return ResourceManager.GetString("ExportMethodDlg_OkDialog_Using_optimized_values_by_transition_is_invalid_for_this" +
                        "_instrument_type__Would_you_like_to_use_optimized_values_by_precursor_instead_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to use the defaults instead?.
        /// </summary>
        public static string ExportMethodDlg_OkDialog_Would_you_like_to_use_the_defaults_instead {
            get {
                return ResourceManager.GetString("ExportMethodDlg_OkDialog_Would_you_like_to_use_the_defaults_instead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are missing any optimized compensation voltages for the following:.
        /// </summary>
        public static string ExportMethodDlg_OkDialog_You_are_missing_any_optimized_compensation_voltages_for_the_following_ {
            get {
                return ResourceManager.GetString("ExportMethodDlg_OkDialog_You_are_missing_any_optimized_compensation_voltages_for_" +
                        "the_following_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are missing compensation voltages for the following:.
        /// </summary>
        public static string ExportMethodDlg_OkDialog_You_are_missing_compensation_voltages_for_the_following_ {
            get {
                return ResourceManager.GetString("ExportMethodDlg_OkDialog_You_are_missing_compensation_voltages_for_the_following_" +
                        "", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are missing medium tune optimized compensation voltages for the following:.
        /// </summary>
        public static string ExportMethodDlg_OkDialog_You_are_missing_medium_tune_optimized_compensation_voltages_for_the_following_ {
            get {
                return ResourceManager.GetString("ExportMethodDlg_OkDialog_You_are_missing_medium_tune_optimized_compensation_volta" +
                        "ges_for_the_following_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can set explicit compensation voltages for these, or add their values to a document optimization library in Transition Settings under the Prediction tab..
        /// </summary>
        public static string ExportMethodDlg_OkDialog_You_can_set_explicit_compensation_voltages_for_these__or_add_their_values_to_a_document_optimization_library_in_Transition_Settings_under_the_Prediction_tab_ {
            get {
                return ResourceManager.GetString("ExportMethodDlg_OkDialog_You_can_set_explicit_compensation_voltages_for_these__or" +
                        "_add_their_values_to_a_document_optimization_library_in_Transition_Settings_unde" +
                        "r_the_Prediction_tab_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will not be able to use retention time prediction with acquired results..
        /// </summary>
        public static string ExportMethodDlg_OkDialog_You_will_not_be_able_to_use_retention_time_prediction_with_acquired_results {
            get {
                return ResourceManager.GetString("ExportMethodDlg_OkDialog_You_will_not_be_able_to_use_retention_time_prediction_wi" +
                        "th_acquired_results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ma&amp;x precursors per sample injection:.
        /// </summary>
        public static string ExportMethodDlg_PREC_PER_SAMPLE_INJ_TXT {
            get {
                return ResourceManager.GetString("ExportMethodDlg_PREC_PER_SAMPLE_INJ_TXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run &amp;duration (min):.
        /// </summary>
        public static string ExportMethodDlg_RUN_DURATION_TXT {
            get {
                return ResourceManager.GetString("ExportMethodDlg_RUN_DURATION_TXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduled.
        /// </summary>
        public static string ExportMethodDlg_SetMethodType_Scheduled {
            get {
                return ResourceManager.GetString("ExportMethodDlg_SetMethodType_Scheduled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard.
        /// </summary>
        public static string ExportMethodDlg_SetMethodType_Standard {
            get {
                return ResourceManager.GetString("ExportMethodDlg_SetMethodType_Standard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple methods is not yet supported for {0}..
        /// </summary>
        public static string ExportMethodDlg_StrategyCheckChanged_Multiple_methods_is_not_yet_supported_for__0__ {
            get {
                return ResourceManager.GetString("ExportMethodDlg_StrategyCheckChanged_Multiple_methods_is_not_yet_supported_for__0" +
                        "__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only one method can be exported in DIA mode..
        /// </summary>
        public static string ExportMethodDlg_StrategyCheckChanged_Only_one_method_can_be_exported_in_DIA_mode {
            get {
                return ResourceManager.GetString("ExportMethodDlg_StrategyCheckChanged_Only_one_method_can_be_exported_in_DIA_mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ma&amp;x transitions per sample injection:.
        /// </summary>
        public static string ExportMethodDlg_TRANS_PER_SAMPLE_INJ_TXT {
            get {
                return ResourceManager.GetString("ExportMethodDlg_TRANS_PER_SAMPLE_INJ_TXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absolute relative intensity threshold value..
        /// </summary>
        public static string ExportMethodDlg_UpdateThermoSureQuantControls_Absolute_relative_intensity_threshold_value_ {
            get {
                return ResourceManager.GetString("ExportMethodDlg_UpdateThermoSureQuantControls_Absolute_relative_intensity_thresho" +
                        "ld_value_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentage of peak max height to use as intensity threshold..
        /// </summary>
        public static string ExportMethodDlg_UpdateThermoSureQuantControls_Percentage_of_peak_max_height_to_use_as_intensity_threshold_ {
            get {
                return ResourceManager.GetString("ExportMethodDlg_UpdateThermoSureQuantControls_Percentage_of_peak_max_height_to_us" +
                        "e_as_intensity_threshold_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The precursor {0} for {1} has {2} transitions, which exceeds the current maximum {3}..
        /// </summary>
        public static string ExportMethodDlg_ValidatePrecursorFit_The_precursor__0__for__1__has__2__transitions__which_exceeds_the_current_maximum__3__ {
            get {
                return ResourceManager.GetString("ExportMethodDlg_ValidatePrecursorFit_The_precursor__0__for__1__has__2__transition" +
                        "s__which_exceeds_the_current_maximum__3__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The precursor {0} for {1} requires {2} transitions to optimize, which exceeds the current maximum {3}..
        /// </summary>
        public static string ExportMethodDlg_ValidatePrecursorFit_The_precursor__0__for__1__requires__2__transitions_to_optimize__which_exceeds_the_current_maximum__3__ {
            get {
                return ResourceManager.GetString("ExportMethodDlg_ValidatePrecursorFit_The_precursor__0__for__1__requires__2__trans" +
                        "itions_to_optimize__which_exceeds_the_current_maximum__3__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must contain a value..
        /// </summary>
        public static string ExportMethodDlg_ValidateSettings__0__must_contain_a_value {
            get {
                return ResourceManager.GetString("ExportMethodDlg_ValidateSettings__0__must_contain_a_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The instrument type {0} does not support triggered acquisition..
        /// </summary>
        public static string ExportMethodDlg_VerifySchedulingAllowed_The_instrument_type__0__does_not_support_triggered_acquisition_ {
            get {
                return ResourceManager.GetString("ExportMethodDlg_VerifySchedulingAllowed_The_instrument_type__0__does_not_support_" +
                        "triggered_acquisition_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current document does not appear to have enough transitions to require multiple injections.
        ///Are you sure you want to continue?.
        /// </summary>
        public static string ImportResultsDlg_CanCreateMultiInjectionMethods_The_current_document_does_not_appear_to_have_enough_transitions_to_require_multiple_injections {
            get {
                return ResourceManager.GetString("ImportResultsDlg_CanCreateMultiInjectionMethods_The_current_document_does_not_app" +
                        "ear_to_have_enough_transitions_to_require_multiple_injections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results found in the folder {0}..
        /// </summary>
        public static string ImportResultsDlg_GetDataSourcePathsDir_No_results_found_in_the_folder__0__ {
            get {
                return ResourceManager.GetString("ImportResultsDlg_GetDataSourcePathsDir_No_results_found_in_the_folder__0__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results Directory.
        /// </summary>
        public static string ImportResultsDlg_GetDataSourcePathsDir_Results_Directory {
            get {
                return ResourceManager.GetString("ImportResultsDlg_GetDataSourcePathsDir_Results_Directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Results Files.
        /// </summary>
        public static string ImportResultsDlg_GetDataSourcePathsFile_Import_Results_Files {
            get {
                return ResourceManager.GetString("ImportResultsDlg_GetDataSourcePathsFile_Import_Results_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred attempting to read sample information from the file {0}..
        /// </summary>
        public static string ImportResultsDlg_GetWiffSubPaths_An_error_occurred_attempting_to_read_sample_information_from_the_file__0__ {
            get {
                return ResourceManager.GetString("ImportResultsDlg_GetWiffSubPaths_An_error_occurred_attempting_to_read_sample_info" +
                        "rmation_from_the_file__0__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading sample names from {0}.
        /// </summary>
        public static string ImportResultsDlg_GetWiffSubPaths_Reading_sample_names_from__0__ {
            get {
                return ResourceManager.GetString("ImportResultsDlg_GetWiffSubPaths_Reading_sample_names_from__0__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample Names.
        /// </summary>
        public static string ImportResultsDlg_GetWiffSubPaths_Sample_Names {
            get {
                return ResourceManager.GetString("ImportResultsDlg_GetWiffSubPaths_Sample_Names", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file may be corrupted, missing, or the correct libraries may not be installed..
        /// </summary>
        public static string ImportResultsDlg_GetWiffSubPaths_The_file_may_be_corrupted_missing_or_the_correct_libraries_may_not_be_installed {
            get {
                return ResourceManager.GetString("ImportResultsDlg_GetWiffSubPaths_The_file_may_be_corrupted_missing_or_the_correct" +
                        "_libraries_may_not_be_installed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A result name may not contain any of the characters &apos;{0}&apos;..
        /// </summary>
        public static string ImportResultsDlg_OkDialog_A_result_name_may_not_contain_any_of_the_characters___0___ {
            get {
                return ResourceManager.GetString("ImportResultsDlg_OkDialog_A_result_name_may_not_contain_any_of_the_characters___0" +
                        "___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified name already exists for this document..
        /// </summary>
        public static string ImportResultsDlg_OkDialog_The_specified_name_already_exists_for_this_document {
            get {
                return ResourceManager.GetString("ImportResultsDlg_OkDialog_The_specified_name_already_exists_for_this_document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select an existing set of results to which to append new data..
        /// </summary>
        public static string ImportResultsDlg_OkDialog_You_must_select_an_existing_set_of_results_to_which_to_append_new_data {
            get {
                return ResourceManager.GetString("ImportResultsDlg_OkDialog_You_must_select_an_existing_set_of_results_to_which_to_" +
                        "append_new_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The files you have chosen have a common prefix and suffix.
        ///Would you like to remove some or all of the prefix or suffix to shorten the names used in Skyline?.
        /// </summary>
        public static string ImportResultsNameDlg_CommonPrefix_and_Suffix {
            get {
                return ResourceManager.GetString("ImportResultsNameDlg_CommonPrefix_and_Suffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The files you have chosen have a common suffix.
        ///Would you like to remove some or all of this suffix to shorten the names used in Skyline?.
        /// </summary>
        public static string ImportResultsNameDlg_CommonSuffix {
            get {
                return ResourceManager.GetString("ImportResultsNameDlg_CommonSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text &apos;{0}&apos; is not a prefix of the files chosen..
        /// </summary>
        public static string ImportResultsNameDlg_OkDialog_The_text__0__is_not_a_prefix_of_the_files_chosen {
            get {
                return ResourceManager.GetString("ImportResultsNameDlg_OkDialog_The_text__0__is_not_a_prefix_of_the_files_chosen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text &apos;{0}&apos; is not a suffix of the files chosen..
        /// </summary>
        public static string ImportResultsNameDlg_OkDialog_The_text__0__is_not_a_suffix_of_the_files_chosen {
            get {
                return ResourceManager.GetString("ImportResultsNameDlg_OkDialog_The_text__0__is_not_a_suffix_of_the_files_chosen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for errors....
        /// </summary>
        public static string ImportTransitionListColumnSelectDlg_CheckForErrors_Checking_for_errors___ {
            get {
                return ResourceManager.GetString("ImportTransitionListColumnSelectDlg_CheckForErrors_Checking_for_errors___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Molecular Formula and/or Precursor m/z.
        /// </summary>
        public static string ImportTransitionListColumnSelectDlg_CheckMoleculeColumns_Molecular_Formula_and_or_Precursor_m_z {
            get {
                return ResourceManager.GetString("ImportTransitionListColumnSelectDlg_CheckMoleculeColumns_Molecular_Formula_and_or" +
                        "_Precursor_m_z", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precursor Adduct and/or Precursor Charge.
        /// </summary>
        public static string ImportTransitionListColumnSelectDlg_CheckMoleculeColumns_Precursor_Adduct_and_or_Precursor_Charge {
            get {
                return ResourceManager.GetString("ImportTransitionListColumnSelectDlg_CheckMoleculeColumns_Precursor_Adduct_and_or_" +
                        "Precursor_Charge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column {0}.
        /// </summary>
        public static string ImportTransitionListColumnSelectDlg_DisplayData_Column__0_ {
            get {
                return ResourceManager.GetString("ImportTransitionListColumnSelectDlg_DisplayData_Column__0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The input text did not appear to contain column headers. Use the dropdown control to assign column meanings for import..
        /// </summary>
        public static string ImportTransitionListColumnSelectDlg_DisplayData_The_input_text_did_not_appear_to_contain_column_headers__Use_the_dropdown_control_to_assign_column_meanings_for_import_ {
            get {
                return ResourceManager.GetString("ImportTransitionListColumnSelectDlg_DisplayData_The_input_text_did_not_appear_to_" +
                        "contain_column_headers__Use_the_dropdown_control_to_assign_column_meanings_for_i" +
                        "mport_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This column is labeled with the header &apos;{0}&apos; in the input text. Use the dropdown control to assign its meaning for import..
        /// </summary>
        public static string ImportTransitionListColumnSelectDlg_DisplayData_This_column_is_labeled_with_the_header___0___in_the_input_text__Use_the_dropdown_control_to_assign_its_meaning_for_import_ {
            get {
                return ResourceManager.GetString("ImportTransitionListColumnSelectDlg_DisplayData_This_column_is_labeled_with_the_h" +
                        "eader___0___in_the_input_text__Use_the_dropdown_control_to_assign_its_meaning_fo" +
                        "r_import_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Assay Library: Identify Columns.
        /// </summary>
        public static string ImportTransitionListColumnSelectDlg_Import_Assay_Library__Identify_Columns {
            get {
                return ResourceManager.GetString("ImportTransitionListColumnSelectDlg_Import_Assay_Library__Identify_Columns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iRT.
        /// </summary>
        public static string ImportTransitionListColumnSelectDlg_PopulateComboBoxes_iRT {
            get {
                return ResourceManager.GetString("ImportTransitionListColumnSelectDlg_PopulateComboBoxes_iRT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library Intensity.
        /// </summary>
        public static string ImportTransitionListColumnSelectDlg_PopulateComboBoxes_Library_Intensity {
            get {
                return ResourceManager.GetString("ImportTransitionListColumnSelectDlg_PopulateComboBoxes_Library_Intensity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protein Description.
        /// </summary>
        public static string ImportTransitionListColumnSelectDlg_PopulateComboBoxes_Protein_Description {
            get {
                return ResourceManager.GetString("ImportTransitionListColumnSelectDlg_PopulateComboBoxes_Protein_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associate Proteins.
        /// </summary>
        public static string ImportTransitionListColumnSelectDlg_ResolveMatchedProteins_Associate_Proteins {
            get {
                return ResourceManager.GetString("ImportTransitionListColumnSelectDlg_ResolveMatchedProteins_Associate_Proteins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A transition contained an error..
        /// </summary>
        public static string ImportTransitionListErrorDlg_ImportTransitionListErrorDlg_A_transition_contained_an_error_ {
            get {
                return ResourceManager.GetString("ImportTransitionListErrorDlg_ImportTransitionListErrorDlg_A_transition_contained_" +
                        "an_error_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A transition contained an error. Skip this transition and import the rest?.
        /// </summary>
        public static string ImportTransitionListErrorDlg_ImportTransitionListErrorDlg_A_transition_contained_an_error__Skip_this_transition_and_import_the_rest_ {
            get {
                return ResourceManager.GetString("ImportTransitionListErrorDlg_ImportTransitionListErrorDlg_A_transition_contained_" +
                        "an_error__Skip_this_transition_and_import_the_rest_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All {0} transitions contained errors.  Please check the transition list for errors and try importing again..
        /// </summary>
        public static string ImportTransitionListErrorDlg_ImportTransitionListErrorDlg_All__0__transitions_contained_errors___Please_check_the_transition_list_for_errors_and_try_importing_again_ {
            get {
                return ResourceManager.GetString("ImportTransitionListErrorDlg_ImportTransitionListErrorDlg_All__0__transitions_con" +
                        "tained_errors___Please_check_the_transition_list_for_errors_and_try_importing_ag" +
                        "ain_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The imported transition contains an error. Please check the transition list and the Skyline settings and try importing again..
        /// </summary>
        public static string ImportTransitionListErrorDlg_ImportTransitionListErrorDlg_The_imported_transition_contains_an_error__Please_check_the_transition_list_and_the_Skyline_settings_and_try_importing_again_ {
            get {
                return ResourceManager.GetString("ImportTransitionListErrorDlg_ImportTransitionListErrorDlg_The_imported_transition" +
                        "_contains_an_error__Please_check_the_transition_list_and_the_Skyline_settings_an" +
                        "d_try_importing_again_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All results must be completely imported before any can be re-imported..
        /// </summary>
        public static string ManageResultsDlg_ReimportResults_All_results_must_be_completely_imported_before_any_can_be_re_imported {
            get {
                return ResourceManager.GetString("ManageResultsDlg_ReimportResults_All_results_must_be_completely_imported_before_a" +
                        "ny_can_be_re_imported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find the following files, either in their original locations or in the folder of the current document:.
        /// </summary>
        public static string ManageResultsDlg_ReimportResults_Unable_to_find_the_following_files_either_in_their_original_locations_or_in_the_folder_of_the_current_document {
            get {
                return ResourceManager.GetString("ManageResultsDlg_ReimportResults_Unable_to_find_the_following_files_either_in_the" +
                        "ir_original_locations_or_in_the_folder_of_the_current_document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The cache file has not been loaded yet..
        /// </summary>
        public static string MinimizeResultsDlg_ChromCacheMinimizer_The_cache_file_has_not_been_loaded_yet {
            get {
                return ResourceManager.GetString("MinimizeResultsDlg_ChromCacheMinimizer_The_cache_file_has_not_been_loaded_yet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All results must be completely imported before any can be minimized..
        /// </summary>
        public static string MinimizeResultsDlg_Minimize_All_results_must_be_completely_imported_before_any_can_be_minimized {
            get {
                return ResourceManager.GetString("MinimizeResultsDlg_Minimize_All_results_must_be_completely_imported_before_any_ca" +
                        "n_be_minimized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not chosen any options to minimize your cache file. Are you sure you want to continue?.
        /// </summary>
        public static string MinimizeResultsDlg_Minimize_You_have_not_chosen_any_options_to_minimize_your_cache_file_Are_you_sure_you_want_to_continue {
            get {
                return ResourceManager.GetString("MinimizeResultsDlg_Minimize_You_have_not_chosen_any_options_to_minimize_your_cach" +
                        "e_file_Are_you_sure_you_want_to_continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred while saving the data cache file {0}..
        /// </summary>
        public static string MinimizeResultsDlg_MinimizeToFile_An_unexpected_error_occurred_while_saving_the_data_cache_file__0__ {
            get {
                return ResourceManager.GetString("MinimizeResultsDlg_MinimizeToFile_An_unexpected_error_occurred_while_saving_the_d" +
                        "ata_cache_file__0__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving new cache file.
        /// </summary>
        public static string MinimizeResultsDlg_MinimizeToFile_Saving_new_cache_file {
            get {
                return ResourceManager.GetString("MinimizeResultsDlg_MinimizeToFile_Saving_new_cache_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The noise time limit must be a positive decimal number..
        /// </summary>
        public static string MinimizeResultsDlg_tbxNoiseTimeRange_Leave_The_noise_time_limit_must_be_a_positive_decimal_number {
            get {
                return ResourceManager.GetString("MinimizeResultsDlg_tbxNoiseTimeRange_Leave_The_noise_time_limit_must_be_a_positiv" +
                        "e_decimal_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The noise time limit must be a valid decimal number..
        /// </summary>
        public static string MinimizeResultsDlg_tbxNoiseTimeRange_Leave_The_noise_time_limit_must_be_a_valid_decimal_number {
            get {
                return ResourceManager.GetString("MinimizeResultsDlg_tbxNoiseTimeRange_Leave_The_noise_time_limit_must_be_a_valid_d" +
                        "ecimal_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export mProphet Features.
        /// </summary>
        public static string MProphetFeaturesDlg_OkDialog_Export_mProphet_Features {
            get {
                return ResourceManager.GetString("MProphetFeaturesDlg_OkDialog_Export_mProphet_Features", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed attempting to save mProphet features to {0}..
        /// </summary>
        public static string MProphetFeaturesDlg_OkDialog_Failed_attempting_to_save_mProphet_features_to__0__ {
            get {
                return ResourceManager.GetString("MProphetFeaturesDlg_OkDialog_Failed_attempting_to_save_mProphet_features_to__0__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mProphet Feature Files.
        /// </summary>
        public static string MProphetFeaturesDlg_OkDialog_mProphet_Feature_Files {
            get {
                return ResourceManager.GetString("MProphetFeaturesDlg_OkDialog_mProphet_Feature_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To export MProphet features first train an MProphet model..
        /// </summary>
        public static string MProphetFeaturesDlg_OkDialog_To_export_MProphet_features_first_train_an_MProphet_model_ {
            get {
                return ResourceManager.GetString("MProphetFeaturesDlg_OkDialog_To_export_MProphet_features_first_train_an_MProphet_" +
                        "model_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select one or more data sources..
        /// </summary>
        public static string OpenDataSourceDialog_Open_Please_select_one_or_more_data_sources {
            get {
                return ResourceManager.GetString("OpenDataSourceDialog_Open_Please_select_one_or_more_data_sources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any spectra format.
        /// </summary>
        public static string OpenDataSourceDialog_OpenDataSourceDialog_Any_spectra_format {
            get {
                return ResourceManager.GetString("OpenDataSourceDialog_OpenDataSourceDialog_Any_spectra_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desktop.
        /// </summary>
        public static string OpenDataSourceDialog_OpenDataSourceDialog_Desktop {
            get {
                return ResourceManager.GetString("OpenDataSourceDialog_OpenDataSourceDialog_Desktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Computer.
        /// </summary>
        public static string OpenDataSourceDialog_OpenDataSourceDialog_My_Computer {
            get {
                return ResourceManager.GetString("OpenDataSourceDialog_OpenDataSourceDialog_My_Computer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Documents.
        /// </summary>
        public static string OpenDataSourceDialog_OpenDataSourceDialog_My_Documents {
            get {
                return ResourceManager.GetString("OpenDataSourceDialog_OpenDataSourceDialog_My_Documents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote Accounts.
        /// </summary>
        public static string OpenDataSourceDialog_OpenDataSourceDialog_Remote_Accounts {
            get {
                return ResourceManager.GetString("OpenDataSourceDialog_OpenDataSourceDialog_Remote_Accounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to access failure.
        /// </summary>
        public static string OpenDataSourceDialog_populateComboBoxFromDirectory_access_failure {
            get {
                return ResourceManager.GetString("OpenDataSourceDialog_populateComboBoxFromDirectory_access_failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Drive.
        /// </summary>
        public static string OpenDataSourceDialog_populateComboBoxFromDirectory_Local_Drive {
            get {
                return ResourceManager.GetString("OpenDataSourceDialog_populateComboBoxFromDirectory_Local_Drive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network Share.
        /// </summary>
        public static string OpenDataSourceDialog_populateComboBoxFromDirectory_Network_Share {
            get {
                return ResourceManager.GetString("OpenDataSourceDialog_populateComboBoxFromDirectory_Network_Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optical Drive.
        /// </summary>
        public static string OpenDataSourceDialog_populateComboBoxFromDirectory_Optical_Drive {
            get {
                return ResourceManager.GetString("OpenDataSourceDialog_populateComboBoxFromDirectory_Optical_Drive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removable Drive.
        /// </summary>
        public static string OpenDataSourceDialog_populateComboBoxFromDirectory_Removable_Drive {
            get {
                return ResourceManager.GetString("OpenDataSourceDialog_populateComboBoxFromDirectory_Removable_Drive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to access failure.
        /// </summary>
        public static string OpenDataSourceDialog_populateListViewFromDirectory_access_failure {
            get {
                return ResourceManager.GetString("OpenDataSourceDialog_populateListViewFromDirectory_access_failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred attempting to retrieve the contents of this directory..
        /// </summary>
        public static string OpenDataSourceDialog_populateListViewFromDirectory_An_error_occurred_attempting_to_retrieve_the_contents_of_this_directory {
            get {
                return ResourceManager.GetString("OpenDataSourceDialog_populateListViewFromDirectory_An_error_occurred_attempting_t" +
                        "o_retrieve_the_contents_of_this_directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Drive.
        /// </summary>
        public static string OpenDataSourceDialog_populateListViewFromDirectory_Local_Drive {
            get {
                return ResourceManager.GetString("OpenDataSourceDialog_populateListViewFromDirectory_Local_Drive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network Share.
        /// </summary>
        public static string OpenDataSourceDialog_populateListViewFromDirectory_Network_Share {
            get {
                return ResourceManager.GetString("OpenDataSourceDialog_populateListViewFromDirectory_Network_Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optical Drive.
        /// </summary>
        public static string OpenDataSourceDialog_populateListViewFromDirectory_Optical_Drive {
            get {
                return ResourceManager.GetString("OpenDataSourceDialog_populateListViewFromDirectory_Optical_Drive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removable Drive.
        /// </summary>
        public static string OpenDataSourceDialog_populateListViewFromDirectory_Removable_Drive {
            get {
                return ResourceManager.GetString("OpenDataSourceDialog_populateListViewFromDirectory_Removable_Drive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry.
        /// </summary>
        public static string OpenDataSourceDialog_populateListViewFromDirectory_Retry {
            get {
                return ResourceManager.GetString("OpenDataSourceDialog_populateListViewFromDirectory_Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue peak boundary import ignoring these charge states?.
        /// </summary>
        public static string PeakBoundaryImporter_UnrecognizedPeptidesCancel_Continue_peak_boundary_import_ignoring_these_charge_states_ {
            get {
                return ResourceManager.GetString("PeakBoundaryImporter_UnrecognizedPeptidesCancel_Continue_peak_boundary_import_ign" +
                        "oring_these_charge_states_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue peak boundary import ignoring this charge state?.
        /// </summary>
        public static string PeakBoundaryImporter_UnrecognizedPeptidesCancel_Continue_peak_boundary_import_ignoring_this_charge_state_ {
            get {
                return ResourceManager.GetString("PeakBoundaryImporter_UnrecognizedPeptidesCancel_Continue_peak_boundary_import_ign" +
                        "oring_this_charge_state_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following {0} peptide, file, and charge state combinations were not recognized:.
        /// </summary>
        public static string PeakBoundaryImporter_UnrecognizedPeptidesCancel_The_following__0__peptide__file__and_charge_state_combinations_were_not_recognized_ {
            get {
                return ResourceManager.GetString("PeakBoundaryImporter_UnrecognizedPeptidesCancel_The_following__0__peptide__file__" +
                        "and_charge_state_combinations_were_not_recognized_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following peptide, file, and charge state combination was not recognized:.
        /// </summary>
        public static string PeakBoundaryImporter_UnrecognizedPeptidesCancel_The_following_peptide__file__and_charge_state_combination_was_not_recognized_ {
            get {
                return ResourceManager.GetString("PeakBoundaryImporter_UnrecognizedPeptidesCancel_The_following_peptide__file__and_" +
                        "charge_state_combination_was_not_recognized_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error retrieving server folders:.
        /// </summary>
        public static string PublishDocumentDlg_addSubFolders_Error_retrieving_server_folders {
            get {
                return ResourceManager.GetString("PublishDocumentDlg_addSubFolders_Error_retrieving_server_folders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skyline Shared Documents.
        /// </summary>
        public static string PublishDocumentDlg_btnBrowse_Click_Skyline_Shared_Documents {
            get {
                return ResourceManager.GetString("PublishDocumentDlg_btnBrowse_Click_Skyline_Shared_Documents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Document.
        /// </summary>
        public static string PublishDocumentDlg_btnBrowse_Click_Upload_Document {
            get {
                return ResourceManager.GetString("PublishDocumentDlg_btnBrowse_Click_Upload_Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving information from servers.
        /// </summary>
        public static string PublishDocumentDlg_PublishDocumentDlg_Load_Retrieving_information_on_servers {
            get {
                return ResourceManager.GetString("PublishDocumentDlg_PublishDocumentDlg_Load_Retrieving_information_on_servers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed attempting to retrieve information from the following servers:.
        /// </summary>
        public static string PublishDocumentDlg_PublishDocumentDlgLoad_Failed_attempting_to_retrieve_information_from_the_following_servers_ {
            get {
                return ResourceManager.GetString("PublishDocumentDlg_PublishDocumentDlgLoad_Failed_attempting_to_retrieve_informati" +
                        "on_from_the_following_servers_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to Tools &gt; Options &gt; Panorama tab to update the username and password..
        /// </summary>
        public static string PublishDocumentDlg_PublishDocumentDlgLoad_Go_to_Tools___Options___Panorama_tab_to_update_the_username_and_password_ {
            get {
                return ResourceManager.GetString("PublishDocumentDlg_PublishDocumentDlgLoad_Go_to_Tools___Options___Panorama_tab_to" +
                        "_update_the_username_and_password_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error obtaining server information..
        /// </summary>
        public static string PublishDocumentDlg_UploadSharedZipFile_Error_obtaining_server_information {
            get {
                return ResourceManager.GetString("PublishDocumentDlg_UploadSharedZipFile_Error_obtaining_server_information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please use a different name..
        /// </summary>
        public static string RenameResultDlg_OkDialog_Please_use_a_different_name {
            get {
                return ResourceManager.GetString("RenameResultDlg_OkDialog_Please_use_a_different_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name {0} is already in use..
        /// </summary>
        public static string RenameResultDlg_ReplicateName_The_name__0__is_already_in_use {
            get {
                return ResourceManager.GetString("RenameResultDlg_ReplicateName_The_name__0__is_already_in_use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All results must be completely imported before they can be re-scored..
        /// </summary>
        public static string RescoreResultsDlg_Rescore_All_results_must_be_completely_imported_before_they_can_be_re_scored_ {
            get {
                return ResourceManager.GetString("RescoreResultsDlg_Rescore_All_results_must_be_completely_imported_before_they_can" +
                        "_be_re_scored_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are not results in this document.
        /// </summary>
        public static string RescoreResultsDlg_Rescore_There_are_not_results_in_this_document {
            get {
                return ResourceManager.GetString("RescoreResultsDlg_Rescore_There_are_not_results_in_this_document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In certain cases, you may want to have Skyline re-calculate peaks and re-score them based on the existing chromatogram data. Chromatograms will not be re-imported from raw data files, but peak integration information may change..
        /// </summary>
        public static string RescoreResultsDlg_RescoreResultsDlg_In_certain_cases__you_may_want_to_have_Skyline_re_calculate_peaks_and_re_score_them_based_on_the_existing_chromatogram_data___Chromatograms_will_not_be_re_imported_from_raw_data_files__but_peak_integration_information_may_change_ {
            get {
                return ResourceManager.GetString(@"RescoreResultsDlg_RescoreResultsDlg_In_certain_cases__you_may_want_to_have_Skyline_re_calculate_peaks_and_re_score_them_based_on_the_existing_chromatogram_data___Chromatograms_will_not_be_re_imported_from_raw_data_files__but_peak_integration_information_may_change_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The replicate {0} contains peptides without enough information to rank transitions for triggered acquisition..
        /// </summary>
        public static string SchedulingOptionsDlg_OkDialog_The_replicate__0__contains_peptides_without_enough_information_to_rank_transitions_for_triggered_acquisition_ {
            get {
                return ResourceManager.GetString("SchedulingOptionsDlg_OkDialog_The_replicate__0__contains_peptides_without_enough_" +
                        "information_to_rank_transitions_for_triggered_acquisition_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using trends in scheduling requires at least {0} replicates..
        /// </summary>
        public static string SchedulingOptionsDlg_TrendsError_Using_trends_in_scheduling_requires_at_least__0__replicates {
            get {
                return ResourceManager.GetString("SchedulingOptionsDlg_TrendsError_Using_trends_in_scheduling_requires_at_least__0_" +
                        "_replicates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to replace them?.
        /// </summary>
        public static string ShareListDlg_ImportFile_Do_you_want_to_replace_them {
            get {
                return ResourceManager.GetString("ShareListDlg_ImportFile_Do_you_want_to_replace_them", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following names already exist:.
        /// </summary>
        public static string ShareListDlg_ImportFile_The_following_names_already_exist {
            get {
                return ResourceManager.GetString("ShareListDlg_ImportFile_The_following_names_already_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name &apos;{0}&apos; already exists. Do you want to replace it?.
        /// </summary>
        public static string ShareListDlg_ImportFile_The_name__0__already_exists_Do_you_want_to_replace_it {
            get {
                return ResourceManager.GetString("ShareListDlg_ImportFile_The_name__0__already_exists_Do_you_want_to_replace_it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save {0}.
        /// </summary>
        public static string ShareListDlg_Label_Save__0__ {
            get {
                return ResourceManager.GetString("ShareListDlg_Label_Save__0__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the {0} you want to save to a file..
        /// </summary>
        public static string ShareListDlg_Label_Select_the__0__you_want_to_save_to_a_file {
            get {
                return ResourceManager.GetString("ShareListDlg_Label_Select_the__0__you_want_to_save_to_a_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skyline Settings.
        /// </summary>
        public static string ShareListDlg_ShareListDlg_Skyline_Settings {
            get {
                return ResourceManager.GetString("ShareListDlg_ShareListDlg_Skyline_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} transitions contained errors..
        /// </summary>
        public static string SkylineWindow_ImportMassList__0__transitions_contained_errors_ {
            get {
                return ResourceManager.GetString("SkylineWindow_ImportMassList__0__transitions_contained_errors_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} transitions contained errors. Skip these {0} transitions and import the rest?.
        /// </summary>
        public static string SkylineWindow_ImportMassList__0__transitions_contained_errors__Skip_these__0__transitions_and_import_the_rest_ {
            get {
                return ResourceManager.GetString("SkylineWindow_ImportMassList__0__transitions_contained_errors__Skip_these__0__tra" +
                        "nsitions_and_import_the_rest_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue peak boundary import ignoring these files?.
        /// </summary>
        public static string SkylineWindow_ImportPeakBoundaries_Continue_peak_boundary_import_ignoring_these_files_ {
            get {
                return ResourceManager.GetString("SkylineWindow_ImportPeakBoundaries_Continue_peak_boundary_import_ignoring_these_f" +
                        "iles_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue peak boundary import ignoring these peptides?.
        /// </summary>
        public static string SkylineWindow_ImportPeakBoundaries_Continue_peak_boundary_import_ignoring_these_peptides_ {
            get {
                return ResourceManager.GetString("SkylineWindow_ImportPeakBoundaries_Continue_peak_boundary_import_ignoring_these_p" +
                        "eptides_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following {0} file names in the peak boundaries file were not recognized:.
        /// </summary>
        public static string SkylineWindow_ImportPeakBoundaries_The_following__0__file_names_in_the_peak_boundaries_file_were_not_recognized_ {
            get {
                return ResourceManager.GetString("SkylineWindow_ImportPeakBoundaries_The_following__0__file_names_in_the_peak_bound" +
                        "aries_file_were_not_recognized_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following {0} peptides in the peak boundaries file were not recognized:.
        /// </summary>
        public static string SkylineWindow_ImportPeakBoundaries_The_following__0__peptides_in_the_peak_boundaries_file_were_not_recognized__ {
            get {
                return ResourceManager.GetString("SkylineWindow_ImportPeakBoundaries_The_following__0__peptides_in_the_peak_boundar" +
                        "ies_file_were_not_recognized__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading {0} from {1}.
        /// </summary>
        public static string SkypSupport_Download_Downloading__0__from__1_ {
            get {
                return ResourceManager.GetString("SkypSupport_Download_Downloading__0__from__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading Skyline Document Archive.
        /// </summary>
        public static string SkypSupport_Open_Downloading_Skyline_Document_Archive {
            get {
                return ResourceManager.GetString("SkypSupport_Open_Downloading_Skyline_Document_Archive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure opening skyp file..
        /// </summary>
        public static string SkypSupport_Open_Failure_opening_skyp_file_ {
            get {
                return ResourceManager.GetString("SkypSupport_Open_Failure_opening_skyp_file_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error downloading the Skyline document {0} from {1}..
        /// </summary>
        public static string SkypSupport_ShowDownloadError_There_was_an_error_downloading_the_Skyline_document__0__from__1__ {
            get {
                return ResourceManager.GetString("SkypSupport_ShowDownloadError_There_was_an_error_downloading_the_Skyline_document" +
                        "__0__from__1__", resourceCulture);
            }
        }
    }
}
