//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pwiz.Skyline.Util.Extensions {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ExtensionsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExtensionsResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("pwiz.Skyline.Util.Extensions.ExtensionsResources", typeof(ExtensionsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :.
        /// </summary>
        public static string ColonEndOfLine {
            get {
                return ResourceManager.GetString("ColonEndOfLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: {1}.
        /// </summary>
        public static string ColonSeparator {
            get {
                return ResourceManager.GetString("ColonSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average.
        /// </summary>
        public static string ExportStrategyExtension_LOCALIZED_VALUES_Average {
            get {
                return ResourceManager.GetString("ExportStrategyExtension_LOCALIZED_VALUES_Average", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monoisotopic.
        /// </summary>
        public static string ExportStrategyExtension_LOCALIZED_VALUES_Monoisotopic {
            get {
                return ResourceManager.GetString("ExportStrategyExtension_LOCALIZED_VALUES_Monoisotopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, line {1}..
        /// </summary>
        public static string LineColNumberedIoException_FormatMessage__0___line__1__ {
            get {
                return ResourceManager.GetString("LineColNumberedIoException_FormatMessage__0___line__1__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, line {1}, col {2}..
        /// </summary>
        public static string LineColNumberedIoException_FormatMessage__0___line__1___col__2__ {
            get {
                return ResourceManager.GetString("LineColNumberedIoException_FormatMessage__0___line__1___col__2__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV (Comma delimited).
        /// </summary>
        public static string TextUtil_DESCRIPTION_CSV_CSV__Comma_delimited_ {
            get {
                return ResourceManager.GetString("TextUtil_DESCRIPTION_CSV_CSV__Comma_delimited_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TSV (Tab delimited).
        /// </summary>
        public static string TextUtil_DESCRIPTION_TSV_TSV__Tab_delimited_ {
            get {
                return ResourceManager.GetString("TextUtil_DESCRIPTION_TSV_TSV__Tab_delimited_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Files.
        /// </summary>
        public static string TextUtil_FileDialogFiltersAll_All_Files {
            get {
                return ResourceManager.GetString("TextUtil_FileDialogFiltersAll_All_Files", resourceCulture);
            }
        }
    }
}
