//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pwiz.Osprey {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class OspreyResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OspreyResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("pwiz.Osprey.OspreyResources", typeof(OspreyResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} days.
        /// </summary>
        public static string AnalysisPipeline_FormatDuration__0__days {
            get {
                return ResourceManager.GetString("AnalysisPipeline_FormatDuration__0__days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} days {1} hours.
        /// </summary>
        public static string AnalysisPipeline_FormatDuration__0__days__1__hours {
            get {
                return ResourceManager.GetString("AnalysisPipeline_FormatDuration__0__days__1__hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} hours.
        /// </summary>
        public static string AnalysisPipeline_FormatDuration__0__hours {
            get {
                return ResourceManager.GetString("AnalysisPipeline_FormatDuration__0__hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} hours {1} minutes.
        /// </summary>
        public static string AnalysisPipeline_FormatDuration__0__hours__1__minutes {
            get {
                return ResourceManager.GetString("AnalysisPipeline_FormatDuration__0__hours__1__minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} minutes.
        /// </summary>
        public static string AnalysisPipeline_FormatDuration__0__minutes {
            get {
                return ResourceManager.GetString("AnalysisPipeline_FormatDuration__0__minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} minutes {1} seconds.
        /// </summary>
        public static string AnalysisPipeline_FormatDuration__0__minutes__1__seconds {
            get {
                return ResourceManager.GetString("AnalysisPipeline_FormatDuration__0__minutes__1__seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ms.
        /// </summary>
        public static string AnalysisPipeline_FormatDuration__0__ms {
            get {
                return ResourceManager.GetString("AnalysisPipeline_FormatDuration__0__ms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:F3} seconds.
        /// </summary>
        public static string AnalysisPipeline_FormatDuration__0__seconds {
            get {
                return ResourceManager.GetString("AnalysisPipeline_FormatDuration__0__seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysis complete in {0}.
        /// </summary>
        public static string AnalysisPipeline_Run_Analysis_complete_in__0_ {
            get {
                return ResourceManager.GetString("AnalysisPipeline_Run_Analysis_complete_in__0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pipeline failed: {0}.
        /// </summary>
        public static string AnalysisPipeline_Run_Pipeline_failed___0_ {
            get {
                return ResourceManager.GetString("AnalysisPipeline_Run_Pipeline_failed___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to record that task {0} completed {1}: {2}. A resume will redo this step..
        /// </summary>
        public static string AnalysisPipeline_WriteTaskSidecars_Failed_to_record_that_task__0__completed__1____2___A_resume_will_redo_this_step_ {
            get {
                return ResourceManager.GetString("AnalysisPipeline_WriteTaskSidecars_Failed_to_record_that_task__0__completed__1___" +
                        "_2___A_resume_will_redo_this_step_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applies To.
        /// </summary>
        public static string OspreyArgUsageProvider_AppliesToHeader_Applies_To {
            get {
                return ResourceManager.GetString("OspreyArgUsageProvider_AppliesToHeader_Applies_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument.
        /// </summary>
        public static string OspreyArgUsageProvider_ArgumentHeader_Argument {
            get {
                return ResourceManager.GetString("OspreyArgUsageProvider_ArgumentHeader_Argument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string OspreyArgUsageProvider_DescriptionHeader_Description {
            get {
                return ResourceManager.GetString("OspreyArgUsageProvider_DescriptionHeader_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory for the {0} cache (overrides {1}).
        /// </summary>
        public static string OspreyArgUsageProvider_GetDescription_cache_dir {
            get {
                return ResourceManager.GetString("OspreyArgUsageProvider_GetDescription_cache_dir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FDRBench 5-column pairing manifest (TSV), used with {0}.
        /// </summary>
        public static string OspreyArgUsageProvider_GetDescription_decoy_pairing_manifest {
            get {
                return ResourceManager.GetString("OspreyArgUsageProvider_GetDescription_decoy_pairing_manifest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trust decoys already in the spectral library instead of generating reverse decoys. Stops with an error if none are recognized..
        /// </summary>
        public static string OspreyArgUsageProvider_GetDescription_decoys_in_library {
            get {
                return ResourceManager.GetString("OspreyArgUsageProvider_GetDescription_decoys_in_library", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write developer diagnostic dump files, for comparison with the Rust implementation.
        /// </summary>
        public static string OspreyArgUsageProvider_GetDescription_diagnostics {
            get {
                return ResourceManager.GetString("OspreyArgUsageProvider_GetDescription_diagnostics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experiment-level FDR threshold (default: 0.01).
        /// </summary>
        public static string OspreyArgUsageProvider_GetDescription_experiment_fdr {
            get {
                return ResourceManager.GetString("OspreyArgUsageProvider_GetDescription_experiment_fdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FDR level (default: {0}).
        /// </summary>
        public static string OspreyArgUsageProvider_GetDescription_fdr_level {
            get {
                return ResourceManager.GetString("OspreyArgUsageProvider_GetDescription_fdr_level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FDR method (default: {0}).
        /// </summary>
        public static string OspreyArgUsageProvider_GetDescription_fdr_method {
            get {
                return ResourceManager.GetString("OspreyArgUsageProvider_GetDescription_fdr_method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write an FDRBench-compatible input TSV to this path. The level is taken from {0} (peptide; precursor and both emit precursor-level). Includes every reported target, i.e. the peptides actually written to the output, regardless of q-value, with the raw SVM discriminant as &apos;score&apos;, so FDRBench can compute true FDR via entrapment counting without truncation at Osprey&apos;s threshold..
        /// </summary>
        public static string OspreyArgUsageProvider_GetDescription_fdrbench {
            get {
                return ResourceManager.GetString("OspreyArgUsageProvider_GetDescription_fdrbench", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With {0}: which FDR pass to emit. 2 (default) = the second-pass results written to the blib (the FDR of what Osprey reports). 1 = the full first-pass pool, before it is filtered for the second pass (every scored target, regardless of q), with first-pass q-values, matching the FDRBench input of the original Rust Osprey (the assumption the second-pass output rests on). both = emit both in one run, writing the {0} path with .pass1 / .pass2 stem suffixes..
        /// </summary>
        public static string OspreyArgUsageProvider_GetDescription_fdrbench_pass {
            get {
                return ResourceManager.GetString("OspreyArgUsageProvider_GetDescription_fdrbench_pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With {0}: emit one row per (precursor, run) using run-level q-values (adds a &apos;run&apos; column). Default is one row per precursor using experiment-level q-values..
        /// </summary>
        public static string OspreyArgUsageProvider_GetDescription_fdrbench_per_run {
            get {
                return ResourceManager.GetString("OspreyArgUsageProvider_GetDescription_fdrbench_per_run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fragment m/z tolerance (default: 10).
        /// </summary>
        public static string OspreyArgUsageProvider_GetDescription_fragment_tolerance {
            get {
                return ResourceManager.GetString("OspreyArgUsageProvider_GetDescription_fragment_tolerance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fragment tolerance unit (default: {0}).
        /// </summary>
        public static string OspreyArgUsageProvider_GetDescription_fragment_unit {
            get {
                return ResourceManager.GetString("OspreyArgUsageProvider_GetDescription_fragment_unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show this help message ({0}).
        /// </summary>
        public static string OspreyArgUsageProvider_GetDescription_help {
            get {
                return ResourceManager.GetString("OspreyArgUsageProvider_GetDescription_help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input mzML files.
        /// </summary>
        public static string OspreyArgUsageProvider_GetDescription_input {
            get {
                return ResourceManager.GetString("OspreyArgUsageProvider_GetDescription_input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File of input paths, one per line (# comments ignored). Bounded alternative to a long {0} list..
        /// </summary>
        public static string OspreyArgUsageProvider_GetDescription_input_list {
            get {
                return ResourceManager.GetString("OspreyArgUsageProvider_GetDescription_input_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spectral library (.tsv, .blib).
        /// </summary>
        public static string OspreyArgUsageProvider_GetDescription_library {
            get {
                return ResourceManager.GetString("OspreyArgUsageProvider_GetDescription_library", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write all output to this file instead of stderr.
        /// </summary>
        public static string OspreyArgUsageProvider_GetDescription_log_file {
            get {
                return ResourceManager.GetString("OspreyArgUsageProvider_GetDescription_log_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefix each output line with managed and private memory in MB (pair with {0} for perfviz).
        /// </summary>
        public static string OspreyArgUsageProvider_GetDescription_memstamp {
            get {
                return ResourceManager.GetString("OspreyArgUsageProvider_GetDescription_memstamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write a self-contained interactive HTML report of the trained scoring model, FDR calibration, and single-peak multiple-ID co-assignment.
        /// </summary>
        public static string OspreyArgUsageProvider_GetDescription_model_diagnostics {
            get {
                return ResourceManager.GetString("OspreyArgUsageProvider_GetDescription_model_diagnostics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable coelution signal pre-filter.
        /// </summary>
        public static string OspreyArgUsageProvider_GetDescription_no_prefilter {
            get {
                return ResourceManager.GetString("OspreyArgUsageProvider_GetDescription_no_prefilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output blib file.
        /// </summary>
        public static string OspreyArgUsageProvider_GetDescription_output {
            get {
                return ResourceManager.GetString("OspreyArgUsageProvider_GetDescription_output", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory for intermediate files (overrides {0}).
        /// </summary>
        public static string OspreyArgUsageProvider_GetDescription_output_dir {
            get {
                return ResourceManager.GetString("OspreyArgUsageProvider_GetDescription_output_dir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input files scored concurrently (OUTER). Absent: one at a time (default). No value: auto from free RAM and cores. &lt;N&gt;: exactly N regardless of RAM/cores. Distinct from {0}..
        /// </summary>
        public static string OspreyArgUsageProvider_GetDescription_parallel_files {
            get {
                return ResourceManager.GetString("OspreyArgUsageProvider_GetDescription_parallel_files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emit the machine-parseable {0} lines that scripts and performance tools read (off by default).
        /// </summary>
        public static string OspreyArgUsageProvider_GetDescription_perf_stats {
            get {
                return ResourceManager.GetString("OspreyArgUsageProvider_GetDescription_perf_stats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protein-level FDR threshold (optional).
        /// </summary>
        public static string OspreyArgUsageProvider_GetDescription_protein_fdr {
            get {
                return ResourceManager.GetString("OspreyArgUsageProvider_GetDescription_protein_fdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peptide q-value threshold for keeping first-pass peptides for cross-run reconciliation and the second pass (default: 0.01 = {0}; loosen e.g. to 0.05 to broaden the reconciliation pool).
        /// </summary>
        public static string OspreyArgUsageProvider_GetDescription_reconciliation_compaction_fdr {
            get {
                return ResourceManager.GetString("OspreyArgUsageProvider_GetDescription_reconciliation_compaction_fdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write TSV report to file.
        /// </summary>
        public static string OspreyArgUsageProvider_GetDescription_report {
            get {
                return ResourceManager.GetString("OspreyArgUsageProvider_GetDescription_report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolution mode (default: {0}).
        /// </summary>
        public static string OspreyArgUsageProvider_GetDescription_resolution {
            get {
                return ResourceManager.GetString("OspreyArgUsageProvider_GetDescription_resolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run-level FDR threshold (default: 0.01).
        /// </summary>
        public static string OspreyArgUsageProvider_GetDescription_run_fdr {
            get {
                return ResourceManager.GetString("OspreyArgUsageProvider_GetDescription_run_fdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared peptide handling (default: {0}).
        /// </summary>
        public static string OspreyArgUsageProvider_GetDescription_shared_peptides {
            get {
                return ResourceManager.GetString("OspreyArgUsageProvider_GetDescription_shared_peptides", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HPC: run exactly one pipeline task (one node = one task). Omit for the full pipeline. {0} stages the {1} caches; {2} regenerates only the {3} report for a COMPLETED run, writing no other output..
        /// </summary>
        public static string OspreyArgUsageProvider_GetDescription_task {
            get {
                return ResourceManager.GetString("OspreyArgUsageProvider_GetDescription_task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Per-file main-search threads (INNER; default: all cores), divided across files run concurrently by {0}.
        /// </summary>
        public static string OspreyArgUsageProvider_GetDescription_threads {
            get {
                return ResourceManager.GetString("OspreyArgUsageProvider_GetDescription_threads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefix each output line with {0}.
        /// </summary>
        public static string OspreyArgUsageProvider_GetDescription_timestamp {
            get {
                return ResourceManager.GetString("OspreyArgUsageProvider_GetDescription_timestamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show more detail (e.g. per-fold Percolator iterations) that is hidden by default.
        /// </summary>
        public static string OspreyArgUsageProvider_GetDescription_verbose {
            get {
                return ResourceManager.GetString("OspreyArgUsageProvider_GetDescription_verbose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show version.
        /// </summary>
        public static string OspreyArgUsageProvider_GetDescription_version {
            get {
                return ResourceManager.GetString("OspreyArgUsageProvider_GetDescription_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write intermediate files AND the spectra cache here (so input data can be read-only); default: beside input.
        /// </summary>
        public static string OspreyArgUsageProvider_GetDescription_work_dir {
            get {
                return ResourceManager.GetString("OspreyArgUsageProvider_GetDescription_work_dir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write PIN files for external tools.
        /// </summary>
        public static string OspreyArgUsageProvider_GetDescription_write_pin {
            get {
                return ResourceManager.GetString("OspreyArgUsageProvider_GetDescription_write_pin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value &apos;{0}&apos; for {1}..
        /// </summary>
        public static string OspreyArgUsageProvider_ValueInvalidMessage_Invalid_value___0___for__1__ {
            get {
                return ResourceManager.GetString("OspreyArgUsageProvider_ValueInvalidMessage_Invalid_value___0___for__1__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value &apos;{0}&apos; for {1} (expected {2})..
        /// </summary>
        public static string OspreyArgUsageProvider_ValueInvalidMessage_Invalid_value___0___for__1___expected__2___ {
            get {
                return ResourceManager.GetString("OspreyArgUsageProvider_ValueInvalidMessage_Invalid_value___0___for__1___expected_" +
                        "_2___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} requires a value..
        /// </summary>
        public static string OspreyArgUsageProvider_ValueMissingMessage__0__requires_a_value_ {
            get {
                return ResourceManager.GetString("OspreyArgUsageProvider_ValueMissingMessage__0__requires_a_value_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value {0} for {1} out of range [{2}, {3}]..
        /// </summary>
        public static string OspreyArgUsageProvider_ValueOutOfRangeMessage_Value__0__for__1__out_of_range___2____3___ {
            get {
                return ResourceManager.GetString("OspreyArgUsageProvider_ValueOutOfRangeMessage_Value__0__for__1__out_of_range___2_" +
                        "___3___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} does not take a value..
        /// </summary>
        public static string OspreyArgUsageProvider_ValueUnexpectedMessage__0__does_not_take_a_value_ {
            get {
                return ResourceManager.GetString("OspreyArgUsageProvider_ValueUnexpectedMessage__0__does_not_take_a_value_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No help section matching &apos;{0}&apos; found. Use {1} to list available sections..
        /// </summary>
        public static string OspreyCommandArgs_BuildUsage_No_help_section_matching___0___found__Use__1__to_list_available_sections_ {
            get {
                return ResourceManager.GetString("OspreyCommandArgs_BuildUsage_No_help_section_matching___0___found__Use__1__to_lis" +
                        "t_available_sections_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is set without {1}; no FDRBench input will be written. Pass {1} {2} to enable FDRBench output..
        /// </summary>
        public static string OspreyCommandArgs_FdrBenchMissingMessage__0__is_set_without__1___no_FDRBench_input_will_be_written__Pass__1___2__to_enable_FDRBench_output_ {
            get {
                return ResourceManager.GetString("OspreyCommandArgs_FdrBenchMissingMessage__0__is_set_without__1___no_FDRBench_inpu" +
                        "t_will_be_written__Pass__1___2__to_enable_FDRBench_output_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decoys.
        /// </summary>
        public static string OspreyCommandArgs_Group_Decoys {
            get {
                return ResourceManager.GetString("OspreyCommandArgs_Group_Decoys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnostics &amp; Info.
        /// </summary>
        public static string OspreyCommandArgs_Group_Diagnostics_Info {
            get {
                return ResourceManager.GetString("OspreyCommandArgs_Group_Diagnostics_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distributed / HPC.
        /// </summary>
        public static string OspreyCommandArgs_Group_Distributed_HPC {
            get {
                return ResourceManager.GetString("OspreyCommandArgs_Group_Distributed_HPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FDR &amp; Protein Inference.
        /// </summary>
        public static string OspreyCommandArgs_Group_FDR_Protein_Inference {
            get {
                return ResourceManager.GetString("OspreyCommandArgs_Group_FDR_Protein_Inference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General I/O.
        /// </summary>
        public static string OspreyCommandArgs_Group_General_IO {
            get {
                return ResourceManager.GetString("OspreyCommandArgs_Group_General_IO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging.
        /// </summary>
        public static string OspreyCommandArgs_Group_Logging {
            get {
                return ResourceManager.GetString("OspreyCommandArgs_Group_Logging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance.
        /// </summary>
        public static string OspreyCommandArgs_Group_Performance {
            get {
                return ResourceManager.GetString("OspreyCommandArgs_Group_Performance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scoring &amp; Tolerance.
        /// </summary>
        public static string OspreyCommandArgs_Group_Scoring_Tolerance {
            get {
                return ResourceManager.GetString("OspreyCommandArgs_Group_Scoring_Tolerance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} file not found: {1}.
        /// </summary>
        public static string OspreyCommandArgs_ReadInputList__0__file_not_found___1_ {
            get {
                return ResourceManager.GetString("OspreyCommandArgs_ReadInputList__0__file_not_found___1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} file lists no input files: {1}.
        /// </summary>
        public static string OspreyCommandArgs_ReadInputList_The__0__file_lists_no_input_files___1_ {
            get {
                return ResourceManager.GetString("OspreyCommandArgs_ReadInputList_The__0__file_lists_no_input_files___1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is set without {1}, so the manifest will not be used. It is still part of the search settings, so existing {2} files scored without it will not be reused. Pass {1} to use the decoys in the library..
        /// </summary>
        public static string OspreyCommandArgs_ToConfig__0__is_set_without__1___so_the_manifest_will_not_be_used {
            get {
                return ResourceManager.GetString("OspreyCommandArgs_ToConfig__0__is_set_without__1___so_the_manifest_will_not_be_us" +
                        "ed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown argument: {0}.
        /// </summary>
        public static string OspreyCommandArgs_TokenizeAndDispatch_Unknown_argument___0_ {
            get {
                return ResourceManager.GetString("OspreyCommandArgs_TokenizeAndDispatch_Unknown_argument___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown argument: {0}. Run with {1} to see valid options..
        /// </summary>
        public static string OspreyCommandArgs_TokenizeAndDispatch_Unknown_argument___0___Run_with__1__to_see_valid_options_ {
            get {
                return ResourceManager.GetString("OspreyCommandArgs_TokenizeAndDispatch_Unknown_argument___0___Run_with__1__to_see_" +
                        "valid_options_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown FDR level &apos;{0}&apos;, defaulting to {1}.
        /// </summary>
        public static string OspreyCommandArgs_Unknown_FDR_level___0____defaulting_to__1_ {
            get {
                return ResourceManager.GetString("OspreyCommandArgs_Unknown_FDR_level___0____defaulting_to__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown FDR method &apos;{0}&apos;, defaulting to {1}.
        /// </summary>
        public static string OspreyCommandArgs_Unknown_FDR_method___0____defaulting_to__1_ {
            get {
                return ResourceManager.GetString("OspreyCommandArgs_Unknown_FDR_method___0____defaulting_to__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown fragment unit &apos;{0}&apos;, defaulting to {1}.
        /// </summary>
        public static string OspreyCommandArgs_Unknown_fragment_unit___0____defaulting_to__1_ {
            get {
                return ResourceManager.GetString("OspreyCommandArgs_Unknown_fragment_unit___0____defaulting_to__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown shared peptides mode &apos;{0}&apos;, defaulting to {1}.
        /// </summary>
        public static string OspreyCommandArgs_Unknown_shared_peptides_mode___0____defaulting_to__1_ {
            get {
                return ResourceManager.GetString("OspreyCommandArgs_Unknown_shared_peptides_mode___0____defaulting_to__1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXAMPLES:.
        /// </summary>
        public static string OspreyCommandArgs_UsageBlocks_EXAMPLES_ {
            get {
                return ResourceManager.GetString("OspreyCommandArgs_UsageBlocks_EXAMPLES_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HPC SPLIT (one node = one {0}): see {0} above..
        /// </summary>
        public static string OspreyCommandArgs_UsageBlocks_HPC_SPLIT__one_node___one__0____see__0__above_ {
            get {
                return ResourceManager.GetString("OspreyCommandArgs_UsageBlocks_HPC_SPLIT__one_node___one__0____see__0__above_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Osprey - Peptide-centric DIA analysis (.NET port of Osprey).
        /// </summary>
        public static string OspreyCommandArgs_UsageBlocks_Osprey___Peptide_centric_DIA_analysis__NET_port_of_Osprey_ {
            get {
                return ResourceManager.GetString("OspreyCommandArgs_UsageBlocks_Osprey___Peptide_centric_DIA_analysis__NET_port_of_" +
                        "Osprey_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USAGE: {0}.
        /// </summary>
        public static string OspreyCommandArgs_UsageBlocks_USAGE___0_ {
            get {
                return ResourceManager.GetString("OspreyCommandArgs_UsageBlocks_USAGE___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:N0} input file names appear more than once..
        /// </summary>
        public static string Program_DuplicateInputStemError__0__input_file_names_appear_more_than_once_ {
            get {
                return ResourceManager.GetString("Program_DuplicateInputStemError__0__input_file_names_appear_more_than_once_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 input file name appears more than once..
        /// </summary>
        public static string Program_DuplicateInputStemError_1_input_file_name_appears_more_than_once_ {
            get {
                return ResourceManager.GetString("Program_DuplicateInputStemError_1_input_file_name_appears_more_than_once_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every file Osprey writes for an input is named after the input without its extension, so inputs sharing a name would overwrite each other&apos;s intermediate files. Rename or stage them so each input has a distinct file name:.
        /// </summary>
        public static string Program_DuplicateInputStemError_Every_file_Osprey_writes_for_an_input_is_named_after_the_input_without_its_extension__so_ {
            get {
                return ResourceManager.GetString("Program_DuplicateInputStemError_Every_file_Osprey_writes_for_an_input_is_named_af" +
                        "ter_the_input_without_its_extension__so_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error:.
        /// </summary>
        public static string Program_LogError_Error_ {
            get {
                return ResourceManager.GetString("Program_LogError_Error_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning:.
        /// </summary>
        public static string Program_LogWarning_Warning_ {
            get {
                return ResourceManager.GetString("Program_LogWarning_Warning_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure occurred. Exiting....
        /// </summary>
        public static string Program_ReconcileExitCode_Failure_occurred__Exiting___ {
            get {
                return ResourceManager.GetString("Program_ReconcileExitCode_Failure_occurred__Exiting___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: unknown task &apos;{1}&apos;. Valid tasks: {2}..
        /// </summary>
        public static string Program_ResolveTask__0___unknown_task___1____Valid_tasks___2__ {
            get {
                return ResourceManager.GetString("Program_ResolveTask__0___unknown_task___1____Valid_tasks___2__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:N0} of {1:N0} input files are not present; using the intermediate scores file written for each one..
        /// </summary>
        public static string Program_Run__0__of__1__input_files_are_not_present__using_the_intermediate_scores_file_written_for_ {
            get {
                return ResourceManager.GetString("Program_Run__0__of__1__input_files_are_not_present__using_the_intermediate_scores" +
                        "_file_written_for_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:N0} of {1:N0} input files are not present but have a spectra cache; reading those from the cache..
        /// </summary>
        public static string Program_Run__0__of__1__input_files_are_not_present_but_have_a_spectra_cache__reading_those_from_the_ {
            get {
                return ResourceManager.GetString("Program_Run__0__of__1__input_files_are_not_present_but_have_a_spectra_cache__read" +
                        "ing_those_from_the_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} requires a task name ({1})..
        /// </summary>
        public static string Program_Run__0__requires_a_task_name___1___ {
            get {
                return ResourceManager.GetString("Program_Run__0__requires_a_task_name___1___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (none).
        /// </summary>
        public static string Program_Run__none_ {
            get {
                return ResourceManager.GetString("Program_Run__none_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 of {1:N0} input files is not present; using the intermediate scores file written for it..
        /// </summary>
        public static string Program_Run_1_of__1__input_files_is_not_present__using_the_intermediate_scores_file_written_for_it_ {
            get {
                return ResourceManager.GetString("Program_Run_1_of__1__input_files_is_not_present__using_the_intermediate_scores_fi" +
                        "le_written_for_it_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 of {1:N0} input files is not present but has a spectra cache; reading it from the cache..
        /// </summary>
        public static string Program_Run_1_of__1__input_files_is_not_present_but_has_a_spectra_cache__reading_it_from_the_cache_ {
            get {
                return ResourceManager.GetString("Program_Run_1_of__1__input_files_is_not_present_but_has_a_spectra_cache__reading_" +
                        "it_from_the_cache_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command: {0}.
        /// </summary>
        public static string Program_Run_Command___0_ {
            get {
                return ResourceManager.GetString("Program_Run_Command___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experiment FDR: {0:P1}.
        /// </summary>
        public static string Program_Run_Experiment_FDR___0_ {
            get {
                return ResourceManager.GetString("Program_Run_Experiment_FDR___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to open log file {0}: {1}.
        /// </summary>
        public static string Program_Run_Failed_to_open_log_file__0____1_ {
            get {
                return ResourceManager.GetString("Program_Run_Failed_to_open_log_file__0____1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal error: {0}.
        /// </summary>
        public static string Program_Run_Fatal_error___0_ {
            get {
                return ResourceManager.GetString("Program_Run_Fatal_error___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fragment tolerance: {0} {1}.
        /// </summary>
        public static string Program_Run_Fragment_tolerance___0___1_ {
            get {
                return ResourceManager.GetString("Program_Run_Fragment_tolerance___0___1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input file not found, and no spectra cache or intermediate file exists to stand in for it: {0}.
        /// </summary>
        public static string Program_Run_Input_file_not_found__and_no_spectra_cache_or_intermediate_file_exists_to_stand_in_for_it_ {
            get {
                return ResourceManager.GetString("Program_Run_Input_file_not_found__and_no_spectra_cache_or_intermediate_file_exist" +
                        "s_to_stand_in_for_it_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input files: {0:N0}.
        /// </summary>
        public static string Program_Run_Input_files___0_ {
            get {
                return ResourceManager.GetString("Program_Run_Input_files___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library: {0} ({1}).
        /// </summary>
        public static string Program_Run_Library___0____1__ {
            get {
                return ResourceManager.GetString("Program_Run_Library___0____1__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library file not found: {0}.
        /// </summary>
        public static string Program_Run_Library_file_not_found___0_ {
            get {
                return ResourceManager.GetString("Program_Run_Library_file_not_found___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No arguments were given; see the usage above..
        /// </summary>
        public static string Program_Run_No_arguments_were_given__see_the_usage_above_ {
            get {
                return ResourceManager.GetString("Program_Run_No_arguments_were_given__see_the_usage_above_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Osprey v{0}.
        /// </summary>
        public static string Program_Run_Osprey_v_0_ {
            get {
                return ResourceManager.GetString("Program_Run_Osprey_v_0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output: {0}.
        /// </summary>
        public static string Program_Run_Output___0_ {
            get {
                return ResourceManager.GetString("Program_Run_Output___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protein FDR: {0:P1}.
        /// </summary>
        public static string Program_Run_Protein_FDR___0_ {
            get {
                return ResourceManager.GetString("Program_Run_Protein_FDR___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolution: {0}.
        /// </summary>
        public static string Program_Run_Resolution___0_ {
            get {
                return ResourceManager.GetString("Program_Run_Resolution___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run FDR: {0:P1}.
        /// </summary>
        public static string Program_Run_Run_FDR___0_ {
            get {
                return ResourceManager.GetString("Program_Run_Run_FDR___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task: {0} (single-task run).
        /// </summary>
        public static string Program_Run_Task___0___single_task_run_ {
            get {
                return ResourceManager.GetString("Program_Run_Task___0___single_task_run_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The input file is not present; using the intermediate scores file written for it..
        /// </summary>
        public static string Program_Run_The_input_file_is_not_present__using_the_intermediate_scores_file_written_for_it_ {
            get {
                return ResourceManager.GetString("Program_Run_The_input_file_is_not_present__using_the_intermediate_scores_file_wri" +
                        "tten_for_it_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The input file is not present but has a spectra cache; reading it from the cache..
        /// </summary>
        public static string Program_Run_The_input_file_is_not_present_but_has_a_spectra_cache__reading_it_from_the_cache_ {
            get {
                return ResourceManager.GetString("Program_Run_The_input_file_is_not_present_but_has_a_spectra_cache__reading_it_fro" +
                        "m_the_cache_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Threads: {0:N0}.
        /// </summary>
        public static string Program_Run_Threads___0_ {
            get {
                return ResourceManager.GetString("Program_Run_Threads___0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: building the report from the completed analysis. Nothing is re-run and no other output changes..
        /// </summary>
        public static string Program_RunModelDiagnosticsTask__0___building_the_report_from_the_completed_analysis__Nothing_is_re_run_and_no_other_ {
            get {
                return ResourceManager.GetString("Program_RunModelDiagnosticsTask__0___building_the_report_from_the_completed_analy" +
                        "sis__Nothing_is_re_run_and_no_other_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: the saved model diagnostics data for this analysis could not be read, so the report was not built..
        /// </summary>
        public static string Program_RunModelDiagnosticsTask__0___the_saved_model_diagnostics_data_for_this_analysis_could_not_be_read__so_the_report_ {
            get {
                return ResourceManager.GetString("Program_RunModelDiagnosticsTask__0___the_saved_model_diagnostics_data_for_this_an" +
                        "alysis_could_not_be_read__so_the_report_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: there is no completed first pass to describe (no first-pass intermediate file for the whole experiment beside the output). Run the analysis at least as far as {1} first..
        /// </summary>
        public static string Program_RunModelDiagnosticsTask__0___there_is_no_completed_first_pass_to_describe__no_first_pass_intermediate_file_for_ {
            get {
                return ResourceManager.GetString("Program_RunModelDiagnosticsTask__0___there_is_no_completed_first_pass_to_describe" +
                        "__no_first_pass_intermediate_file_for_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No input files specified. Use {0}.
        /// </summary>
        public static string Program_ValidateArgs_No_input_files_specified__Use__0_ {
            get {
                return ResourceManager.GetString("Program_ValidateArgs_No_input_files_specified__Use__0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No output path specified. Use {0}.
        /// </summary>
        public static string Program_ValidateArgs_No_output_path_specified__Use__0_ {
            get {
                return ResourceManager.GetString("Program_ValidateArgs_No_output_path_specified__Use__0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No spectral library specified. Use {0}.
        /// </summary>
        public static string Program_ValidateArgs_No_spectral_library_specified__Use__0_ {
            get {
                return ResourceManager.GetString("Program_ValidateArgs_No_spectral_library_specified__Use__0_", resourceCulture);
            }
        }
    }
}
