set(pwiz_INCLUDE_DIRS
    ${CMAKE_CURRENT_LIST_DIR}
    ${CMAKE_CURRENT_LIST_DIR}/libraries/boost_1_76_0
    ${CMAKE_CURRENT_LIST_DIR}/libraries/boost_aux
    )

set(pwiz_LIB_PREFIX ${CMAKE_CURRENT_LIST_DIR}/build-nt-x86)
set(pwiz_LIBS_DEBUG
    ${pwiz_LIB_PREFIX}/ext/boost/chrono-1_76_0/msvc-14.2/dbg/adrs-mdl-64/async-excpt-on/lnk-sttc/thrd-mlt/libboost_chrono-vc142-mt-gd.lib
    ${pwiz_LIB_PREFIX}/ext/boost/filesystem-1_76_0/msvc-14.2/dbg/adrs-mdl-64/async-excpt-on/lnk-sttc/thrd-mlt/libboost_filesystem-vc142-mt-gd.lib
    ${pwiz_LIB_PREFIX}/ext/boost/iostreams-1_76_0/msvc-14.2/dbg/adrs-mdl-64/async-excpt-on/lnk-sttc/thrd-mlt/libboost_iostreams-vc142-mt-gd.lib
    ${pwiz_LIB_PREFIX}/ext/boost/nowide-1_76_0/msvc-14.2/dbg/adrs-mdl-64/async-excpt-on/lnk-sttc/thrd-mlt/libboost_nowide-vc142-mt-gd.lib
    ${pwiz_LIB_PREFIX}/ext/boost/program_options-1_76_0/msvc-14.2/dbg/adrs-mdl-64/async-excpt-on/lnk-sttc/thrd-mlt/libboost_program_options-vc142-mt-gd.lib
    ${pwiz_LIB_PREFIX}/ext/boost/serialization-1_76_0/msvc-14.2/dbg/adrs-mdl-64/async-excpt-on/lnk-sttc/thrd-mlt/libboost_serialization-vc142-mt-gd.lib
    ${pwiz_LIB_PREFIX}/ext/boost/system-1_76_0/msvc-14.2/dbg/adrs-mdl-64/async-excpt-on/lnk-sttc/thrd-mlt/libboost_system-vc142-mt-gd.lib
    ${pwiz_LIB_PREFIX}/ext/boost/thread-1_76_0/msvc-14.2/dbg/adrs-mdl-64/async-excpt-on/lnk-sttc/thrd-mlt/libboost_thread-vc142-mt-gd.lib
    ${pwiz_LIB_PREFIX}/ext/freetype/freetype/msvc-14.2/dbg/adrs-mdl-64/async-excpt-on/lnk-sttc/thrd-mlt/libfreetype-vc142-mt-gd-2_4.lib
    ${pwiz_LIB_PREFIX}/ext/gd/gd/msvc-14.2/dbg/adrs-mdl-64/async-excpt-on/lnk-sttc/thrd-mlt/libgd-vc142-mt-gd-2_1.lib
    ${pwiz_LIB_PREFIX}/ext/hdf5/msvc-14.2/dbg/adrs-mdl-64/async-excpt-on/lnk-sttc/thrd-mlt/libhdf5.lib
    ${pwiz_LIB_PREFIX}/ext/hdf5/msvc-14.2/dbg/adrs-mdl-64/async-excpt-on/lnk-sttc/thrd-mlt/libhdf5pp.lib
    ${pwiz_LIB_PREFIX}/libraries/libsvm-3.0/msvc-14.2/dbg/adrs-mdl-64/async-excpt-on/lnk-sttc/thrd-mlt/libsvm.lib
    ${pwiz_LIB_PREFIX}/libraries/SQLite/msvc-14.2/dbg/adrs-mdl-64/async-excpt-on/lnk-sttc/thrd-mlt/libsqlite3.lib
    ${pwiz_LIB_PREFIX}/libraries/SQLite/msvc-14.2/dbg/adrs-mdl-64/async-excpt-on/lnk-sttc/thrd-mlt/libsqlite3pp.lib
    ${pwiz_LIB_PREFIX}/pwiz/analysis/chromatogram_processing/msvc-14.2/dbg/adrs-mdl-64/async-excpt-on/lnk-sttc/thrd-mlt/libpwiz_analysis_chromatogram_processing.lib
    ${pwiz_LIB_PREFIX}/pwiz/analysis/common/msvc-14.2/dbg/adrs-mdl-64/async-excpt-on/lnk-sttc/thrd-mlt/libpwiz_analysis_common.lib
    ${pwiz_LIB_PREFIX}/pwiz/analysis/demux/msvc-14.2/dbg/adrs-mdl-64/async-excpt-on/lnk-sttc/thrd-mlt/libpwiz_analysis_demux.lib
    ${pwiz_LIB_PREFIX}/pwiz/analysis/demux/msvc-14.2/dbg/adrs-mdl-64/async-excpt-on/lnk-sttc/thrd-mlt/libpwiz_analysis_demuxtestdata.lib
    ${pwiz_LIB_PREFIX}/pwiz/analysis/dia_umpire/msvc-14.2/dbg/adrs-mdl-64/async-excpt-on/lnk-sttc/thrd-mlt/libpwiz_analysis_diaumpire.lib
    ${pwiz_LIB_PREFIX}/pwiz/analysis/frequency/msvc-14.2/dbg/adrs-mdl-64/async-excpt-on/lnk-sttc/thrd-mlt/libpwiz_analysis_frequency.lib
    ${pwiz_LIB_PREFIX}/pwiz/analysis/msvc-14.2/dbg/adrs-mdl-64/async-excpt-on/lnk-sttc/thrd-mlt/libpwiz_analysis_version.lib
    ${pwiz_LIB_PREFIX}/pwiz/analysis/passive/msvc-14.2/dbg/adrs-mdl-64/async-excpt-on/lnk-sttc/thrd-mlt/libpwiz_analysis_passive.lib
    ${pwiz_LIB_PREFIX}/pwiz/analysis/passive/msvc-14.2/dbg/adrs-mdl-64/async-excpt-on/lnk-sttc/thrd-mlt/libpwiz_analysis_passive_core.lib
    ${pwiz_LIB_PREFIX}/pwiz/analysis/peakdetect/msvc-14.2/dbg/adrs-mdl-64/async-excpt-on/lnk-sttc/thrd-mlt/libpwiz_analysis_peakdetect.lib
    ${pwiz_LIB_PREFIX}/pwiz/analysis/peptideid/msvc-14.2/dbg/adrs-mdl-64/async-excpt-on/lnk-sttc/thrd-mlt/libpwiz_analysis_peptideid.lib
    ${pwiz_LIB_PREFIX}/pwiz/analysis/proteome_processing/msvc-14.2/dbg/adrs-mdl-64/async-excpt-on/lnk-sttc/thrd-mlt/libpwiz_analysis_proteome_processing.lib
    ${pwiz_LIB_PREFIX}/pwiz/analysis/spectrum_processing/msvc-14.2/dbg/adrs-mdl-64/async-excpt-on/lnk-sttc/thrd-mlt/libpwiz_analysis_spectrum_processing.lib
    ${pwiz_LIB_PREFIX}/pwiz/analysis/spectrum_processing/msvc-14.2/dbg/adrs-mdl-64/async-excpt-on/lnk-sttc/thrd-mlt/libpwiz_analysis_spectrum_processing_basic.lib
    ${pwiz_LIB_PREFIX}/pwiz/data/common/msvc-14.2/dbg/adrs-mdl-64/async-excpt-on/lnk-sttc/thrd-mlt/libpwiz_data_common.lib
    ${pwiz_LIB_PREFIX}/pwiz/data/common/msvc-14.2/dbg/adrs-mdl-64/async-excpt-on/lnk-sttc/thrd-mlt/libpwiz_data_obo.lib
    ${pwiz_LIB_PREFIX}/pwiz/data/identdata/msvc-14.2/dbg/adrs-mdl-64/async-excpt-on/lnk-sttc/thrd-mlt/libpwiz_data_identdata.lib
    ${pwiz_LIB_PREFIX}/pwiz/data/identdata/msvc-14.2/dbg/adrs-mdl-64/async-excpt-on/lnk-sttc/thrd-mlt/libpwiz_data_identdata_examples.lib
    ${pwiz_LIB_PREFIX}/pwiz/data/identdata/msvc-14.2/dbg/adrs-mdl-64/async-excpt-on/lnk-sttc/thrd-mlt/libpwiz_data_identdata_version.lib
    ${pwiz_LIB_PREFIX}/pwiz/data/misc/msvc-14.2/dbg/adrs-mdl-64/async-excpt-on/lnk-sttc/thrd-mlt/libpwiz_data_misc.lib
    ${pwiz_LIB_PREFIX}/pwiz/data/msdata/msvc-14.2/dbg/adrs-mdl-64/async-excpt-on/lnk-sttc/thrd-mlt/libpwiz_data_msdata.lib
    ${pwiz_LIB_PREFIX}/pwiz/data/msdata/msvc-14.2/dbg/adrs-mdl-64/async-excpt-on/lnk-sttc/thrd-mlt/libpwiz_data_msdata_core.lib
    ${pwiz_LIB_PREFIX}/pwiz/data/msdata/msvc-14.2/dbg/adrs-mdl-64/async-excpt-on/lnk-sttc/thrd-mlt/libpwiz_data_msdata_examples.lib
    ${pwiz_LIB_PREFIX}/pwiz/data/msdata/msvc-14.2/dbg/adrs-mdl-64/async-excpt-on/lnk-sttc/thrd-mlt/libpwiz_data_msdata_version.lib
    ${pwiz_LIB_PREFIX}/pwiz/data/msdata/mz5/msvc-14.2/dbg/adrs-mdl-64/async-excpt-on/lnk-sttc/thrd-mlt/libpwiz_data_msdata_mz5.lib
    ${pwiz_LIB_PREFIX}/pwiz/data/proteome/msvc-14.2/dbg/adrs-mdl-64/async-excpt-on/lnk-sttc/thrd-mlt/libpwiz_data_proteome.lib
    ${pwiz_LIB_PREFIX}/pwiz/data/proteome/msvc-14.2/dbg/adrs-mdl-64/async-excpt-on/lnk-sttc/thrd-mlt/libpwiz_data_proteome_examples.lib
    ${pwiz_LIB_PREFIX}/pwiz/data/proteome/msvc-14.2/dbg/adrs-mdl-64/async-excpt-on/lnk-sttc/thrd-mlt/libpwiz_data_proteome_version.lib
    ${pwiz_LIB_PREFIX}/pwiz/data/tradata/msvc-14.2/dbg/adrs-mdl-64/async-excpt-on/lnk-sttc/thrd-mlt/libpwiz_data_tradata.lib
    ${pwiz_LIB_PREFIX}/pwiz/data/tradata/msvc-14.2/dbg/adrs-mdl-64/async-excpt-on/lnk-sttc/thrd-mlt/libpwiz_data_tradata_examples.lib
    ${pwiz_LIB_PREFIX}/pwiz/data/tradata/msvc-14.2/dbg/adrs-mdl-64/async-excpt-on/lnk-sttc/thrd-mlt/libpwiz_data_tradata_version.lib
    ${pwiz_LIB_PREFIX}/pwiz/data/vendor_readers/ABI/msvc-14.2/dbg/adrs-mdl-64/async-excpt-on/lnk-sttc/thrd-mlt/libpwiz_reader_abi.lib
    ${pwiz_LIB_PREFIX}/pwiz/data/vendor_readers/ABI/T2D/msvc-14.2/dbg/adrs-mdl-64/async-excpt-on/lnk-sttc/thrd-mlt/libpwiz_reader_abi_t2d.lib
    ${pwiz_LIB_PREFIX}/pwiz/data/vendor_readers/Agilent/msvc-14.2/dbg/adrs-mdl-64/async-excpt-on/lnk-sttc/thrd-mlt/libpwiz_reader_agilent.lib
    ${pwiz_LIB_PREFIX}/pwiz/data/vendor_readers/Bruker/msvc-14.2/dbg/adrs-mdl-64/async-excpt-on/lnk-sttc/thrd-mlt/libpwiz_reader_bruker.lib
    ${pwiz_LIB_PREFIX}/pwiz/data/vendor_readers/msvc-14.2/dbg/adrs-mdl-64/async-excpt-on/lnk-sttc/thrd-mlt/libpwiz_data_vendor_readers.lib
    ${pwiz_LIB_PREFIX}/pwiz/data/vendor_readers/Shimadzu/msvc-14.2/dbg/adrs-mdl-64/async-excpt-on/lnk-sttc/thrd-mlt/libpwiz_reader_shimadzu.lib
    ${pwiz_LIB_PREFIX}/pwiz/data/vendor_readers/Thermo/msvc-14.2/dbg/adrs-mdl-64/async-excpt-on/lnk-sttc/thrd-mlt/libpwiz_reader_thermo.lib
    ${pwiz_LIB_PREFIX}/pwiz/data/vendor_readers/UIMF/msvc-14.2/dbg/adrs-mdl-64/async-excpt-on/lnk-sttc/thrd-mlt/libpwiz_reader_uimf.lib
    ${pwiz_LIB_PREFIX}/pwiz/data/vendor_readers/UNIFI/msvc-14.2/dbg/adrs-mdl-64/async-excpt-on/lnk-sttc/thrd-mlt/libpwiz_reader_unifi.lib
    ${pwiz_LIB_PREFIX}/pwiz/data/vendor_readers/Waters/msvc-14.2/dbg/adrs-mdl-64/async-excpt-on/lnk-sttc/thrd-mlt/libpwiz_reader_waters.lib
    ${pwiz_LIB_PREFIX}/pwiz/msvc-14.2/dbg/adrs-mdl-64/async-excpt-on/lnk-sttc/thrd-mlt/libpwiz_version.lib
    ${pwiz_LIB_PREFIX}/pwiz/utility/chemistry/msvc-14.2/dbg/adrs-mdl-64/async-excpt-on/lnk-sttc/thrd-mlt/libpwiz_utility_chemistry.lib
    ${pwiz_LIB_PREFIX}/pwiz/utility/math/msvc-14.2/dbg/adrs-mdl-64/async-excpt-on/lnk-sttc/thrd-mlt/libpwiz_utility_math.lib
    ${pwiz_LIB_PREFIX}/pwiz/utility/minimxml/msvc-14.2/dbg/adrs-mdl-64/async-excpt-on/lnk-sttc/thrd-mlt/libpwiz_utility_minimxml.lib
    ${pwiz_LIB_PREFIX}/pwiz/utility/misc/msvc-14.2/dbg/adrs-mdl-64/async-excpt-on/lnk-sttc/thrd-mlt/libpwiz_utility_image.lib
    ${pwiz_LIB_PREFIX}/pwiz/utility/misc/msvc-14.2/dbg/adrs-mdl-64/async-excpt-on/lnk-sttc/thrd-mlt/libpwiz_utility_misc.lib
    ${pwiz_LIB_PREFIX}/pwiz/utility/misc/msvc-14.2/dbg/adrs-mdl-64/async-excpt-on/lnk-sttc/thrd-mlt/libpwiz_utility_vendor_reader_test_harness.lib
    ${pwiz_LIB_PREFIX}/pwiz/utility/misc/msvc-14.2/dbg/adrs-mdl-64/async-excpt-on/lnk-sttc/thrd-mlt/libSHA1.lib
    ${pwiz_LIB_PREFIX}/pwiz_aux/msrc/utility/vendor_api/Agilent/msvc-14.2/dbg/adrs-mdl-64/lnk-sttc/thrd-mlt/us-clr-tr/libpwiz_vendor_api_agilent.lib
    ${pwiz_LIB_PREFIX}/pwiz_aux/msrc/utility/vendor_api/thermo/msvc-14.2/dbg/adrs-mdl-64/lnk-sttc/thrd-mlt/us-clr-tr/libpwiz_vendor_api_thermo.lib
    ${pwiz_LIB_PREFIX}/pwiz_aux/msrc/utility/vendor_api/UIMF/msvc-14.2/dbg/adrs-mdl-64/lnk-sttc/thrd-mlt/us-clr-tr/libpwiz_vendor_api_uimf.lib
    ${pwiz_LIB_PREFIX}/pwiz_aux/msrc/utility/vendor_api/UNIFI/msvc-14.2/dbg/adrs-mdl-64/lnk-sttc/thrd-mlt/us-clr-tr/libpwiz_vendor_api_unifi.lib
    ${pwiz_LIB_PREFIX}/pwiz_tools/commandline/msvc-14.2/dbg/adrs-mdl-64/async-excpt-on/lnk-sttc/thrd-mlt/msconvert.lib
    ${pwiz_LIB_PREFIX}/pwiz_tools/common/msvc-14.2/dbg/adrs-mdl-64/async-excpt-on/lnk-sttc/thrd-mlt/libpwiz_tools_common.lib
    ${pwiz_LIB_PREFIX}/standalone/libpng/msvc-14.2/dbg/adrs-mdl-64/async-excpt-on/lnk-sttc/thrd-mlt/libpng.lib
    ${pwiz_LIB_PREFIX}/standalone/zlib/msvc-14.2/dbg/adrs-mdl-64/async-excpt-on/lnk-sttc/thrd-mlt/libzlib.lib
    )

set(pwiz_LIBS_RELEASE
    ${pwiz_LIB_PREFIX}/ext/boost/chrono-1_76_0/msvc-14.2/rls/adrs-mdl-64/async-excpt-on/lnk-sttc/thrd-mlt/libboost_chrono-vc142-mt.lib
    ${pwiz_LIB_PREFIX}/ext/boost/filesystem-1_76_0/msvc-14.2/rls/adrs-mdl-64/async-excpt-on/lnk-sttc/thrd-mlt/libboost_filesystem-vc142-mt.lib
    ${pwiz_LIB_PREFIX}/ext/boost/iostreams-1_76_0/msvc-14.2/rls/adrs-mdl-64/async-excpt-on/lnk-sttc/thrd-mlt/libboost_iostreams-vc142-mt.lib
    ${pwiz_LIB_PREFIX}/ext/boost/nowide-1_76_0/msvc-14.2/rls/adrs-mdl-64/async-excpt-on/lnk-sttc/thrd-mlt/libboost_nowide-vc142-mt.lib
    ${pwiz_LIB_PREFIX}/ext/boost/program_options-1_76_0/msvc-14.2/rls/adrs-mdl-64/async-excpt-on/lnk-sttc/thrd-mlt/libboost_program_options-vc142-mt.lib
    ${pwiz_LIB_PREFIX}/ext/boost/serialization-1_76_0/msvc-14.2/rls/adrs-mdl-64/async-excpt-on/lnk-sttc/thrd-mlt/libboost_serialization-vc142-mt.lib
    ${pwiz_LIB_PREFIX}/ext/boost/system-1_76_0/msvc-14.2/rls/adrs-mdl-64/async-excpt-on/lnk-sttc/thrd-mlt/libboost_system-vc142-mt.lib
    ${pwiz_LIB_PREFIX}/ext/boost/thread-1_76_0/msvc-14.2/rls/adrs-mdl-64/async-excpt-on/lnk-sttc/thrd-mlt/libboost_thread-vc142-mt.lib
    ${pwiz_LIB_PREFIX}/ext/freetype/freetype/msvc-14.2/rls/adrs-mdl-64/async-excpt-on/lnk-sttc/thrd-mlt/libfreetype-vc142-mt-2_4.lib
    ${pwiz_LIB_PREFIX}/ext/gd/gd/msvc-14.2/rls/adrs-mdl-64/async-excpt-on/lnk-sttc/thrd-mlt/libgd-vc142-mt-2_1.lib
    ${pwiz_LIB_PREFIX}/ext/hdf5/msvc-14.2/rls/adrs-mdl-64/async-excpt-on/lnk-sttc/thrd-mlt/libhdf5.lib
    ${pwiz_LIB_PREFIX}/ext/hdf5/msvc-14.2/rls/adrs-mdl-64/async-excpt-on/lnk-sttc/thrd-mlt/libhdf5pp.lib
    ${pwiz_LIB_PREFIX}/libraries/libsvm-3.0/msvc-14.2/rls/adrs-mdl-64/async-excpt-on/lnk-sttc/thrd-mlt/libsvm.lib
    ${pwiz_LIB_PREFIX}/libraries/SQLite/msvc-14.2/rls/adrs-mdl-64/async-excpt-on/lnk-sttc/thrd-mlt/libsqlite3.lib
    ${pwiz_LIB_PREFIX}/libraries/SQLite/msvc-14.2/rls/adrs-mdl-64/async-excpt-on/lnk-sttc/thrd-mlt/libsqlite3pp.lib
    ${pwiz_LIB_PREFIX}/pwiz/analysis/chromatogram_processing/msvc-14.2/rls/adrs-mdl-64/async-excpt-on/lnk-sttc/thrd-mlt/libpwiz_analysis_chromatogram_processing.lib
    ${pwiz_LIB_PREFIX}/pwiz/analysis/common/msvc-14.2/rls/adrs-mdl-64/async-excpt-on/lnk-sttc/thrd-mlt/libpwiz_analysis_common.lib
    ${pwiz_LIB_PREFIX}/pwiz/analysis/demux/msvc-14.2/rls/adrs-mdl-64/async-excpt-on/lnk-sttc/thrd-mlt/libpwiz_analysis_demux.lib
    ${pwiz_LIB_PREFIX}/pwiz/analysis/demux/msvc-14.2/rls/adrs-mdl-64/async-excpt-on/lnk-sttc/thrd-mlt/libpwiz_analysis_demuxtestdata.lib
    ${pwiz_LIB_PREFIX}/pwiz/analysis/dia_umpire/msvc-14.2/rls/adrs-mdl-64/async-excpt-on/lnk-sttc/thrd-mlt/libpwiz_analysis_diaumpire.lib
    ${pwiz_LIB_PREFIX}/pwiz/analysis/frequency/msvc-14.2/rls/adrs-mdl-64/async-excpt-on/lnk-sttc/thrd-mlt/libpwiz_analysis_frequency.lib
    ${pwiz_LIB_PREFIX}/pwiz/analysis/msvc-14.2/rls/adrs-mdl-64/async-excpt-on/lnk-sttc/thrd-mlt/libpwiz_analysis_version.lib
    ${pwiz_LIB_PREFIX}/pwiz/analysis/passive/msvc-14.2/rls/adrs-mdl-64/async-excpt-on/lnk-sttc/thrd-mlt/libpwiz_analysis_passive.lib
    ${pwiz_LIB_PREFIX}/pwiz/analysis/passive/msvc-14.2/rls/adrs-mdl-64/async-excpt-on/lnk-sttc/thrd-mlt/libpwiz_analysis_passive_core.lib
    ${pwiz_LIB_PREFIX}/pwiz/analysis/peakdetect/msvc-14.2/rls/adrs-mdl-64/async-excpt-on/lnk-sttc/thrd-mlt/libpwiz_analysis_peakdetect.lib
    ${pwiz_LIB_PREFIX}/pwiz/analysis/peptideid/msvc-14.2/rls/adrs-mdl-64/async-excpt-on/lnk-sttc/thrd-mlt/libpwiz_analysis_peptideid.lib
    ${pwiz_LIB_PREFIX}/pwiz/analysis/proteome_processing/msvc-14.2/rls/adrs-mdl-64/async-excpt-on/lnk-sttc/thrd-mlt/libpwiz_analysis_proteome_processing.lib
    ${pwiz_LIB_PREFIX}/pwiz/analysis/spectrum_processing/msvc-14.2/rls/adrs-mdl-64/async-excpt-on/lnk-sttc/thrd-mlt/libpwiz_analysis_spectrum_processing.lib
    ${pwiz_LIB_PREFIX}/pwiz/analysis/spectrum_processing/msvc-14.2/rls/adrs-mdl-64/async-excpt-on/lnk-sttc/thrd-mlt/libpwiz_analysis_spectrum_processing_basic.lib
    ${pwiz_LIB_PREFIX}/pwiz/data/common/msvc-14.2/rls/adrs-mdl-64/async-excpt-on/lnk-sttc/thrd-mlt/libpwiz_data_common.lib
    ${pwiz_LIB_PREFIX}/pwiz/data/common/msvc-14.2/rls/adrs-mdl-64/async-excpt-on/lnk-sttc/thrd-mlt/libpwiz_data_obo.lib
    ${pwiz_LIB_PREFIX}/pwiz/data/identdata/msvc-14.2/rls/adrs-mdl-64/async-excpt-on/lnk-sttc/thrd-mlt/libpwiz_data_identdata.lib
    ${pwiz_LIB_PREFIX}/pwiz/data/identdata/msvc-14.2/rls/adrs-mdl-64/async-excpt-on/lnk-sttc/thrd-mlt/libpwiz_data_identdata_examples.lib
    ${pwiz_LIB_PREFIX}/pwiz/data/identdata/msvc-14.2/rls/adrs-mdl-64/async-excpt-on/lnk-sttc/thrd-mlt/libpwiz_data_identdata_version.lib
    ${pwiz_LIB_PREFIX}/pwiz/data/misc/msvc-14.2/rls/adrs-mdl-64/async-excpt-on/lnk-sttc/thrd-mlt/libpwiz_data_misc.lib
    ${pwiz_LIB_PREFIX}/pwiz/data/msdata/msvc-14.2/rls/adrs-mdl-64/async-excpt-on/lnk-sttc/thrd-mlt/libpwiz_data_msdata.lib
    ${pwiz_LIB_PREFIX}/pwiz/data/msdata/msvc-14.2/rls/adrs-mdl-64/async-excpt-on/lnk-sttc/thrd-mlt/libpwiz_data_msdata_core.lib
    ${pwiz_LIB_PREFIX}/pwiz/data/msdata/msvc-14.2/rls/adrs-mdl-64/async-excpt-on/lnk-sttc/thrd-mlt/libpwiz_data_msdata_examples.lib
    ${pwiz_LIB_PREFIX}/pwiz/data/msdata/msvc-14.2/rls/adrs-mdl-64/async-excpt-on/lnk-sttc/thrd-mlt/libpwiz_data_msdata_version.lib
    ${pwiz_LIB_PREFIX}/pwiz/data/msdata/mz5/msvc-14.2/rls/adrs-mdl-64/async-excpt-on/lnk-sttc/thrd-mlt/libpwiz_data_msdata_mz5.lib
    ${pwiz_LIB_PREFIX}/pwiz/data/proteome/msvc-14.2/rls/adrs-mdl-64/async-excpt-on/lnk-sttc/thrd-mlt/libpwiz_data_proteome.lib
    ${pwiz_LIB_PREFIX}/pwiz/data/proteome/msvc-14.2/rls/adrs-mdl-64/async-excpt-on/lnk-sttc/thrd-mlt/libpwiz_data_proteome_examples.lib
    ${pwiz_LIB_PREFIX}/pwiz/data/proteome/msvc-14.2/rls/adrs-mdl-64/async-excpt-on/lnk-sttc/thrd-mlt/libpwiz_data_proteome_version.lib
    ${pwiz_LIB_PREFIX}/pwiz/data/tradata/msvc-14.2/rls/adrs-mdl-64/async-excpt-on/lnk-sttc/thrd-mlt/libpwiz_data_tradata.lib
    ${pwiz_LIB_PREFIX}/pwiz/data/tradata/msvc-14.2/rls/adrs-mdl-64/async-excpt-on/lnk-sttc/thrd-mlt/libpwiz_data_tradata_examples.lib
    ${pwiz_LIB_PREFIX}/pwiz/data/tradata/msvc-14.2/rls/adrs-mdl-64/async-excpt-on/lnk-sttc/thrd-mlt/libpwiz_data_tradata_version.lib
    ${pwiz_LIB_PREFIX}/pwiz/data/vendor_readers/ABI/msvc-14.2/rls/adrs-mdl-64/async-excpt-on/lnk-sttc/thrd-mlt/libpwiz_reader_abi.lib
    ${pwiz_LIB_PREFIX}/pwiz/data/vendor_readers/ABI/T2D/msvc-14.2/rls/adrs-mdl-64/async-excpt-on/lnk-sttc/thrd-mlt/libpwiz_reader_abi_t2d.lib
    ${pwiz_LIB_PREFIX}/pwiz/data/vendor_readers/Agilent/msvc-14.2/rls/adrs-mdl-64/async-excpt-on/lnk-sttc/thrd-mlt/libpwiz_reader_agilent.lib
    ${pwiz_LIB_PREFIX}/pwiz/data/vendor_readers/Bruker/msvc-14.2/rls/adrs-mdl-64/async-excpt-on/lnk-sttc/thrd-mlt/libpwiz_reader_bruker.lib
    ${pwiz_LIB_PREFIX}/pwiz/data/vendor_readers/msvc-14.2/rls/adrs-mdl-64/async-excpt-on/lnk-sttc/thrd-mlt/libpwiz_data_vendor_readers.lib
    ${pwiz_LIB_PREFIX}/pwiz/data/vendor_readers/Shimadzu/msvc-14.2/rls/adrs-mdl-64/async-excpt-on/lnk-sttc/thrd-mlt/libpwiz_reader_shimadzu.lib
    ${pwiz_LIB_PREFIX}/pwiz/data/vendor_readers/Thermo/msvc-14.2/rls/adrs-mdl-64/async-excpt-on/lnk-sttc/thrd-mlt/libpwiz_reader_thermo.lib
    ${pwiz_LIB_PREFIX}/pwiz/data/vendor_readers/UIMF/msvc-14.2/rls/adrs-mdl-64/async-excpt-on/lnk-sttc/thrd-mlt/libpwiz_reader_uimf.lib
    ${pwiz_LIB_PREFIX}/pwiz/data/vendor_readers/UNIFI/msvc-14.2/rls/adrs-mdl-64/async-excpt-on/lnk-sttc/thrd-mlt/libpwiz_reader_unifi.lib
    ${pwiz_LIB_PREFIX}/pwiz/data/vendor_readers/Waters/msvc-14.2/rls/adrs-mdl-64/async-excpt-on/lnk-sttc/thrd-mlt/libpwiz_reader_waters.lib
    ${pwiz_LIB_PREFIX}/pwiz/msvc-14.2/rls/adrs-mdl-64/async-excpt-on/lnk-sttc/thrd-mlt/libpwiz_version.lib
    ${pwiz_LIB_PREFIX}/pwiz/utility/chemistry/msvc-14.2/rls/adrs-mdl-64/async-excpt-on/lnk-sttc/thrd-mlt/libpwiz_utility_chemistry.lib
    ${pwiz_LIB_PREFIX}/pwiz/utility/math/msvc-14.2/rls/adrs-mdl-64/async-excpt-on/lnk-sttc/thrd-mlt/libpwiz_utility_math.lib
    ${pwiz_LIB_PREFIX}/pwiz/utility/minimxml/msvc-14.2/rls/adrs-mdl-64/async-excpt-on/lnk-sttc/thrd-mlt/libpwiz_utility_minimxml.lib
    ${pwiz_LIB_PREFIX}/pwiz/utility/misc/msvc-14.2/rls/adrs-mdl-64/async-excpt-on/lnk-sttc/thrd-mlt/libpwiz_utility_image.lib
    ${pwiz_LIB_PREFIX}/pwiz/utility/misc/msvc-14.2/rls/adrs-mdl-64/async-excpt-on/lnk-sttc/thrd-mlt/libpwiz_utility_misc.lib
    ${pwiz_LIB_PREFIX}/pwiz/utility/misc/msvc-14.2/rls/adrs-mdl-64/async-excpt-on/lnk-sttc/thrd-mlt/libpwiz_utility_vendor_reader_test_harness.lib
    ${pwiz_LIB_PREFIX}/pwiz/utility/misc/msvc-14.2/rls/adrs-mdl-64/async-excpt-on/lnk-sttc/thrd-mlt/libSHA1.lib
    ${pwiz_LIB_PREFIX}/pwiz_aux/msrc/utility/vendor_api/Agilent/msvc-14.2/rls/adrs-mdl-64/lnk-sttc/thrd-mlt/us-clr-tr/libpwiz_vendor_api_agilent.lib
    ${pwiz_LIB_PREFIX}/pwiz_aux/msrc/utility/vendor_api/thermo/msvc-14.2/rls/adrs-mdl-64/lnk-sttc/thrd-mlt/us-clr-tr/libpwiz_vendor_api_thermo.lib
    ${pwiz_LIB_PREFIX}/pwiz_aux/msrc/utility/vendor_api/UIMF/msvc-14.2/rls/adrs-mdl-64/lnk-sttc/thrd-mlt/us-clr-tr/libpwiz_vendor_api_uimf.lib
    ${pwiz_LIB_PREFIX}/pwiz_aux/msrc/utility/vendor_api/UNIFI/msvc-14.2/rls/adrs-mdl-64/lnk-sttc/thrd-mlt/us-clr-tr/libpwiz_vendor_api_unifi.lib
    ${pwiz_LIB_PREFIX}/pwiz_tools/commandline/msvc-14.2/rls/adrs-mdl-64/async-excpt-on/lnk-sttc/thrd-mlt/msconvert.lib
    ${pwiz_LIB_PREFIX}/pwiz_tools/common/msvc-14.2/rls/adrs-mdl-64/async-excpt-on/lnk-sttc/thrd-mlt/libpwiz_tools_common.lib
    ${pwiz_LIB_PREFIX}/standalone/libpng/msvc-14.2/rls/adrs-mdl-64/async-excpt-on/lnk-sttc/thrd-mlt/libpng.lib
    ${pwiz_LIB_PREFIX}/standalone/zlib/msvc-14.2/rls/adrs-mdl-64/async-excpt-on/lnk-sttc/thrd-mlt/libzlib.lib
    )

set(pwiz_REDISTR_DEBUG
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/agtsampleinforw.dll
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/BaseCommon.dll
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/BaseDataAccess.dll
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/BaseError.dll
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/BaseTof.dll
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/IdentityModel.dll
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/Interop.DataExplorer.dll
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/MassSpecDataReader.dll
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/mfc90.dll
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/MIDAC.dll
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/Newtonsoft.Json.dll
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/ParallelExtensionsExtras.dll
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/System.Data.SQLite.dll
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/System.Runtime.Caching.Generic.dll
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/ThermoFisher.CommonCore.Data.dll
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/ThermoFisher.CommonCore.RawFileReader.dll
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/UIMFLibrary.dll
    ${pwiz_LIB_PREFIX}/msvc-debug-x86_64/unifi-protobuf-net.dll
    )

set(pwiz_REDISTR_RELEASE
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/agtsampleinforw.dll
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/BaseCommon.dll
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/BaseDataAccess.dll
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/BaseError.dll
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/BaseTof.dll
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/IdentityModel.dll
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/Interop.DataExplorer.dll
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/MassSpecDataReader.dll
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/mfc90.dll
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/MIDAC.dll
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/Newtonsoft.Json.dll
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/ParallelExtensionsExtras.dll
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/System.Data.SQLite.dll
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/System.Runtime.Caching.Generic.dll
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/ThermoFisher.CommonCore.Data.dll
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/ThermoFisher.CommonCore.RawFileReader.dll
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/UIMFLibrary.dll
    ${pwiz_LIB_PREFIX}/msvc-release-x86_64/unifi-protobuf-net.dll
    )

if (CMAKE_BUILD_TYPE STREQUAL "Debug")
    set(pwiz_LIBS ${pwiz_LIBS_DEBUG})
    set(pwiz_REDISTR ${pwiz_REDISTR_DEBUG})
else()
    set(pwiz_LIBS ${pwiz_LIBS_RELEASE})
    set(pwiz_REDISTR ${pwiz_REDISTR_RELEASE})
endif()
