set(pwiz_INCLUDE_DIRS
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_INCLUDE_DIR@
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_INCLUDE_DIR@/libraries/boost_1_76_0
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_INCLUDE_DIR@/libraries/boost_aux
    )

set(pwiz_LIBS_DEBUG
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_LIBS@/libboost_chrono-vc143-mt-gd.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_LIBS@/libboost_filesystem-vc143-mt-gd.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_LIBS@/libboost_iostreams-vc143-mt-gd.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_LIBS@/libboost_nowide-vc143-mt-gd.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_LIBS@/libboost_program_options-vc143-mt-gd.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_LIBS@/libboost_serialization-vc143-mt-gd.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_LIBS@/libboost_system-vc143-mt-gd.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_LIBS@/libboost_thread-vc143-mt-gd.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_LIBS@/libfreetype-vc143-mt-gd-2_4.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_LIBS@/libgd-vc143-mt-gd-2_1.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_LIBS@/libhdf5.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_LIBS@/libhdf5pp.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_LIBS@/libpng.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_LIBS@/libpwiz_analysis_chromatogram_processing.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_LIBS@/libpwiz_analysis_common.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_LIBS@/libpwiz_analysis_demux.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_LIBS@/libpwiz_analysis_demuxtestdata.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_LIBS@/libpwiz_analysis_diaumpire.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_LIBS@/libpwiz_analysis_frequency.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_LIBS@/libpwiz_analysis_passive.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_LIBS@/libpwiz_analysis_passive_core.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_LIBS@/libpwiz_analysis_peakdetect.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_LIBS@/libpwiz_analysis_peptideid.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_LIBS@/libpwiz_analysis_proteome_processing.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_LIBS@/libpwiz_analysis_spectrum_processing.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_LIBS@/libpwiz_analysis_spectrum_processing_basic.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_LIBS@/libpwiz_analysis_version.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_LIBS@/libpwiz_data_common.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_LIBS@/libpwiz_data_identdata.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_LIBS@/libpwiz_data_identdata_examples.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_LIBS@/libpwiz_data_identdata_version.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_LIBS@/libpwiz_data_misc.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_LIBS@/libpwiz_data_msdata.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_LIBS@/libpwiz_data_msdata_core.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_LIBS@/libpwiz_data_msdata_examples.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_LIBS@/libpwiz_data_msdata_mz5.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_LIBS@/libpwiz_data_msdata_mzmlb.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_LIBS@/libpwiz_data_msdata_version.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_LIBS@/libpwiz_data_obo.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_LIBS@/libpwiz_data_proteome.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_LIBS@/libpwiz_data_proteome_examples.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_LIBS@/libpwiz_data_proteome_version.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_LIBS@/libpwiz_data_tradata.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_LIBS@/libpwiz_data_tradata_examples.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_LIBS@/libpwiz_data_tradata_version.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_LIBS@/libpwiz_data_vendor_readers.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_LIBS@/libpwiz_reader_abi.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_LIBS@/libpwiz_reader_abi_t2d.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_LIBS@/libpwiz_reader_agilent.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_LIBS@/libpwiz_reader_bruker.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_LIBS@/libpwiz_reader_shimadzu.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_LIBS@/libpwiz_reader_thermo.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_LIBS@/libpwiz_reader_uimf.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_LIBS@/libpwiz_reader_unifi.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_LIBS@/libpwiz_reader_waters.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_LIBS@/libpwiz_tools_common.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_LIBS@/libpwiz_utility_chemistry.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_LIBS@/libpwiz_utility_image.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_LIBS@/libpwiz_utility_math.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_LIBS@/libpwiz_utility_minimxml.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_LIBS@/libpwiz_utility_misc.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_LIBS@/libpwiz_utility_vendor_reader_test_harness.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_LIBS@/libpwiz_vendor_api_abi.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_LIBS@/libpwiz_vendor_api_agilent.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_LIBS@/libpwiz_vendor_api_bruker.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_LIBS@/libpwiz_vendor_api_thermo.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_LIBS@/libpwiz_vendor_api_uimf.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_LIBS@/libpwiz_vendor_api_unifi.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_LIBS@/libpwiz_version.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_LIBS@/libSHA1.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_LIBS@/libsqlite3.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_LIBS@/libsqlite3pp.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_LIBS@/libsvm.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_LIBS@/libzlib.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_LIBS@/msconvert.lib
    )

set(pwiz_LIBS_RELEASE
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_LIBS@/libboost_chrono-vc143-mt.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_LIBS@/libboost_filesystem-vc143-mt.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_LIBS@/libboost_iostreams-vc143-mt.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_LIBS@/libboost_nowide-vc143-mt.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_LIBS@/libboost_program_options-vc143-mt.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_LIBS@/libboost_serialization-vc143-mt.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_LIBS@/libboost_system-vc143-mt.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_LIBS@/libboost_thread-vc143-mt.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_LIBS@/libfreetype-vc143-mt-2_4.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_LIBS@/libgd-vc143-mt-2_1.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_LIBS@/libhdf5.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_LIBS@/libhdf5pp.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_LIBS@/libpng.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_LIBS@/libpwiz_analysis_chromatogram_processing.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_LIBS@/libpwiz_analysis_common.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_LIBS@/libpwiz_analysis_demux.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_LIBS@/libpwiz_analysis_demuxtestdata.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_LIBS@/libpwiz_analysis_diaumpire.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_LIBS@/libpwiz_analysis_frequency.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_LIBS@/libpwiz_analysis_passive.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_LIBS@/libpwiz_analysis_passive_core.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_LIBS@/libpwiz_analysis_peakdetect.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_LIBS@/libpwiz_analysis_peptideid.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_LIBS@/libpwiz_analysis_proteome_processing.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_LIBS@/libpwiz_analysis_spectrum_processing.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_LIBS@/libpwiz_analysis_spectrum_processing_basic.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_LIBS@/libpwiz_analysis_version.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_LIBS@/libpwiz_data_common.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_LIBS@/libpwiz_data_identdata.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_LIBS@/libpwiz_data_identdata_examples.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_LIBS@/libpwiz_data_identdata_version.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_LIBS@/libpwiz_data_misc.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_LIBS@/libpwiz_data_msdata.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_LIBS@/libpwiz_data_msdata_core.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_LIBS@/libpwiz_data_msdata_examples.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_LIBS@/libpwiz_data_msdata_mz5.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_LIBS@/libpwiz_data_msdata_mzmlb.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_LIBS@/libpwiz_data_msdata_version.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_LIBS@/libpwiz_data_obo.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_LIBS@/libpwiz_data_proteome.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_LIBS@/libpwiz_data_proteome_examples.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_LIBS@/libpwiz_data_proteome_version.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_LIBS@/libpwiz_data_tradata.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_LIBS@/libpwiz_data_tradata_examples.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_LIBS@/libpwiz_data_tradata_version.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_LIBS@/libpwiz_data_vendor_readers.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_LIBS@/libpwiz_reader_abi.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_LIBS@/libpwiz_reader_abi_t2d.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_LIBS@/libpwiz_reader_agilent.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_LIBS@/libpwiz_reader_bruker.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_LIBS@/libpwiz_reader_shimadzu.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_LIBS@/libpwiz_reader_thermo.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_LIBS@/libpwiz_reader_uimf.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_LIBS@/libpwiz_reader_unifi.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_LIBS@/libpwiz_reader_waters.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_LIBS@/libpwiz_tools_common.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_LIBS@/libpwiz_utility_chemistry.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_LIBS@/libpwiz_utility_image.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_LIBS@/libpwiz_utility_math.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_LIBS@/libpwiz_utility_minimxml.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_LIBS@/libpwiz_utility_misc.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_LIBS@/libpwiz_utility_vendor_reader_test_harness.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_LIBS@/libpwiz_vendor_api_abi.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_LIBS@/libpwiz_vendor_api_agilent.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_LIBS@/libpwiz_vendor_api_bruker.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_LIBS@/libpwiz_vendor_api_thermo.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_LIBS@/libpwiz_vendor_api_uimf.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_LIBS@/libpwiz_vendor_api_unifi.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_LIBS@/libpwiz_version.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_LIBS@/libSHA1.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_LIBS@/libsqlite3.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_LIBS@/libsqlite3pp.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_LIBS@/libsvm.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_LIBS@/libzlib.lib
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_LIBS@/msconvert.lib
    )

set(pwiz_REDISTR_DEBUG
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_BIN@/agtsampleinforw.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_BIN@/api-ms-win-core-console-l1-1-0.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_BIN@/api-ms-win-core-datetime-l1-1-0.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_BIN@/api-ms-win-core-debug-l1-1-0.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_BIN@/api-ms-win-core-errorhandling-l1-1-0.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_BIN@/api-ms-win-core-file-l1-1-0.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_BIN@/api-ms-win-core-file-l1-2-0.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_BIN@/api-ms-win-core-file-l2-1-0.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_BIN@/api-ms-win-core-handle-l1-1-0.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_BIN@/api-ms-win-core-heap-l1-1-0.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_BIN@/api-ms-win-core-interlocked-l1-1-0.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_BIN@/api-ms-win-core-libraryloader-l1-1-0.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_BIN@/api-ms-win-core-localization-l1-2-0.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_BIN@/api-ms-win-core-memory-l1-1-0.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_BIN@/api-ms-win-core-namedpipe-l1-1-0.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_BIN@/api-ms-win-core-processenvironment-l1-1-0.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_BIN@/api-ms-win-core-processthreads-l1-1-0.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_BIN@/api-ms-win-core-processthreads-l1-1-1.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_BIN@/api-ms-win-core-profile-l1-1-0.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_BIN@/api-ms-win-core-rtlsupport-l1-1-0.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_BIN@/api-ms-win-core-string-l1-1-0.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_BIN@/api-ms-win-core-synch-l1-1-0.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_BIN@/api-ms-win-core-synch-l1-2-0.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_BIN@/api-ms-win-core-sysinfo-l1-1-0.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_BIN@/api-ms-win-core-timezone-l1-1-0.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_BIN@/api-ms-win-core-util-l1-1-0.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_BIN@/api-ms-win-crt-conio-l1-1-0.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_BIN@/api-ms-win-crt-convert-l1-1-0.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_BIN@/api-ms-win-crt-environment-l1-1-0.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_BIN@/api-ms-win-crt-filesystem-l1-1-0.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_BIN@/api-ms-win-crt-heap-l1-1-0.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_BIN@/api-ms-win-crt-locale-l1-1-0.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_BIN@/api-ms-win-crt-math-l1-1-0.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_BIN@/api-ms-win-crt-multibyte-l1-1-0.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_BIN@/api-ms-win-crt-private-l1-1-0.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_BIN@/api-ms-win-crt-process-l1-1-0.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_BIN@/api-ms-win-crt-runtime-l1-1-0.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_BIN@/api-ms-win-crt-stdio-l1-1-0.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_BIN@/api-ms-win-crt-string-l1-1-0.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_BIN@/api-ms-win-crt-time-l1-1-0.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_BIN@/api-ms-win-crt-utility-l1-1-0.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_BIN@/baf2sql_c.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_BIN@/BaseCommon.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_BIN@/BaseDataAccess.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_BIN@/BaseError.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_BIN@/BaseTof.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_BIN@/BDal.BCO.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_BIN@/BDal.BCO.Interfaces.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_BIN@/BDal.CCO.Calibration.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_BIN@/BDal.CCO.Interfaces.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_BIN@/BDal.CCO.TemperatureCompensation.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_BIN@/BDal.CCO.Transformation.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_BIN@/BDal.CCO.Utilities.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_BIN@/BDal.CXt.Lc.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_BIN@/BDal.CXt.Lc.Factory.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_BIN@/BDal.CXt.Lc.Interfaces.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_BIN@/BDal.CXt.Lc.UntU2.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_BIN@/boost_date_time-vc90-mt-1_37-x64-BDAL_20091123.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_BIN@/boost_regex-vc90-mt-1_37-x64-BDAL_20091123.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_BIN@/boost_system-vc90-mt-1_37-x64-BDAL_20091123.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_BIN@/boost_thread-vc90-mt-1_37-x64-BDAL_20091123.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_BIN@/cdt.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_BIN@/Clearcore2.Compression.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_BIN@/Clearcore2.Data.AnalystDataProvider.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_BIN@/Clearcore2.Data.Client.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_BIN@/Clearcore2.Data.CommonInterfaces.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_BIN@/Clearcore2.Data.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_BIN@/Clearcore2.Data.Wiff2.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_BIN@/Clearcore2.Data.WiffReader.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_BIN@/Clearcore2.Devices.Types.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_BIN@/Clearcore2.Domain.Acquisition.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_BIN@/Clearcore2.Infrastructure.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_BIN@/Clearcore2.InternalRawXYProcessing.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_BIN@/Clearcore2.Muni.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_BIN@/Clearcore2.RawXYProcessing.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_BIN@/Clearcore2.StructuredStorage.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_BIN@/Clearcore2.Utility.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_BIN@/Clearcore2.XmlHelpers.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_BIN@/CompassXtractMS.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_BIN@/Compressor_12451AC8-3BF1-48e1-8E66-DA05BF3852A0.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_BIN@/Compressor_382D5134-9727-4be6-B6F8-754F577426D6.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_BIN@/Compressor_4F1EA0CB-5A6A-43ED-9562-D6D873034577.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_BIN@/Compressor_6BB2E64A-27A0-4575-A66A-4E312C8B9AD7.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_BIN@/Compressor_6EEE649E-09AA-4332-8E82-8188652E8AB5.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_BIN@/Compressor_7F88E97F-2038-40ba-8F3A-FCA9A9719569.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_BIN@/HSReadWrite.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_BIN@/IdentityModel.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_BIN@/Interop.DataExplorer.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_BIN@/Interop.EDAL.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_BIN@/Interop.HSREADWRITELib.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_BIN@/MassLynxRaw.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_BIN@/MassSpecDataReader.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_BIN@/mfc90.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_BIN@/MIDAC.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_BIN@/mkl_sequential.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_BIN@/msvcm90.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_BIN@/msvcp110.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_BIN@/msvcp120.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_BIN@/msvcp140.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_BIN@/msvcp90.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_BIN@/msvcr110.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_BIN@/msvcr120.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_BIN@/msvcr90.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_BIN@/Newtonsoft.Json.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_BIN@/OFX.Core.Contracts.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_BIN@/ParallelExtensionsExtras.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_BIN@/protobuf-net.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_BIN@/SCIEX.Apis.Data.v1.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_BIN@/Sciex.Clearcore.FMan.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_BIN@/Sciex.Data.SimpleTypes.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_BIN@/Sciex.Data.XYData.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_BIN@/Sciex.FMan.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_BIN@/Sciex.Wiff.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_BIN@/SQLite.Interop.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_BIN@/System.Data.SQLite.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_BIN@/System.Runtime.Caching.Generic.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_BIN@/ThermoFisher.CommonCore.Data.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_BIN@/ThermoFisher.CommonCore.RawFileReader.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_BIN@/timsdata.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_BIN@/ucrtbase.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_BIN@/UIMFLibrary.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_BIN@/unifi-protobuf-net.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_BIN@/vcomp110.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_BIN@/vcomp140.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_BIN@/vcomp90.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_BIN@/vcruntime140.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_BIN@/vcruntime140_1.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_DEBUG_BIN@/msconvert.exe
    )

set(pwiz_REDISTR_RELEASE
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_BIN@/agtsampleinforw.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_BIN@/api-ms-win-core-console-l1-1-0.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_BIN@/api-ms-win-core-datetime-l1-1-0.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_BIN@/api-ms-win-core-debug-l1-1-0.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_BIN@/api-ms-win-core-errorhandling-l1-1-0.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_BIN@/api-ms-win-core-file-l1-1-0.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_BIN@/api-ms-win-core-file-l1-2-0.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_BIN@/api-ms-win-core-file-l2-1-0.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_BIN@/api-ms-win-core-handle-l1-1-0.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_BIN@/api-ms-win-core-heap-l1-1-0.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_BIN@/api-ms-win-core-interlocked-l1-1-0.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_BIN@/api-ms-win-core-libraryloader-l1-1-0.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_BIN@/api-ms-win-core-localization-l1-2-0.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_BIN@/api-ms-win-core-memory-l1-1-0.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_BIN@/api-ms-win-core-namedpipe-l1-1-0.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_BIN@/api-ms-win-core-processenvironment-l1-1-0.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_BIN@/api-ms-win-core-processthreads-l1-1-0.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_BIN@/api-ms-win-core-processthreads-l1-1-1.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_BIN@/api-ms-win-core-profile-l1-1-0.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_BIN@/api-ms-win-core-rtlsupport-l1-1-0.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_BIN@/api-ms-win-core-string-l1-1-0.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_BIN@/api-ms-win-core-synch-l1-1-0.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_BIN@/api-ms-win-core-synch-l1-2-0.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_BIN@/api-ms-win-core-sysinfo-l1-1-0.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_BIN@/api-ms-win-core-timezone-l1-1-0.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_BIN@/api-ms-win-core-util-l1-1-0.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_BIN@/api-ms-win-crt-conio-l1-1-0.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_BIN@/api-ms-win-crt-convert-l1-1-0.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_BIN@/api-ms-win-crt-environment-l1-1-0.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_BIN@/api-ms-win-crt-filesystem-l1-1-0.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_BIN@/api-ms-win-crt-heap-l1-1-0.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_BIN@/api-ms-win-crt-locale-l1-1-0.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_BIN@/api-ms-win-crt-math-l1-1-0.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_BIN@/api-ms-win-crt-multibyte-l1-1-0.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_BIN@/api-ms-win-crt-private-l1-1-0.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_BIN@/api-ms-win-crt-process-l1-1-0.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_BIN@/api-ms-win-crt-runtime-l1-1-0.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_BIN@/api-ms-win-crt-stdio-l1-1-0.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_BIN@/api-ms-win-crt-string-l1-1-0.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_BIN@/api-ms-win-crt-time-l1-1-0.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_BIN@/api-ms-win-crt-utility-l1-1-0.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_BIN@/baf2sql_c.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_BIN@/BaseCommon.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_BIN@/BaseDataAccess.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_BIN@/BaseError.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_BIN@/BaseTof.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_BIN@/BDal.BCO.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_BIN@/BDal.BCO.Interfaces.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_BIN@/BDal.CCO.Calibration.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_BIN@/BDal.CCO.Interfaces.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_BIN@/BDal.CCO.TemperatureCompensation.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_BIN@/BDal.CCO.Transformation.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_BIN@/BDal.CCO.Utilities.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_BIN@/BDal.CXt.Lc.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_BIN@/BDal.CXt.Lc.Factory.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_BIN@/BDal.CXt.Lc.Interfaces.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_BIN@/BDal.CXt.Lc.UntU2.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_BIN@/boost_date_time-vc90-mt-1_37-x64-BDAL_20091123.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_BIN@/boost_regex-vc90-mt-1_37-x64-BDAL_20091123.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_BIN@/boost_system-vc90-mt-1_37-x64-BDAL_20091123.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_BIN@/boost_thread-vc90-mt-1_37-x64-BDAL_20091123.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_BIN@/cdt.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_BIN@/Clearcore2.Compression.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_BIN@/Clearcore2.Data.AnalystDataProvider.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_BIN@/Clearcore2.Data.Client.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_BIN@/Clearcore2.Data.CommonInterfaces.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_BIN@/Clearcore2.Data.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_BIN@/Clearcore2.Data.Wiff2.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_BIN@/Clearcore2.Data.WiffReader.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_BIN@/Clearcore2.Devices.Types.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_BIN@/Clearcore2.Domain.Acquisition.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_BIN@/Clearcore2.Infrastructure.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_BIN@/Clearcore2.InternalRawXYProcessing.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_BIN@/Clearcore2.Muni.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_BIN@/Clearcore2.RawXYProcessing.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_BIN@/Clearcore2.StructuredStorage.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_BIN@/Clearcore2.Utility.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_BIN@/Clearcore2.XmlHelpers.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_BIN@/CompassXtractMS.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_BIN@/Compressor_12451AC8-3BF1-48e1-8E66-DA05BF3852A0.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_BIN@/Compressor_382D5134-9727-4be6-B6F8-754F577426D6.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_BIN@/Compressor_4F1EA0CB-5A6A-43ED-9562-D6D873034577.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_BIN@/Compressor_6BB2E64A-27A0-4575-A66A-4E312C8B9AD7.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_BIN@/Compressor_6EEE649E-09AA-4332-8E82-8188652E8AB5.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_BIN@/Compressor_7F88E97F-2038-40ba-8F3A-FCA9A9719569.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_BIN@/HSReadWrite.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_BIN@/IdentityModel.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_BIN@/Interop.DataExplorer.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_BIN@/Interop.EDAL.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_BIN@/Interop.HSREADWRITELib.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_BIN@/MassLynxRaw.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_BIN@/MassSpecDataReader.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_BIN@/mfc90.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_BIN@/MIDAC.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_BIN@/mkl_sequential.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_BIN@/msvcm90.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_BIN@/msvcp110.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_BIN@/msvcp120.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_BIN@/msvcp140.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_BIN@/msvcp90.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_BIN@/msvcr110.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_BIN@/msvcr120.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_BIN@/msvcr90.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_BIN@/Newtonsoft.Json.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_BIN@/OFX.Core.Contracts.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_BIN@/ParallelExtensionsExtras.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_BIN@/protobuf-net.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_BIN@/SCIEX.Apis.Data.v1.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_BIN@/Sciex.Clearcore.FMan.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_BIN@/Sciex.Data.SimpleTypes.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_BIN@/Sciex.Data.XYData.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_BIN@/Sciex.FMan.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_BIN@/Sciex.Wiff.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_BIN@/SQLite.Interop.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_BIN@/System.Data.SQLite.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_BIN@/System.Runtime.Caching.Generic.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_BIN@/ThermoFisher.CommonCore.Data.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_BIN@/ThermoFisher.CommonCore.RawFileReader.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_BIN@/timsdata.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_BIN@/ucrtbase.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_BIN@/UIMFLibrary.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_BIN@/unifi-protobuf-net.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_BIN@/vcomp110.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_BIN@/vcomp140.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_BIN@/vcomp90.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_BIN@/vcruntime140.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_BIN@/vcruntime140_1.dll
    ${CMAKE_CURRENT_LIST_DIR}/@VCPKG_RELEASE_BIN@/msconvert.exe
    )

if (CMAKE_BUILD_TYPE STREQUAL "Debug")
    set(pwiz_LIBS ${pwiz_LIBS_DEBUG})
    set(pwiz_REDISTR ${pwiz_REDISTR_DEBUG})
else()
    set(pwiz_LIBS ${pwiz_LIBS_RELEASE})
    set(pwiz_REDISTR ${pwiz_REDISTR_RELEASE})
endif()
