// Port of pwiz_tools/BiblioSpec/src/SQTversion.{h,cpp}
//
// Detect the dialect of an SQT file (SEQUEST vs Comet, with version numbers).
// Used by SQTreader to decide whether StaticMod values in the header are
// "residue mass + modification" (older SEQUEST <= 2.7) or "modification mass alone"
// (Comet, or newer SEQUEST).

using System.Globalization;
using System.Text.RegularExpressions;

namespace Pwiz.Tools.BiblioSpec;

/// <summary>
/// Abstract base for SQT-file version detection. Concrete subclasses
/// (<see cref="SequestVersion"/>, <see cref="CometVersion"/>) parse a version string
/// out of an SQT header and support ordered comparison so the reader can branch on
/// "newer / older than 2.7" style cutoffs.
/// </summary>
/// <remarks>
/// Port of <c>BiblioSpec::SQTversion</c> (SQTversion.h:31). The cpp class hierarchy
/// uses RTTI (<c>typeid</c>) to refuse comparisons across generators (Sequest vs Comet);
/// the C# port mirrors that with runtime type checks.
/// </remarks>
public abstract class SQTversion : IComparable<SQTversion>, IEquatable<SQTversion>
{
    /// <summary>Try to parse the given string into this version object.</summary>
    /// <returns>True on success, false if the string is not a valid version for this dialect.</returns>
    /// <remarks>cpp parity: SQTversion.h:35.</remarks>
    public abstract bool TrySetVersion(string versionString);

    /// <summary>Name of the search-engine generator, e.g. "Sequest" or "Comet".</summary>
    /// <remarks>cpp parity: SQTversion.h:42.</remarks>
    public abstract string GeneratorName { get; }

    /// <summary>
    /// Compare two SQT versions of the same dialect. Throws <see cref="BlibException"/>
    /// if compared across dialects, mirroring cpp's <c>typeid</c> guard.
    /// </summary>
    /// <remarks>cpp parity: SQTversion.cpp:73 (Sequest), 143 (Comet).</remarks>
    public abstract int CompareTo(SQTversion? other);

    /// <inheritdoc/>
    public abstract bool Equals(SQTversion? other);

    /// <inheritdoc/>
    public override bool Equals(object? obj) => obj is SQTversion other && Equals(other);

    /// <inheritdoc/>
    public override int GetHashCode() => HashCode.Combine(GeneratorName);

    /// <summary>cpp parity: <c>operator&lt;</c>.</summary>
    public static bool operator <(SQTversion left, SQTversion right) => Compare(left, right) < 0;
    /// <summary>cpp parity: <c>operator&gt;</c>.</summary>
    public static bool operator >(SQTversion left, SQTversion right) => Compare(left, right) > 0;
    /// <summary>cpp parity: <c>operator&lt;=</c>.</summary>
    public static bool operator <=(SQTversion left, SQTversion right) => Compare(left, right) <= 0;
    /// <summary>cpp parity: <c>operator&gt;=</c>.</summary>
    public static bool operator >=(SQTversion left, SQTversion right) => Compare(left, right) >= 0;
    /// <summary>cpp parity: <c>operator==</c>.</summary>
    public static bool operator ==(SQTversion? left, SQTversion? right)
    {
        if (ReferenceEquals(left, right)) return true;
        if (left is null || right is null) return false;
        return left.Equals(right);
    }
    /// <summary>cpp parity: <c>operator!=</c>.</summary>
    public static bool operator !=(SQTversion? left, SQTversion? right) => !(left == right);

    private static int Compare(SQTversion left, SQTversion right)
    {
        ArgumentNullException.ThrowIfNull(left);
        ArgumentNullException.ThrowIfNull(right);
        return left.CompareTo(right);
    }
}

/// <summary>
/// SQT version generated by SEQUEST. Parses "MAJOR[.MINOR]" with trailing whitespace.
/// </summary>
/// <remarks>cpp parity: SQTversion.h:45.</remarks>
public sealed class SequestVersion : SQTversion
{
    // cpp parity: SQTversion.cpp:34 — regex "^(?P<major>[0-9]+)([.](?P<minor>[0-9]+))?[[:blank:]]*$".
    // boost::xpressive's [[:blank:]] is space+tab; .NET's \p{Zs} differs; we use a manual class.
    private static readonly Regex _versionParser = new(
        @"^(?<major>[0-9]+)([.](?<minor>[0-9]+))?[ \t]*$",
        RegexOptions.Compiled | RegexOptions.CultureInvariant);

    private int _majorVersion;
    private int _minorVersion;

    /// <summary>Construct an unset SequestVersion (major=0, minor=0).</summary>
    /// <remarks>cpp parity: SQTversion.cpp:31.</remarks>
    public SequestVersion()
    {
    }

    /// <summary>Construct a SequestVersion by parsing the given version string.</summary>
    /// <remarks>cpp parity: SQTversion.cpp:37.</remarks>
    /// <exception cref="BlibException">If the version string is not a valid SEQUEST version.</exception>
    public SequestVersion(string versionString)
    {
        if (!TrySetVersion(versionString))
        {
            throw new BlibException(false,
                $"Error initializing with an improperly formatted sequest version string: {versionString}");
        }
    }

    /// <inheritdoc/>
    public override string GeneratorName => "Sequest";

    /// <inheritdoc/>
    public override bool TrySetVersion(string versionString)
    {
        // cpp parity: SQTversion.cpp:46.
        if (string.IsNullOrEmpty(versionString))
            return false;

        var match = _versionParser.Match(versionString);
        if (!match.Success)
            return false;

        _majorVersion = 0;
        _minorVersion = 0;
        // cpp parity: SQTversion.cpp:62-69 — atoi("") is 0; only assign when the captured group has content.
        if (match.Groups["major"].Length > 0)
            _majorVersion = int.Parse(match.Groups["major"].Value, CultureInfo.InvariantCulture);
        if (match.Groups["minor"].Length > 0)
            _minorVersion = int.Parse(match.Groups["minor"].Value, CultureInfo.InvariantCulture);
        return true;
    }

    /// <inheritdoc/>
    public override int CompareTo(SQTversion? other)
    {
        // cpp parity: SQTversion.cpp:73 — typeid mismatch throws BlibException.
        if (other is null)
            return 1;
        if (other is not SequestVersion rhs)
        {
            throw new BlibException(false,
                "Tried to compare an SQT version between a file generated from sequest, and a file"
                + "generated by a different software");
        }
        if (_majorVersion == rhs._majorVersion)
            return _minorVersion.CompareTo(rhs._minorVersion);
        return _majorVersion.CompareTo(rhs._majorVersion);
    }

    /// <inheritdoc/>
    public override bool Equals(SQTversion? other)
    {
        if (other is null)
            return false;
        // cpp parity: SQTversion.cpp:86 — typeid mismatch throws BlibException.
        if (other is not SequestVersion rhs)
        {
            throw new BlibException(false,
                "Tried to compare an SQT version between a file generated from sequest, and a file"
                + "generated by a different software");
        }
        return _majorVersion == rhs._majorVersion && _minorVersion == rhs._minorVersion;
    }

    /// <inheritdoc/>
    public override int GetHashCode() => HashCode.Combine(GeneratorName, _majorVersion, _minorVersion);
}

/// <summary>
/// SQT version generated by Comet. Parses "MAJOR[.MINOR] [rev. REV]" with trailing whitespace.
/// </summary>
/// <remarks>cpp parity: SQTversion.h:59.</remarks>
public sealed class CometVersion : SQTversion
{
    // cpp parity: SQTversion.cpp:100 — regex
    // "^(?P<major>[0-9]+)([.](?P<minor>[0-9]+))?[[:blank:]]*(rev[.][[:blank:]]*(?P<rev>[0-9]+)?)?[[:blank:]]*$".
    private static readonly Regex _versionParser = new(
        @"^(?<major>[0-9]+)([.](?<minor>[0-9]+))?[ \t]*(rev[.][ \t]*(?<rev>[0-9]+)?)?[ \t]*$",
        RegexOptions.Compiled | RegexOptions.CultureInvariant);

    private int _majorVersion;
    private int _minorVersion;
    private int _revision;

    /// <summary>Construct an unset CometVersion (major=0, minor=0, revision=0).</summary>
    /// <remarks>cpp parity: SQTversion.cpp:97.</remarks>
    public CometVersion()
    {
    }

    /// <summary>Construct a CometVersion by parsing the given version string.</summary>
    /// <remarks>cpp parity: SQTversion.cpp:103.</remarks>
    /// <exception cref="BlibException">If the version string is not a valid Comet version.</exception>
    public CometVersion(string versionString)
    {
        if (!TrySetVersion(versionString))
        {
            throw new BlibException(false,
                $"Error initializing with an improperly formatted comet version string: {versionString}");
        }
    }

    /// <inheritdoc/>
    public override string GeneratorName => "Comet";

    /// <inheritdoc/>
    public override bool TrySetVersion(string versionString)
    {
        // cpp parity: SQTversion.cpp:112.
        if (string.IsNullOrEmpty(versionString))
            return false;

        var match = _versionParser.Match(versionString);
        if (!match.Success)
            return false;

        _majorVersion = 0;
        _minorVersion = 0;
        _revision = 0;
        if (match.Groups["major"].Length > 0)
            _majorVersion = int.Parse(match.Groups["major"].Value, CultureInfo.InvariantCulture);
        if (match.Groups["minor"].Length > 0)
            _minorVersion = int.Parse(match.Groups["minor"].Value, CultureInfo.InvariantCulture);
        if (match.Groups["rev"].Length > 0)
            _revision = int.Parse(match.Groups["rev"].Value, CultureInfo.InvariantCulture);
        return true;
    }

    /// <inheritdoc/>
    public override int CompareTo(SQTversion? other)
    {
        // cpp parity: SQTversion.cpp:143.
        if (other is null)
            return 1;
        if (other is not CometVersion rhs)
        {
            throw new BlibException(false,
                "Tried to compare an SQT version between a file generated from comet, and a file"
                + "generated by a different software");
        }
        if (_majorVersion == rhs._majorVersion)
        {
            if (_minorVersion == rhs._minorVersion)
                return _revision.CompareTo(rhs._revision);
            return _minorVersion.CompareTo(rhs._minorVersion);
        }
        return _majorVersion.CompareTo(rhs._majorVersion);
    }

    /// <inheritdoc/>
    public override bool Equals(SQTversion? other)
    {
        if (other is null)
            return false;
        // cpp parity: SQTversion.cpp:160.
        if (other is not CometVersion rhs)
        {
            throw new BlibException(false,
                "Tried to compare an SQT version between a file generated from comet, and a file"
                + "generated by a different software");
        }
        return _majorVersion == rhs._majorVersion
            && _minorVersion == rhs._minorVersion
            && _revision == rhs._revision;
    }

    /// <inheritdoc/>
    public override int GetHashCode() =>
        HashCode.Combine(GeneratorName, _majorVersion, _minorVersion, _revision);
}
