//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pwiz.Skyline.Model.AuditLog {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EnumNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EnumNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("pwiz.Skyline.Model.AuditLog.EnumNames", typeof(EnumNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        public static string AnnotationType_number {
            get {
                return ResourceManager.GetString("AnnotationType_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string AnnotationType_text {
            get {
                return ResourceManager.GetString("AnnotationType_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True/False.
        /// </summary>
        public static string AnnotationType_true_false {
            get {
                return ResourceManager.GetString("AnnotationType_true_false", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value List.
        /// </summary>
        public static string AnnotationType_value_list {
            get {
                return ResourceManager.GetString("AnnotationType_value_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precursors.
        /// </summary>
        public static string AreaCVMsLevel_precursors {
            get {
                return ResourceManager.GetString("AreaCVMsLevel_precursors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        public static string AreaCVMsLevel_products {
            get {
                return ResourceManager.GetString("AreaCVMsLevel_products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Standards.
        /// </summary>
        public static string AreaCVNormalizationMethod_global_standards {
            get {
                return ResourceManager.GetString("AreaCVNormalizationMethod_global_standards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medians.
        /// </summary>
        public static string AreaCVNormalizationMethod_medians {
            get {
                return ResourceManager.GetString("AreaCVNormalizationMethod_medians", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string AreaCVNormalizationMethod_none {
            get {
                return ResourceManager.GetString("AreaCVNormalizationMethod_none", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ratio.
        /// </summary>
        public static string AreaCVNormalizationMethod_ratio {
            get {
                return ResourceManager.GetString("AreaCVNormalizationMethod_ratio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Ion Current.
        /// </summary>
        public static string AreaCVNormalizationMethod_tic {
            get {
                return ResourceManager.GetString("AreaCVNormalizationMethod_tic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string AreaCVTransitions_all {
            get {
                return ResourceManager.GetString("AreaCVTransitions_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best.
        /// </summary>
        public static string AreaCVTransitions_best {
            get {
                return ResourceManager.GetString("AreaCVTransitions_best", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        public static string AreaCVTransitions_count {
            get {
                return ResourceManager.GetString("AreaCVTransitions_count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilinear.
        /// </summary>
        public static string BilinearFit_bilinear {
            get {
                return ResourceManager.GetString("BilinearFit_bilinear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chebyshev.
        /// </summary>
        public static string ClusterMetricType_chebyshev {
            get {
                return ResourceManager.GetString("ClusterMetricType_chebyshev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Euclidean.
        /// </summary>
        public static string ClusterMetricType_euclidean {
            get {
                return ResourceManager.GetString("ClusterMetricType_euclidean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City block.
        /// </summary>
        public static string ClusterMetricType_manhattan {
            get {
                return ResourceManager.GetString("ClusterMetricType_manhattan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pearson.
        /// </summary>
        public static string ClusterMetricType_pearson {
            get {
                return ResourceManager.GetString("ClusterMetricType_pearson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        public static string CountImpl_Count {
            get {
                return ResourceManager.GetString("CountImpl_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 ion.
        /// </summary>
        public static string DeltaFragmentFinder_1_ion {
            get {
                return ResourceManager.GetString("DeltaFragmentFinder_1_ion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 ions.
        /// </summary>
        public static string DeltaFragmentFinder_2_ions {
            get {
                return ResourceManager.GetString("DeltaFragmentFinder_2_ions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 ions.
        /// </summary>
        public static string DeltaFragmentFinder_3_ions {
            get {
                return ResourceManager.GetString("DeltaFragmentFinder_3_ions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4 ions.
        /// </summary>
        public static string DeltaFragmentFinder_4_ions {
            get {
                return ResourceManager.GetString("DeltaFragmentFinder_4_ions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 ions.
        /// </summary>
        public static string DeltaFragmentFinder_5_ions {
            get {
                return ResourceManager.GetString("DeltaFragmentFinder_5_ions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6 ions.
        /// </summary>
        public static string DeltaFragmentFinder_6_ions {
            get {
                return ResourceManager.GetString("DeltaFragmentFinder_6_ions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compensation Voltage (V).
        /// </summary>
        public static string eIonMobilityUnits_compensation_V {
            get {
                return ResourceManager.GetString("eIonMobilityUnits_compensation_V", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drift Time (ms).
        /// </summary>
        public static string eIonMobilityUnits_drift_time_msec {
            get {
                return ResourceManager.GetString("eIonMobilityUnits_drift_time_msec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1/K0 (Vs/cm^2).
        /// </summary>
        public static string eIonMobilityUnits_inverse_K0_Vsec_per_cm2 {
            get {
                return ResourceManager.GetString("eIonMobilityUnits_inverse_K0_Vsec_per_cm2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string eIonMobilityUnits_none {
            get {
                return ResourceManager.GetString("eIonMobilityUnits_none", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string eIonMobilityUnits_unknown {
            get {
                return ResourceManager.GetString("eIonMobilityUnits_unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waters SONAR.
        /// </summary>
        public static string eIonMobilityUnits_waters_sonar {
            get {
                return ResourceManager.GetString("eIonMobilityUnits_waters_sonar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DDA.
        /// </summary>
        public static string FullScanAcquisitionMethod_DDA {
            get {
                return ResourceManager.GetString("FullScanAcquisitionMethod_DDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DIA.
        /// </summary>
        public static string FullScanAcquisitionMethod_DIA {
            get {
                return ResourceManager.GetString("FullScanAcquisitionMethod_DIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string FullScanAcquisitionMethod_None {
            get {
                return ResourceManager.GetString("FullScanAcquisitionMethod_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRM.
        /// </summary>
        public static string FullScanAcquisitionMethod_PRM {
            get {
                return ResourceManager.GetString("FullScanAcquisitionMethod_PRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SureQuant.
        /// </summary>
        public static string FullScanAcquisitionMethod_SureQuant {
            get {
                return ResourceManager.GetString("FullScanAcquisitionMethod_SureQuant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Targeted (obsolete).
        /// </summary>
        public static string FullScanAcquisitionMethod_Targeted {
            get {
                return ResourceManager.GetString("FullScanAcquisitionMethod_Targeted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centroided.
        /// </summary>
        public static string FullScanMassAnalyzerType_centroided {
            get {
                return ResourceManager.GetString("FullScanMassAnalyzerType_centroided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FT-ICR.
        /// </summary>
        public static string FullScanMassAnalyzerType_ft_icr {
            get {
                return ResourceManager.GetString("FullScanMassAnalyzerType_ft_icr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string FullScanMassAnalyzerType_none {
            get {
                return ResourceManager.GetString("FullScanMassAnalyzerType_none", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orbitrap.
        /// </summary>
        public static string FullScanMassAnalyzerType_orbitrap {
            get {
                return ResourceManager.GetString("FullScanMassAnalyzerType_orbitrap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QIT.
        /// </summary>
        public static string FullScanMassAnalyzerType_qit {
            get {
                return ResourceManager.GetString("FullScanMassAnalyzerType_qit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOF.
        /// </summary>
        public static string FullScanMassAnalyzerType_tof {
            get {
                return ResourceManager.GetString("FullScanMassAnalyzerType_tof", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        public static string FullScanPrecursorIsotopes_Count {
            get {
                return ResourceManager.GetString("FullScanPrecursorIsotopes_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string FullScanPrecursorIsotopes_None {
            get {
                return ResourceManager.GetString("FullScanPrecursorIsotopes_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percent.
        /// </summary>
        public static string FullScanPrecursorIsotopes_Percent {
            get {
                return ResourceManager.GetString("FullScanPrecursorIsotopes_Percent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small.
        /// </summary>
        public static string GraphFontSize_10 {
            get {
                return ResourceManager.GetString("GraphFontSize_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string GraphFontSize_12 {
            get {
                return ResourceManager.GetString("GraphFontSize_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Large.
        /// </summary>
        public static string GraphFontSize_14 {
            get {
                return ResourceManager.GetString("GraphFontSize_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X-Large.
        /// </summary>
        public static string GraphFontSize_16 {
            get {
                return ResourceManager.GetString("GraphFontSize_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X-Small.
        /// </summary>
        public static string GraphFontSize_8 {
            get {
                return ResourceManager.GetString("GraphFontSize_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Many.
        /// </summary>
        public static string ImportResultsSimultaneousFileOptions_many {
            get {
                return ResourceManager.GetString("ImportResultsSimultaneousFileOptions_many", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One at a time.
        /// </summary>
        public static string ImportResultsSimultaneousFileOptions_one_at_a_time {
            get {
                return ResourceManager.GetString("ImportResultsSimultaneousFileOptions_one_at_a_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Several.
        /// </summary>
        public static string ImportResultsSimultaneousFileOptions_several {
            get {
                return ResourceManager.GetString("ImportResultsSimultaneousFileOptions_several", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DDA raw (search and build library).
        /// </summary>
        public static string InputFile_dda_raw {
            get {
                return ResourceManager.GetString("InputFile_dda_raw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DIA raw (deconvolute, search, and build library).
        /// </summary>
        public static string InputFile_dia_raw {
            get {
                return ResourceManager.GetString("InputFile_dia_raw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search results (build library directly).
        /// </summary>
        public static string InputFile_search_result {
            get {
                return ResourceManager.GetString("InputFile_search_result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orbitrap LTQ.
        /// </summary>
        public static string InstrumentPreset_OrbitrapLTQ {
            get {
                return ResourceManager.GetString("InstrumentPreset_OrbitrapLTQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Q Exactive.
        /// </summary>
        public static string InstrumentPreset_QExactive {
            get {
                return ResourceManager.GetString("InstrumentPreset_QExactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TripleTOF.
        /// </summary>
        public static string InstrumentPreset_TripleTOF {
            get {
                return ResourceManager.GetString("InstrumentPreset_TripleTOF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed width.
        /// </summary>
        public static string IonMobilityWindowWidthType_fixed_width {
            get {
                return ResourceManager.GetString("IonMobilityWindowWidthType_fixed_width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linear range.
        /// </summary>
        public static string IonMobilityWindowWidthType_linear_range {
            get {
                return ResourceManager.GetString("IonMobilityWindowWidthType_linear_range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string IonMobilityWindowWidthType_none {
            get {
                return ResourceManager.GetString("IonMobilityWindowWidthType_none", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolving power.
        /// </summary>
        public static string IonMobilityWindowWidthType_resolving_power {
            get {
                return ResourceManager.GetString("IonMobilityWindowWidthType_resolving_power", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linear.
        /// </summary>
        public static string IrtRegressionType_linear {
            get {
                return ResourceManager.GetString("IrtRegressionType_linear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logarithmic.
        /// </summary>
        public static string IrtRegressionType_logarithmic {
            get {
                return ResourceManager.GetString("IrtRegressionType_logarithmic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lowess.
        /// </summary>
        public static string IrtRegressionType_lowess {
            get {
                return ResourceManager.GetString("IrtRegressionType_lowess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed.
        /// </summary>
        public static string IsolationWidthType_fixed_width {
            get {
                return ResourceManager.GetString("IsolationWidthType_fixed_width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string IsolationWidthType_none {
            get {
                return ResourceManager.GetString("IsolationWidthType_none", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        public static string IsolationWidthType_results {
            get {
                return ResourceManager.GetString("IsolationWidthType_results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results with margin.
        /// </summary>
        public static string IsolationWidthType_results_with_margin {
            get {
                return ResourceManager.GetString("IsolationWidthType_results_with_margin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to last ion.
        /// </summary>
        public static string LastFragmentFinder_last_ion {
            get {
                return ResourceManager.GetString("LastFragmentFinder_last_ion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to last ion - 1.
        /// </summary>
        public static string LastFragmentFinder_last_ion__minus__1 {
            get {
                return ResourceManager.GetString("LastFragmentFinder_last_ion__minus__1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to last ion - 2.
        /// </summary>
        public static string LastFragmentFinder_last_ion__minus__2 {
            get {
                return ResourceManager.GetString("LastFragmentFinder_last_ion__minus__2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to last ion - 3.
        /// </summary>
        public static string LastFragmentFinder_last_ion__minus__3 {
            get {
                return ResourceManager.GetString("LastFragmentFinder_last_ion__minus__3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linear in Log Space.
        /// </summary>
        public static string LinearInLogSpace_linear_in_log_space {
            get {
                return ResourceManager.GetString("LinearInLogSpace_linear_in_log_space", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ascending.
        /// </summary>
        public static string ListSortDirection_Ascending {
            get {
                return ResourceManager.GetString("ListSortDirection_Ascending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descending.
        /// </summary>
        public static string ListSortDirection_Descending {
            get {
                return ResourceManager.GetString("ListSortDirection_Descending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blank plus 2 * SD.
        /// </summary>
        public static string LodCalculation_blank_plus_2_sd {
            get {
                return ResourceManager.GetString("LodCalculation_blank_plus_2_sd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blank plus 3 * SD.
        /// </summary>
        public static string LodCalculation_blank_plus_3_sd {
            get {
                return ResourceManager.GetString("LodCalculation_blank_plus_3_sd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string LodCalculation_none {
            get {
                return ResourceManager.GetString("LodCalculation_none", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilinear turning point.
        /// </summary>
        public static string LodCalculation_turning_point {
            get {
                return ResourceManager.GetString("LodCalculation_turning_point", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always.
        /// </summary>
        public static string LossInclusion_Always {
            get {
                return ResourceManager.GetString("LossInclusion_Always", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matching Library.
        /// </summary>
        public static string LossInclusion_Library {
            get {
                return ResourceManager.GetString("LossInclusion_Library", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never.
        /// </summary>
        public static string LossInclusion_Never {
            get {
                return ResourceManager.GetString("LossInclusion_Never", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average.
        /// </summary>
        public static string MassType_Average {
            get {
                return ResourceManager.GetString("MassType_Average", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monoisotopic.
        /// </summary>
        public static string MassType_Monoisotopic {
            get {
                return ResourceManager.GetString("MassType_Monoisotopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C.
        /// </summary>
        public static string ModTerminus_C {
            get {
                return ResourceManager.GetString("ModTerminus_C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N.
        /// </summary>
        public static string ModTerminus_N {
            get {
                return ResourceManager.GetString("ModTerminus_N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (m/z &gt; precursor) - 1.
        /// </summary>
        public static string MzFragmentFinder__m_z__gt__precursor___minus__1 {
            get {
                return ResourceManager.GetString("MzFragmentFinder__m_z__gt__precursor___minus__1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (m/z &gt; precursor) - 2.
        /// </summary>
        public static string MzFragmentFinder__m_z__gt__precursor___minus__2 {
            get {
                return ResourceManager.GetString("MzFragmentFinder__m_z__gt__precursor___minus__2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (m/z &gt; precursor) + 1.
        /// </summary>
        public static string MzFragmentFinder__m_z__gt__precursor___plus__1 {
            get {
                return ResourceManager.GetString("MzFragmentFinder__m_z__gt__precursor___plus__1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (m/z &gt; precursor) + 2.
        /// </summary>
        public static string MzFragmentFinder__m_z__gt__precursor___plus__2 {
            get {
                return ResourceManager.GetString("MzFragmentFinder__m_z__gt__precursor___plus__2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m/z &gt; precursor.
        /// </summary>
        public static string MzFragmentFinder_m_z__gt__precursor {
            get {
                return ResourceManager.GetString("MzFragmentFinder_m_z__gt__precursor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coefficent Of Variation.
        /// </summary>
        public static string NumericAggregate_Cv {
            get {
                return ResourceManager.GetString("NumericAggregate_Cv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mean.
        /// </summary>
        public static string NumericAggregate_Mean {
            get {
                return ResourceManager.GetString("NumericAggregate_Mean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard Deviation.
        /// </summary>
        public static string NumericAggregate_StdDev {
            get {
                return ResourceManager.GetString("NumericAggregate_StdDev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum.
        /// </summary>
        public static string NumericAggregate_Sum {
            get {
                return ResourceManager.GetString("NumericAggregate_Sum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string OptimizedMethodType_None {
            get {
                return ResourceManager.GetString("OptimizedMethodType_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precursor.
        /// </summary>
        public static string OptimizedMethodType_Precursor {
            get {
                return ResourceManager.GetString("OptimizedMethodType_Precursor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transition.
        /// </summary>
        public static string OptimizedMethodType_Transition {
            get {
                return ResourceManager.GetString("OptimizedMethodType_Transition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ion 1.
        /// </summary>
        public static string OrdinalFragmentFinder_ion_1 {
            get {
                return ResourceManager.GetString("OrdinalFragmentFinder_ion_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ion 2.
        /// </summary>
        public static string OrdinalFragmentFinder_ion_2 {
            get {
                return ResourceManager.GetString("OrdinalFragmentFinder_ion_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ion 3.
        /// </summary>
        public static string OrdinalFragmentFinder_ion_3 {
            get {
                return ResourceManager.GetString("OrdinalFragmentFinder_ion_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ion 4.
        /// </summary>
        public static string OrdinalFragmentFinder_ion_4 {
            get {
                return ResourceManager.GetString("OrdinalFragmentFinder_ion_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library and Filter.
        /// </summary>
        public static string PeptidePick_both {
            get {
                return ResourceManager.GetString("PeptidePick_both", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library or Filter.
        /// </summary>
        public static string PeptidePick_either {
            get {
                return ResourceManager.GetString("PeptidePick_either", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string PeptidePick_filter {
            get {
                return ResourceManager.GetString("PeptidePick_filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library.
        /// </summary>
        public static string PeptidePick_library {
            get {
                return ResourceManager.GetString("PeptidePick_library", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gene.
        /// </summary>
        public static string PeptideUniquenessConstraint_gene {
            get {
                return ResourceManager.GetString("PeptideUniquenessConstraint_gene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to none.
        /// </summary>
        public static string PeptideUniquenessConstraint_none {
            get {
                return ResourceManager.GetString("PeptideUniquenessConstraint_none", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to protein.
        /// </summary>
        public static string PeptideUniquenessConstraint_protein {
            get {
                return ResourceManager.GetString("PeptideUniquenessConstraint_protein", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to species.
        /// </summary>
        public static string PeptideUniquenessConstraint_species {
            get {
                return ResourceManager.GetString("PeptideUniquenessConstraint_species", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Large.
        /// </summary>
        public static string PointSize_large {
            get {
                return ResourceManager.GetString("PointSize_large", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string PointSize_normal {
            get {
                return ResourceManager.GetString("PointSize_normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small.
        /// </summary>
        public static string PointSize_small {
            get {
                return ResourceManager.GetString("PointSize_small", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X-Large.
        /// </summary>
        public static string PointSize_x_large {
            get {
                return ResourceManager.GetString("PointSize_x_large", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X-Small.
        /// </summary>
        public static string PointSize_x_small {
            get {
                return ResourceManager.GetString("PointSize_x_small", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circle.
        /// </summary>
        public static string PointSymbol_Circle {
            get {
                return ResourceManager.GetString("PointSymbol_Circle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diamond.
        /// </summary>
        public static string PointSymbol_Diamond {
            get {
                return ResourceManager.GetString("PointSymbol_Diamond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plus.
        /// </summary>
        public static string PointSymbol_Plus {
            get {
                return ResourceManager.GetString("PointSymbol_Plus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Square.
        /// </summary>
        public static string PointSymbol_Square {
            get {
                return ResourceManager.GetString("PointSymbol_Square", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Star.
        /// </summary>
        public static string PointSymbol_Star {
            get {
                return ResourceManager.GetString("PointSymbol_Star", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Triangle.
        /// </summary>
        public static string PointSymbol_Triangle {
            get {
                return ResourceManager.GetString("PointSymbol_Triangle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Triangle Down.
        /// </summary>
        public static string PointSymbol_TriangleDown {
            get {
                return ResourceManager.GetString("PointSymbol_TriangleDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X Cross.
        /// </summary>
        public static string PointSymbol_XCross {
            get {
                return ResourceManager.GetString("PointSymbol_XCross", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DIA-Umpire.
        /// </summary>
        public static string Protocol_dia_umpire {
            get {
                return ResourceManager.GetString("Protocol_dia_umpire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSConvert.
        /// </summary>
        public static string Protocol_msconvert {
            get {
                return ResourceManager.GetString("Protocol_msconvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string Protocol_none {
            get {
                return ResourceManager.GetString("Protocol_none", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quadratic.
        /// </summary>
        public static string QuadraticFit_quadratic {
            get {
                return ResourceManager.GetString("QuadraticFit_quadratic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ratio to Heavy.
        /// </summary>
        public static string RatioToLabel_ratio_to_heavy {
            get {
                return ResourceManager.GetString("RatioToLabel_ratio_to_heavy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ratio to Light.
        /// </summary>
        public static string RatioToLabel_ratio_to_light {
            get {
                return ResourceManager.GetString("RatioToLabel_ratio_to_light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 / x.
        /// </summary>
        public static string RegressionWeighting_1_over_x {
            get {
                return ResourceManager.GetString("RegressionWeighting_1_over_x", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 / (x * x).
        /// </summary>
        public static string RegressionWeighting_1_over_x_squared {
            get {
                return ResourceManager.GetString("RegressionWeighting_1_over_x_squared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string RegressionWeighting_none {
            get {
                return ResourceManager.GetString("RegressionWeighting_none", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use only scans within time frame of MS/MS IDs.
        /// </summary>
        public static string RetentionTimeFilterType_ms2_ids {
            get {
                return ResourceManager.GetString("RetentionTimeFilterType_ms2_ids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include all matching scans.
        /// </summary>
        public static string RetentionTimeFilterType_none {
            get {
                return ResourceManager.GetString("RetentionTimeFilterType_none", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use only scans within time frame of predicted RT.
        /// </summary>
        public static string RetentionTimeFilterType_scheduling_windows {
            get {
                return ResourceManager.GetString("RetentionTimeFilterType_scheduling_windows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blank.
        /// </summary>
        public static string SampleType_blank {
            get {
                return ResourceManager.GetString("SampleType_blank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double Blank.
        /// </summary>
        public static string SampleType_double_blank {
            get {
                return ResourceManager.GetString("SampleType_double_blank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality Control.
        /// </summary>
        public static string SampleType_qc {
            get {
                return ResourceManager.GetString("SampleType_qc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solvent.
        /// </summary>
        public static string SampleType_solvent {
            get {
                return ResourceManager.GetString("SampleType_solvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard.
        /// </summary>
        public static string SampleType_standard {
            get {
                return ResourceManager.GetString("SampleType_standard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string SampleType_unknown {
            get {
                return ResourceManager.GetString("SampleType_unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MS Amanda.
        /// </summary>
        public static string SearchEngine_MSAmanda {
            get {
                return ResourceManager.GetString("SearchEngine_MSAmanda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MSFragger.
        /// </summary>
        public static string SearchEngine_MSFragger {
            get {
                return ResourceManager.GetString("SearchEngine_MSFragger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MS-GF+.
        /// </summary>
        public static string SearchEngine_MSGFPlus {
            get {
                return ResourceManager.GetString("SearchEngine_MSGFPlus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max.
        /// </summary>
        public static string SelectOne_Max {
            get {
                return ResourceManager.GetString("SelectOne_Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min.
        /// </summary>
        public static string SelectOne_Min {
            get {
                return ResourceManager.GetString("SelectOne_Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C.
        /// </summary>
        public static string SequenceTerminus_C {
            get {
                return ResourceManager.GetString("SequenceTerminus_C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N.
        /// </summary>
        public static string SequenceTerminus_N {
            get {
                return ResourceManager.GetString("SequenceTerminus_N", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned to the protein with the most peptides.
        /// </summary>
        public static string SharedPeptides_AssignedToBestProtein {
            get {
                return ResourceManager.GetString("SharedPeptides_AssignedToBestProtein", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned to first protein.
        /// </summary>
        public static string SharedPeptides_AssignedToFirstProtein {
            get {
                return ResourceManager.GetString("SharedPeptides_AssignedToFirstProtein", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicated between proteins.
        /// </summary>
        public static string SharedPeptides_DuplicatedBetweenProteins {
            get {
                return ResourceManager.GetString("SharedPeptides_DuplicatedBetweenProteins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed (peptides must be unique to a single protein).
        /// </summary>
        public static string SharedPeptides_Removed {
            get {
                return ResourceManager.GetString("SharedPeptides_Removed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned to the protein group with the most peptides.
        /// </summary>
        public static string SharedPeptidesGroup_AssignedToBestProtein {
            get {
                return ResourceManager.GetString("SharedPeptidesGroup_AssignedToBestProtein", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned to first protein group.
        /// </summary>
        public static string SharedPeptidesGroup_AssignedToFirstProtein {
            get {
                return ResourceManager.GetString("SharedPeptidesGroup_AssignedToFirstProtein", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicated between protein groups.
        /// </summary>
        public static string SharedPeptidesGroup_DuplicatedBetweenProteins {
            get {
                return ResourceManager.GetString("SharedPeptidesGroup_DuplicatedBetweenProteins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed (peptides must be unique to a single protein group).
        /// </summary>
        public static string SharedPeptidesGroup_Removed {
            get {
                return ResourceManager.GetString("SharedPeptidesGroup_Removed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linear.
        /// </summary>
        public static string SimpleRegressionFit_linear {
            get {
                return ResourceManager.GetString("SimpleRegressionFit_linear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linear through zero.
        /// </summary>
        public static string SimpleRegressionFit_linear_through_zero {
            get {
                return ResourceManager.GetString("SimpleRegressionFit_linear_through_zero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string SimpleRegressionFit_none {
            get {
                return ResourceManager.GetString("SimpleRegressionFit_none", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equalize Medians.
        /// </summary>
        public static string SingletonNormalizationMethod_equalize_medians {
            get {
                return ResourceManager.GetString("SingletonNormalizationMethod_equalize_medians", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ratio to Global Standards.
        /// </summary>
        public static string SingletonNormalizationMethod_global_standards {
            get {
                return ResourceManager.GetString("SingletonNormalizationMethod_global_standards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string SingletonNormalizationMethod_none {
            get {
                return ResourceManager.GetString("SingletonNormalizationMethod_none", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantile.
        /// </summary>
        public static string SingletonNormalizationMethod_quantile {
            get {
                return ResourceManager.GetString("SingletonNormalizationMethod_quantile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Ion Current.
        /// </summary>
        public static string SingletonNormalizationMethod_tic {
            get {
                return ResourceManager.GetString("SingletonNormalizationMethod_tic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centroided.
        /// </summary>
        public static string String1FullScanMassAnalyzerType_centroided {
            get {
                return ResourceManager.GetString("String1FullScanMassAnalyzerType_centroided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum of transition areas.
        /// </summary>
        public static string SummarizationMethod_averaging {
            get {
                return ResourceManager.GetString("SummarizationMethod_averaging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turkey&apos;s Median Polish.
        /// </summary>
        public static string SummarizationMethod_medianpolish {
            get {
                return ResourceManager.GetString("SummarizationMethod_medianpolish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regression.
        /// </summary>
        public static string SummarizationMethod_regression {
            get {
                return ResourceManager.GetString("SummarizationMethod_regression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From filtered ion charges and types.
        /// </summary>
        public static string TransitionLibraryPick_all {
            get {
                return ResourceManager.GetString("TransitionLibraryPick_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From filtered ion charges and types plus filtered product ions.
        /// </summary>
        public static string TransitionLibraryPick_all_plus {
            get {
                return ResourceManager.GetString("TransitionLibraryPick_all_plus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From filtered product ions.
        /// </summary>
        public static string TransitionLibraryPick_filter {
            get {
                return ResourceManager.GetString("TransitionLibraryPick_filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string TransitionLibraryPick_none {
            get {
                return ResourceManager.GetString("TransitionLibraryPick_none", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Built in Views.
        /// </summary>
        public static string ViewGroup_ {
            get {
                return ResourceManager.GetString("ViewGroup_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DDA with MS1 filtering.
        /// </summary>
        public static string Workflow_dda {
            get {
                return ResourceManager.GetString("Workflow_dda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DIA.
        /// </summary>
        public static string Workflow_dia {
            get {
                return ResourceManager.GetString("Workflow_dia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRM.
        /// </summary>
        public static string Workflow_prm {
            get {
                return ResourceManager.GetString("Workflow_prm", resourceCulture);
            }
        }
    }
}
